### ISSUE TITLE
Request build for Debian 10 Buster x64

### ISSUE THREAD

**Issue by BusterRaid** [pwsafe/pwsafe#1003]
Hi.

Please could I request a build of the latest and greatest for Debian 10 Buster, x64 ?

I'm currently using V1.13 but that now seems a little behind the current release.

Thank you.

**Machine**:
Ancient Dell Inspiron 6400
Linux  4.19.0-24-amd64 #1 SMP Debian 4.19.282-1 (2023-04-29) x86_64 GNU/Linux
Debian Buster 10.13

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Core(TM)2 CPU         T7400  @ 2.16GHz
stepping	: 6
microcode	: 0xd1
cpu MHz	: 1222.350
cache size	: 4096 KB
physical id	: 0
siblings	        : 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		        : yes
fpu_exception	: yes
cpuid level	: 10
wp		        : yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm lahf_lm pti tpr_shadow dtherm
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 4327.38
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Core(TM)2 CPU         T7400  @ 2.16GHz
stepping	: 6
microcode	: 0xd1
cpu MHz	: 1244.654
cache size	: 4096 KB
physical id	: 0
siblings	        : 2
core id		: 1
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		        : yes
fpu_exception	: yes
cpuid level	: 10
wp		       : yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm lahf_lm pti tpr_shadow dtherm
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 4327.38
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

**Comment by ronys** [comment]
Done: https://github.com/pwsafe/pwsafe/releases/download/1.17.0/passwordsafe-debian10-1.17-amd64.deb

**Comment by BusterRaid** [comment]
Downloaded and tested on Debian Buster 10.13 x64 - Seems to work great. 
Thank you.
