### ISSUE TITLE
Windows 11 Password Field Focus when interacting with Password Safe 3.63.0 system tray icon

### ISSUE THREAD

**Issue by RolfWojtech** [pwsafe/pwsafe#1012]
The issue in #965 is not fully fixed yet.

When re-opening pwsafe from the system tray icon, the popup window receives focus but the "Master Password:" textbox does not receive focus.

Platform:
Microsoft Windows [Version 10.0.22621.1992] (22H2)
Password Safe V 3.63 64-Bit

I had commented it in the other ticket but I think it got missed, so feel free to reopen #965 and close this one as a duplicate.

**Comment by ronys** [comment]
This was supposed to have been fixed by changing the program's behavior so that a single click should be used to open from the system tray. If you're double-clicking out of habit, this could explain the problem on this version.
Can you try with a single click and confirm?

**Comment by RolfWojtech** [comment]
Confirmed, works with single click
