### ISSUE TITLE
Yes/No buttons: Use Delete/Cancel buttons instead of Yes/No before executing dangerous actions like Delete Group

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1020]
Today I have have pretty big disaster with Password Safe v3.63 on Windows 10, I have permanently lost 30+ passwords, because of two circumstances:
- my not the best setting in pwsafe,
- me as not reading Yes/No question with potential dangerous lost of data

What happened?
1. First my settings: menu Manage | Options | Backups
   - "Save database immediately after any change": checked
   - "Backup Name | Max=3"
2. I have changed some passwords, but because every change results in database save (first setting) and only having 3 backup history files I quickly run out of useful backup, the trap I have gotten into.
3. Then I notice one of my groups does not have the best name and I decided to rename the group. Right mouse click "Rename Group".
4. Question popped up and I clicked on Yes button. Yes, yes, yes, don't bother me I want to rename. But.... to my surprise whole group of passwords were deleted. What I most probably did is miss the "Rename Group" and click one selection bellow "Delete Group", but because I was convinced I was renaming I confirmed Yes without reading the message, but the message was most probably delete confirmation.
5. This should not be a problem. I closed down pwsafe and lets rename backup... But all backups are few seconds old. Upsss, I lost my passwords.

I don't blame the software, I have had dangerous settings and did not read the notification.

Now I did:
- unchecked "Save database immediately after any change" setting
- changed "Backup Name | Max=50"

But my recommendation for feature request: Please never ever use Yes/No questions when something potentially very dangerous fallows like deleting data. In my humble opinion Yes/No is pretty bad practice, because it forces user to actually read and understands the warning and then anxiously click and hope correct Yes or No is selected. Yes/No are dangerous because users are so annoyed with this kind of confirmations that they always click on Yes, because yet one more nag.

My recommendation is, when something dangerous follows name buttons so it is clear from the buttons itself (without reading actual warning) that something dangerous is potentially following. Instead of Yes and No buttons please use "Delete" and "Cancel". When I see Delete/Cancel combination I immediately know clicking on Cancel is something that gets me out of danger. And... if "Delete" buttons appears, it is immediately obvious that what follows is not "rename group" and in this case I would for sure read the notification massage.

---
I don't know if there are any other Yes/No questions, if they are, can you please consider changing to ACTION/Cancel variant.

**Comment by ronys** [comment]
Note that if you haven't exited PasswordSafe or closed the database, you can undo all operations, including group delete, by Crtl-Z or menu Edit->Undo. Perhaps too late for this time, but useful to keep in mind.

I'm not sure Delete/Cancel would help much in such cases, but I'll take a look to see how many places would be affected.

**Comment by igor2x** [comment]
I have found some user interface guidelines referring to Yes/No buttons.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/ec1c2dae-6275-4922-9758-a94687403421)
Details: https://uxplanet.org/primary-secondary-action-buttons-c16df9b36150

---
![image](https://github.com/pwsafe/pwsafe/assets/10895030/d3ddfdac-205b-49de-a5ed-36088c1f8fec)
Details: https://uxplanet.org/golden-rules-of-user-interface-design-19282aeb06b

**Comment by igor2x** [comment]
One additional Yes/No. Create new database and type in simple password and bellow dialog appears:

![image](https://github.com/pwsafe/pwsafe/assets/10895030/6ed1be6e-d4c5-4757-8f71-ca0cb5018c60)

1. Yes/No suggestion:
- change **No** with **Cancel** button
- change **Yes**  with **Use anyway** button

2. Different terminologies
- when new database is selected to be created there is "Safe Combination" terminology
- in dialog above there are two terminologies: "passphrase" and "Password"
I suggest to use only one terminology consistently to simplify wording.

**Comment by igor2x** [comment]
One additional Yes/No. Right click on empty space and select "Add entry".
Type in something in "Group" field and then click Cancel and bellow dialog appears:

![image](https://github.com/pwsafe/pwsafe/assets/10895030/08bf5d88-448f-442c-a3ad-097403959a67)

1. Yes/No suggestion:
-  change **No** with **Cancel** button
-  change **Yes** with **Discard** button

2. Wording
Wording of question is quite ambiguous. Question is: "Are you sure you want to cancel?" This "cancel" question it looks like it refers to  "Cancel" button from previous dialog and not to "cancel" current action. Probably better wording could be:
"One or more values have been changed." (I suggest new line here).
"Do you want to discard the changes?"

**Comment by igor2x** [comment]
One additional Yes/No. Do some changes and then click on "Close" button from toolbar and bellow dialog appears:

![image](https://github.com/pwsafe/pwsafe/assets/10895030/ec075fed-7f7d-48c5-a4af-cf217524ffef)

1. Yes/No suggestion:
- change **No** with **Discard**
- change **Yes** with **Save**
- **Cancel** button is fine just like it is

2. Order of buttons. Standard behavior of buttons are (on Linux): Cancel / Discard / Save.

3. Maybe add new line before database path.

**Comment by igor2x** [comment]
One additional Yes/No. After File | Merge bellow dialog appears.
![image](https://github.com/pwsafe/pwsafe/assets/10895030/51332cbb-ca53-48c8-8771-2cefc9231501)

1. Yes/No suggestion:
- change **No** with **Close**
- change **Yes** with **Details**

2. Dialog design. File | Merge could be improved from current:

![image](https://github.com/pwsafe/pwsafe/assets/10895030/627a7ae3-f528-4240-974a-7673be8ab72d)

My suggestion. Logic: when merging, I first ask myself what is "source" database and then what is "target" database and I expect dialogs to be positioned in this order. Also both input dialogs "source path" and "source password" should be grouped with square rectangle around it, to indicate this belongs together and "target" database is separate info.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/88252559-ff3a-41d2-81d3-5173fb377cfc)

Also button should not be just **OK**, but obvious action like **Merge**

3. Report dialog.
![image](https://github.com/pwsafe/pwsafe/assets/10895030/42241d66-9775-4136-94df-640837746bcb)
I love description of first two buttons, but the last one **Finish** is not the best. Finish is used when there are several wizard dialogs with Next buttons and then finally user gets to Finish that confirms some drastic change will happen or user has gotten to the end of wizard. I think in this case it would be better to use **Close** button, because nothing special is performed, just dialog is closed down.

**Comment by igor2x** [comment]
One additional this time OK/Cancel.

Lock the database and unlock it and bellow dialog appears.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/4b078edd-3b26-47f0-8d38-b1ede243b497)

1. OK/Cancel combination is also not user friendly:
- change **OK** with **Unlock**
- **Cancel** button is fine like it is now

The main mantra should be, from the button names it should be absolutely clear what ACTION will follow. OK doesn't really tell anything useful. To understand how design of dialog should be made, imagine you clicked on some ACTION from main application window with blind folded and now you take off blind fold and only think you see is input box and confirmation buttons like this:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/1e25beda-10f6-4f4c-a279-359bf8eb9579)

From above "Cancel" we can assume that dialog will disappear and we will be moved logically one action into the past. But what does "OK" button do? We have no idea. Now it makes more sense it should be "Unlock" button.

Why is this important. Working with program should be quick. Password Safe is not the program I spend hours a day, but password manager is mainly distraction of regular work. Like opening some program I am focused and working in, I just need to enter the userid and password I don't remember, so distraction switch to password manager and get the userid and password. If I am forced to read text, this distraction gets tiring.

2. Exit button.
In my humble opinion **Exit** button is by user unusual and unexpected feature and most probably very rarely used. What users expect to exit a program? Click on Cancel button and then in main program click on top right "X" to close a program.

3. Icon on the left.
What is the point of the Password Safe icon on the left. It doesn't tell user anything useful, it is actually only a distraction. General guidance should be minimalism, use only the UI components that are essential for solving the problem.

**Comment by igor2x** [comment]
One more thing to the previous dialog... UI guideline is to be minimalistic the text itself:
"Please enter the safe combination for this password database."

- Word "Please" looks nice, but it is redundant and unusual design.
- Message does not inform user what ACTION will follow, so why does user need to enter safe combination.
- Nitpicking, use ":" instead of "." to make it clear that file path that follows in next line is related to text message.

Suggestion: Enter safe combination to unlock database:
From the message above you tell user WHAT he or she should do and what ACTION will follow.
WHAT = enter safe combination
ACTION = database is going to be unlocked

**Comment by igor2x** [comment]
One additional Yes/No. Password Safe v3.65 on Windows 10.

1. Edit Entry
2. Right click text input box of Notes field.
3. "!Edit externaly" and Message is displayed: "WARNING: Use of an external editor may leave sensitive data on your hard disk. Do you wish to continue?"

Suggestion:
- change **Yes**  with **Continue anyway**
- change **No** with **Cancel**

**Comment by igor2x** [comment]
One additional Yes/No. Password Safe v3.65 on Windows 10.

1. File | Clear Recent Safe List
2. Dialog with: "Please confirm that you wish to clear the recent Safe list." and Yes/No button.

Suggestion:
- change **Yes** button with **Confim**
- change **No** button with **Cancel**

**Comment by igor2x** [comment]
Just in case if someone has bookmarked this issue. I have divided one single multi-post issues into several issues to follow one issue per bug report, so developers can easily digest them individually:
- https://github.com/pwsafe/pwsafe/issues/1120
- https://github.com/pwsafe/pwsafe/issues/1121
- https://github.com/pwsafe/pwsafe/issues/1122
- https://github.com/pwsafe/pwsafe/issues/1123
- https://github.com/pwsafe/pwsafe/issues/1124
- https://github.com/pwsafe/pwsafe/issues/1125
- https://github.com/pwsafe/pwsafe/issues/1126
- https://github.com/pwsafe/pwsafe/issues/1127
