### ISSUE TITLE
Crash on Recent Password Databases entering value greater then maximum allowed

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1021]
Password Safe v3.63 on Windows 10.
1. Menu Manage | Options | System.
2. In "Recent PasswordSafe Databases" into "Remember last databases" field type in 50.
3. Click on OK button to close dialog. Error message appears: "Enter an integer between 0 and 20."
4. Click  on OK button on error message. Yet another the same dialog appears "Enter an integer between 0 and 20".
5. Click on OK button again. Now crash window appears: "Sorry but PasswordSafe has had a problem. Minimal diagnostic information has been written to file... in your temporary directory. Dump: [PWS_Minidump_20230905_064345519.zip](https://github.com/pwsafe/pwsafe/files/12518902/PWS_Minidump_20230905_064345519.zip)
6. Clicking on Yes button and PasswordSafe program closes down.

Feature request:  I suggest in error to replace world "integer" with "number", so: "Enter a number between 0 and 20". Integer is fine from programmers point of view, but average user know what "number" is.

I have also tested Password Safe v1.71 on Ubuntu 23.04 and it does not crashes. Also no error is returned. When reentering Manage | Options and check for the value it is set to 20. It would still be nice to have some dialog message like in Windows.

**Comment by ronys** [comment]
Double error message and crash fixed in commit b96f35afb.
I agree that "number" would be clearer than "integer", but this message is generated by Windows' framework, and rewriting this to fix the text is painful. I will make this change in the texts that the program manages directly.
