### ISSUE TITLE
Double-click to unlock from Notification Area loses focus

### ISSUE THREAD

**Issue by tovodeverett** [pwsafe/pwsafe#1030]
I don't know if this issue cropped up because I upgraded from 3.59.0 to 3.63.0 or because I upgraded from Win11 21H2 to 22H2 recently (I did these both at the same time).  I am seeing the behavior on multiple machines.

I have my Password Safe icons in the Notification Area set to always display.  Historically, I have unlocked a locked database using a double-click on the Password Safe icon in the Notification Area.  Since my most recent upgrade, this results in the "Enter Master Password" dialog popping up, but **without** focus.  After further investigation, I discovered that if the right-click menu and "Unlock Safe", then the "Enter Master Password" menu entry, then the "Enter Master Password" dialog does get focus.  I also discovered that a single-click on the Password Safe icon in the Notification Area will display the "Enter Master Password" dialog **with** focus.  I don't know if single-click was an option in the past, so if that change was made between 3.59.0 and 3.63.0, then perhaps it is treating the double-click as a single-click, which opens the dialog with focus, and then the second click is sending focus back to the Task Bar.

Obviously I can work around this by retraining myself to single-click, but it is a definite UI annoyance.

**Comment by mhudec** [comment]
For me the doublelicking loosing focus might have been resolved by Windows 11 November patches (https://support.microsoft.com/en-us/topic/november-14-2023-kb5032190-os-builds-22621-2715-and-22631-2715-f9e3e13c-5e98-42c2-add8-f075841ca812), though I do not see anything about it in the patches' release notes.
