### ISSUE TITLE
Can't update to 3.64

### ISSUE THREAD

**Issue by bcosell** [pwsafe/pwsafe#1037]
This on win10/pro:  when I try to do the update, it says "Please exit all running instances....".  And I exited PWsafe.  got the same error. I then check taskmanager and , indeed, I had no instances of pwsafe running.   What is blocking the update??

**Comment by ronys** [comment]
Clicking on the 'X' on top of the app's window doesn't exit the program, it just closes its window.
To exit either use File->Exit, or right-click and select Exit on the PasswordSafe icon in the taskbar (system tray).

Let me know if this still occurs, and I'll reopen the issue.
