### ISSUE TITLE
macOS wxWidgets Warning on start: Cannot set locale to language "English (Germany)".

### ISSUE THREAD

**Issue by raymanP** [pwsafe/pwsafe#1039]
Is not a affecting the program, but confusing.
Please fix if possible for next version.

Thank you, laos for the grat program!

**Comment by nobugshere** [comment]
German English?  I didn't know there was such a thing :-)  The README.MAC.DEVELOPERS.md file has a note that might be what you are seeing.  The suggested fix is to open a file, goto "Manage->Select Language", and pick the one you want.  

https://github.com/pwsafe/pwsafe/blob/master/README.MAC.DEVELOPERS.md#known-issues-with-macos-install

**Comment by raymanP** [comment]
I think I tried it already, but now it worked. Thank you!!
