### ISSUE TITLE
Check pws_* dll signatures

### ISSUE THREAD

**Issue by ronys** [pwsafe/pwsafe#1041]
Although dll's are signed, there's no check of their authenticity when they're loaded.

**Comment by ronys** [comment]
Fixed in commit 7dd0ff5cc

**Comment by ronys** [comment]
I'd expect a certificate check perhaps, e.g., OCSP.
What server/protocol are you seeing?

**Comment by zM-3Cz-x67vB** [comment]
Seeing a bunch of different addresses all on port TCP/80. 
They occur when I first launch which might be consistent with cert check (or for the security conscious, someone is trying to capture the safe/master pw). If the initial connection is blocked, every time I unlock  the safe it tries to connect to these addresses again. 
23.221.22.78
23.221.22.86
23.221.22.72
23.220.161.217
23.223.240.80

Looking at the code comments, it sounds like I could (not necessarily should) trust some cert in my local store. Which one?

**Comment by ronys** [comment]
Well, port 80 is consistent with OCSP.
I don't see any such traffic on my machine, might be worth sniffing with wireshark to see the exact requests.
You can see the certificate chain via right-click->Properties on the exe, installer or dll files. Details, View Certificate, Certification Path will show the certificate chain.

In any case, if someone were trying to exfiltrate any sensitive data, port 80 is an odd choice.

**Comment by ronys** [comment]
certum.pl is the issuer of the certificate used to sign pwsafe's executables and dlls.
This request is an attempt by Window's runtime to check the validity of the signing certificate: The crl is a certificate revocation list.
The next release will address this issue so that no outgoing traffic requests will be made while checking the signatures.
