### ISSUE TITLE
Password Safe not visible on VMware Virtual Desktops after update

### ISSUE THREAD

**Issue by JohnPhem14** [pwsafe/pwsafe#1046]
We are seeing a weird reaction possibly caused by the new feature of blocking screen grabs. We use VMware Horizon client to access our VDI environment. Since installing 3.64.0 that has the block of screen grab we are not able to have Password Safe open up to see their information since we added the update to our environment. It comes up[ blank. Wondering if anyone else who uses Password Safe with VMware VDI seeing the same issue.

**Comment by ronys** [comment]
Yes, this is expected. See the online help for workarounds, specifically, the --allow-screen-capture command line argument and "Exclude from screen capture" option in the Security Tab.
