### ISSUE TITLE
Question about the staus of coretest on Linux

### ISSUE THREAD

**Issue by nobugshere** [pwsafe/pwsafe#1051]
After successfully building pwsafe from , I tried running "make test" from my build directory.  Coretest reported 8 failures (see attached log.)  
[LastTest.log](https://github.com/pwsafe/pwsafe/files/13234353/LastTest.log)

These failures occurred when pulled from git tag 1.18.0, but it also happens on 1.17.0.  This was on Fedora 38 Arm and wxWidgets 3.2.2.1.

Before I dig into them, I just wanted to know if this is a known issue, I did something wrong, or if this test just doesn't work in this environment.

Thanks, 
Richard

**Comment by ronys** [comment]
Looks like all the tests that read/write files are failing.
The tests assume that they're run in the src/test directory, with a 'data' subdirectory.
Did you use cmake to build & run tests? Cmake copies these under the build directory and runs them correctly.

**Comment by nobugshere** [comment]
I create and cd to the build directory then run "cmake ..;make".  When the build completes, coretest is under the src/test sub-directory with the data directory, as you described.  But, I'm still not clear on how to properly invoke the test.  Running "make test" invokes ctest and produces the output above, whether I run it from the build dir or src/test.  Cd to src/test and run "./coretest" also fails.  What's the command and what directory should I run it from?

**Comment by ronys** [comment]
Running 'make test' from the build directory should work - that's what I do.
Ultimately it runs coretest from build/src/test.
Perhaps there's a file permission problem? Did you checkout and build the repo under the same user you're running the tests under?

Other possibility is that's it's somehow due to the distro + ARM architecture. I've successfully built the project on a Raspberry Pi under Debian, though. Odd.

**Comment by nobugshere** [comment]
I do all the work under the same user; the permissions look good.  So far, I've tracked the initial error to the check starting at CoreImpExp.cpp:1083
```
    // convert linebuf from UTF-8 to StringX
    StringX slinebuf;
    if (!conv.FromUTF8(reinterpret_cast<const unsigned char*>(linebuf.c_str()),
      linebuf.length(), slinebuf)) {
      // XXX add an appropriate error message
      numSkipped++;
      continue;
    }
```

**Comment by nobugshere** [comment]
I figured it out: it was my locale setting. I had LC_ALL=POSIX set in my environment. If I unset LC_ALL, and let it default to en_US.UTF-8, "make test" works from either the build directory or build_dir/src/test.  Submitted PR #1052 to update the build instructions.
