### ISSUE TITLE
macOS: add support for Yubikey

### ISSUE THREAD

**Issue by raymanP** [pwsafe/pwsafe#1056]
Yet I was not able to use Yubikey with PasswordSafe on macOS. It is not displayed as option when Yubikey is inserted.

If someone shows me the code parts where to integrate (I think should be similar to Linux), I could try to do that.

Kind regards, Reimund

**Comment by ronys** [comment]
Well, to start you need the equivalent of libyubikey-dev and libykpers-1-dev, which, if not already available on Mac, can probably be built from the relevant Yubico GitHub repos (https://github.com/Yubico/yubico-c, https://github.com/Yubico/yubikey-personalization, I think).
After that, Mac versions of src/os/unix/PWYubi.{h,cpp} need to be developed.
The wx CmakeLists.txt will detect the existence of ykpers header files, and add the relevant source and header files to the build (YubiCfgDlg, YubiMixin).

Looking forward to a PR!

**Comment by nobugshere** [comment]
I was able to get a clean build using the libraries installed via Homebrew, but I don't have a Yubikey to test it.  Since Homebrew libs are neither static nor universal, it's not really something I would recommend for general release.  If there's sufficient interest, and no license issues, I could look into a static/universal build.

The _*strictly experimental*_ version is [here](https://github.com/nobugshere/pwsafe/tree/MacYubi). 
*"brew install yubikey_personalization"* will install the necessary dependencies.  To build it locally, you need wxWidgets which you can also get via brew.  See the [README.MAC.DEVELOPERS.md](https://github.com/nobugshere/pwsafe/blob/MacYubi/README.MAC.DEVELOPERS.md) file.

**Comment by ronys** [comment]
Nice.

If you wish, we can create a 'macyubi-test' branch on the main pwsafe repo, and offer a .dmg artifact for people to test.

**Comment by raymanP** [comment]
Great, sounds very promising. Thank you for the fast response :-) 
I'll try to build ykpers without brew...

**Comment by raymanP** [comment]
Here's how to build the universal libs:

Build universal libyubikey:
```
curl https://developers.yubico.com/yubico-c/Releases/libyubikey-1.13.tar.gz --output libyubikey.tar.gz
tar -xf libyubikey.tar.gz
cd libyubikey-1.13
./configure CC="gcc -arch x86_64 -arch arm64" \
                CXX="g++ -arch x86_64 -arch arm64" \
                CPP="gcc -E" CXXCPP="g++ -E"
make check
make install
```
Build universal ykpers-1:
```
curl https://developers.yubico.com/yubikey-personalization/Releases/ykpers-1.20.0.tar.gz --output ykpers.tar.gz
tar -xf ykpers.tar.gz
cd ykpers-1.20.0
./configure CC="gcc -arch x86_64 -arch arm64" \
                CXX="g++ -arch x86_64 -arch arm64" \
                CPP="gcc -E" CXXCPP="g++ -E"
make check
make install
```

Yet I don't know how to specify for which darwin/macOS version to build. I expect them to build on the installed xcode version.

Maybe someone of you knows?

**Comment by nobugshere** [comment]
> If you wish, we can create a 'macyubi-test' branch on the main pwsafe repo, and offer a .dmg artifact for people to test.

@ronys ,
That would be great.  I think we're close to having something to try.

**Comment by nobugshere** [comment]
> Here's how to build the universal libs:

@raymanP,
Excellent! That's a big help.  I integrated that into the GitHub workflow and adjusted the parameters a bit.  You can see it [here](https://github.com/nobugshere/pwsafe/blob/MacYubi/.github/workflows/macos-latest.yml). 

It looks like I got a good build.  It's static, universal and, when I run it on my M1 Sonoma system, it has a "Manage->YubiKey..." menu item that I'm sure wasn't there before :-). It pops-up a dialog asking me to insert my YubiKey!

If you're eager to try it, [here's the build artifact](https://github.com/nobugshere/pwsafe/suites/18399910543/artifacts/1066039425).

**Comment by raymanP** [comment]
@nobugshere  That's great! I tried it and it shows the "Manage->YubiKey...", however, the yubikey is not detected when insterted. Also in the database openening mask nothing happens.

How is best to debug that? Is there a verbosity option to display more informations?
When using debugger (Eclipse?) someone knows where to look for the critical section?

Looking forward for some tips ;)

**Comment by raymanP** [comment]
I see now, the libs are not packaged into the .dmg file

**Comment by raymanP** [comment]
If using `otool -L pwsafe` to check it's dependencies it shows no ykpers-1 dependency. This coild be the main cause why the yubikey is not detected. Anyone knows where to add the dependencies?

**Comment by nobugshere** [comment]
Thanks for the reference, I'll take a look at it.  The WX and Yubi libs were static linked into the executable, so they won't show up in `otool -L`.  That build was really set-up for a release configuration; maybe a little overconfident :-).  I made a new branch: [MacYubi-debug](https://github.com/nobugshere/pwsafe/tree/MacYubi-debug) that is set-up for a debug build, which disabled some runtime hardening and should look for the Yubi libs in /usr/local/lib (I didn't bundle any with the app).  Just out of curiosity, do you have an Intel or Apple Silicon Mac?

It looks like all the calls to libykpers are through the routines in src/os/unix/PWYubi.cpp

[Here is the .dmg file](https://github.com/nobugshere/pwsafe/suites/18425742900/artifacts/1068025597)
```
pwsafe.app/Contents/MacOS/pwsafe (architecture x86_64):
	/usr/local/lib/libykpers-1.1.dylib (compatibility version 22.0.0, current version 22.0.0)
	/usr/local/lib/libyubikey.0.dylib (compatibility version 2.0.0, current version 2.7.0)
pwsafe.app/Contents/MacOS/pwsafe (architecture arm64):
	/usr/local/lib/libykpers-1.1.dylib (compatibility version 22.0.0, current version 22.0.0)
	/usr/local/lib/libyubikey.0.dylib (compatibility version 2.0.0, current version 2.7.0)
```

**Comment by raymanP** [comment]
Still not working, I'll try to debug on Sunday hopefully

**Comment by nobugshere** [comment]
Do any of the ykpers executables work?  (/usr/local/bin/ykinfo, etc.) They would be easier to troubleshoot if they don't detect the key.

**Comment by raymanP** [comment]
Great, that was the problem. The kyinfo v1.20 is not working. Need to build latest libs from repository:

* https://github.com/Yubico/yubico-c/archive/refs/heads/master.zip
* https://github.com/Yubico/yubikey-personalization/archive/refs/heads/master.zip

After extracting use:
`autoreconf --install`
and then the other options commands

After that the `debug` version is working. The static is failing I think due to the old libs. 

@nobugshere Could you please generate a release version with libs build form the repositories.

I had a problem with the repositories buildng them. The manuals failed ti build using asciidoc, so I just disabled the manuals building in the Makefile, in case you encounter the same problem: remove targets at: `dist_man1_MANS` or `dist_man_MANS`

**Comment by nobugshere** [comment]
Try [this one](https://github.com/nobugshere/pwsafe/suites/18507571263/artifacts/1073977927).  It was built with no debug and the hardened runtime enabled.  From the [MacYubi branch](https://github.com/nobugshere/pwsafe/tree/MacYubi)

The Yubico libs were built from the master head of their repos.  Adding --disable-documentation to the configure command got rid of the a2x problem.  Here's what I used for both libs:
`./configure --disable-shared --disable-documentation CFLAGS="-O2 -arch arm64 -arch x86_64 -mmacosx-version-min=10.14`

Just for the record, what kind of Mac and Yubikey are you using?

**Comment by raymanP** [comment]
Great @nobugshere , I have intel and apple chip macbooks with macOS 14.1, on both working with the new version and without the need of any external lib. Older macOS should be tried, but for now seems very good. Thank you @nobugshere and also @ronys for the fast responses and support :)))

**Comment by raymanP** [comment]
Someone then makes a pull request?

**Comment by nobugshere** [comment]
Hi @raymanP ,
Sorry for the delay.  I was playing around with the build options a bit.  How is it working for you?  I assume it must be going well.

Hi @ronys ,
I'm about ready to push this.  Do you still want to make a separate branch for wider testing, or shall I just send a regular PR?

**Comment by raymanP** [comment]
Hi @nobugshere , is working on my both apple and intel macOS perfectly!! No hurry :+1:
