### ISSUE TITLE
macOS: Update packaging and include language translations

### ISSUE THREAD

**Issue by nobugshere** [pwsafe/pwsafe#1063]
The current release build workflow does not include the language files or any other docs.  The makefile used for the manual process does include languages, release notes, and has a fancy background image.  Using that as a basis, I'm reworking the GitHub workflow to include all this and more! 

Here's a sample:
![Screenshot 2023-12-02 at 9 49 46 PM](https://github.com/pwsafe/pwsafe/assets/61946508/cea1cad9-308c-4662-8ca9-b8e11862a62e)

**Comment by ronys** [comment]
Excellent - looking forward to your PR.
