### ISSUE TITLE
Bug: Autotype skips \ in username in versions after 3.61 

### ISSUE THREAD

**Issue by tlourey** [pwsafe/pwsafe#1064]
I have an entry that has a \ in the username.  On newer version it is not typed. Below is what I have noted in terms of version numbers. 

When using auto type: 
- it **is** typed/passed in 3.61 64 bit
- it is **not** typed/passed in 3.64.1 32 bit
- it is **not** typed/passed in 3.64.0 32 bit
- where I say it is not typed, it just skips that character. 

I haven't tried to update to a newer 64 bit version. I didn't mean to go back to 32 bit, but it is where I noticed it. When I went back to 3.61 64 bit its working again. 

In this particular case the password is an alias so I can't retype the username.

**Comment by tlourey** [comment]
Also @ronys not sure if bugs should be in github or sourceforge. I went with what was easy. Let me know if you want this put into source forge.

**Comment by tlourey** [comment]
Created https://sourceforge.net/p/passwordsafe/bugs/1583/ as I think bugs should be created in sourceforge but I'm not 100% sure.

**Comment by ronys** [comment]
Both GitHub and SourceForge are fine for creating bugs. Closing this as duplicate.
