### ISSUE TITLE
Signature verification may cause net traffic

### ISSUE THREAD

**Issue by ronys** [pwsafe/pwsafe#1066]
The dll verification check added for https://github.com/pwsafe/pwsafe/issues/1041 causes network traffic (probably OCSP checks) as part of the signature verification.
This may cause delays in environments where these requests are blocked.

**Comment by mitch-PetroAus** [comment]
I can reproduce the delay - although I don't know for sure what is causing it.
Using a clean Windows 7 SP1 64 bit on a VM (with network access, and no known blocks), and 64-bit pwsafe 3.64.1 extracted from *.bin.zip (not running any installer). ...
If the CA root certificate Certum Trusted Netword CA 2 is not installed (which is the case in my clean VM), there is a 70 second delay starting pwsafe.
If I manually install the CA root certificate (exported from the host PC, which does have it) on that same VM, pwsafe starts immediately.
I've run this test several times (including simultaneously on two separate VMs, in case of intermittent network issues) and the results seem to be consistent.

**Comment by ronys** [comment]
The delay is probably due to Windows requesting the root certificate from Certum, the request being blocked, e.g., by a firewall, and eventually timing out.

The next release will disable outgoing traffic requests for certificate validation.
