### ISSUE TITLE
Link to 1.18.2 is broken

### ISSUE THREAD

**Issue by seamusdemora** [pwsafe/pwsafe#1078]
The link to d/l 1.18.2 from SourceForge is broken; i.e. it does not work.

**Comment by ronys** [comment]
I've moved it from https://sourceforge.net/projects/passwordsafe/files/1.18.2/ to https://sourceforge.net/projects/passwordsafe/files/Linux/1.18.2/

Please let me know if the latter is broken - looks ok from my browser.

**Comment by seamusdemora** [comment]
Is this what you intended to show? There's a link to d/l 1.18.2 below this... but this banner says 1.12?!

<img width="1008" alt="Screenshot 2024-01-23 at 1 17 59 PM" src="https://github.com/pwsafe/pwsafe/assets/14911811/f5178799-3220-4c8e-b632-d02501695edb">

**Comment by ronys** [comment]
Thanks - I forgot to update the default download for MacOS and Linux. Fixed.
