### ISSUE TITLE
Bold vs. regular header in View | Flattened List

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1082]
I installed Password Safe v1.18.2 on Ubuntu 23.10
1. Using deb package.
2. Install flatpak from today PR on flathub.

Some small differences:
a) flatpak contains icon on top left that should not be there
b) deb package has no bold header of password stable

![image](https://github.com/pwsafe/pwsafe/assets/10895030/1c4fadb3-fe21-42fd-8412-1f519b20605f)

**Comment by rafaelx** [comment]
Same as in #1083. The visual appearance of the header may depend on the wxWidgets version.
The style flags or font properties could be checked.

**Comment by igor2x** [comment]
I have now self-compiled it from master branch and table headers are in bold. Maybe something has changed in Password Safe code or some package e.g. wxWidgets have been updated.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/21c784fc-c8c3-4e23-8faf-9176515f5d81)

This issue can probably be closed down.
