### ISSUE TITLE
Safe Combination vs. Master Password wording between Linux and Windows versions

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1085]
In Windows 10 using Password Safe v3.65, menu Manage  | Master Password
![image](https://github.com/pwsafe/pwsafe/assets/10895030/7adc7440-cf81-40fc-9d13-f407a3f27b31)

On Ubuntu 23.10 using Password Safe v1.18.3, menu Manage | Change Safe Combination.
![image](https://github.com/pwsafe/pwsafe/assets/10895030/b98a562c-3f03-417b-b903-7c22641be631)

Two different wordings. If we follow the "inclusive language" both wordings show be the "Safe Combination".

P.S. By the way in my humble opinion checkbox name "Show Combination" should be changed to "Show Safe Combination", to make it clear what this checkbox does or even better "Visible".

P.S.S Also at first I was confused the logic of "Confirmation". Maybe whole wording could be better. Like:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/a31f4c9a-87ad-46d0-a12b-9e6f644dc3c9)

**Comment by igor2x** [comment]
Similar issues:
- First window after program starts (left side)
- Toolbar "Lock" and then unlock (right side)

On top Windows, on bottom Linux.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/ffca57f0-2090-446a-8a04-a0563d41d8eb)

**Comment by igor2x** [comment]
Similar "master password" vs. "safe combination" issues:

Left side images: First window after program starts.
Right site images: Toolbar "Lock" and then unlock.
On top Windows, on bottom Linux.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/5ad1df50-d717-416c-b2e2-c223bd2af894)

Current wording:
"Please enter the Master Password for this password database."

Suggestion:
"Enter the Master Password for unlock password database:"

**Comment by igor2x** [comment]
Similar issues. Print screen:
- First window after program starts (left side)
- Toolbar "Lock" and then unlock (right side)
- On top Windows, on bottom Linux.

Looking at above print-screens:
1. Color icon of Password Safe in Linux is black. It should be dark red (like on Windows).
2. Wording "Open Password Database" may be strange working. Why "open"? What does it mean? "open as noun" or "open as verb". It can also be wrongly understood as "been open". To simplify I suggest removing word "Open" from the string.
3. Current wording: "Please enter the Master Password for this password database."
    Suggestion: "Enter the Master Password for unlock password database:"

![image](https://github.com/pwsafe/pwsafe/assets/10895030/919ba122-9a41-4991-9d33-f2cf37a607bb)

**Comment by igor2x** [comment]
Like discussed by mail with @ronys we should use Windows wording, so "master password". I have also checked with other password managers and I see "master password" is really common in other programs.

Suggested task:
1. Make Linux dialog like Windows one.
2. Remove word Please from both Windows and Linux, because this word is redundant. You don't see this in other programs, simplicity.

**Comment by ronys** [comment]
Fixed in pr #1111
