### ISSUE TITLE
Why are releases hosted on SourceForge?

### ISSUE THREAD

**Issue by julie777** [pwsafe/pwsafe#1090]
I do not understand why I cannot just download the releases here on GitHub.

**Comment by igor2x** [comment]
You can download it from GitHub too.

See official web site:
https://www.pwsafe.org/
and scroll down to the bottom and look at the bottom-left site of web page and there is link to GitHub download page.

**Comment by ronys** [comment]
PasswordSafe started off by being hosted on SourceForge (before GitHub existed), and switched to GitHub as the main repo a while ago, keeping SourceForge  as a backup repo.

In any case, the downloads on GitHub can be found at https://github.com/pwsafe/pwsafe/releases
