### ISSUE TITLE
macOS: There's a new runner in town

### ISSUE THREAD

**Issue by nobugshere** [pwsafe/pwsafe#1096]
I came across [this announcement](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/) on Github that says a new macos-14 runner and M1 build hosts will become macos-latest sometime in Q2.  To get a head start on testing it, and other changes, I submitted PR #1095.  Since the new runner is still tagged as "beta" I made it a draft PR.  However, I've been building and using the same combination on my own system for some time now.  The only problem I have encountered with WX 3.2.4 was the one patched in PR #1069.

**Comment by seamusdemora** [comment]
That sounds pretty cool, but does that mean that you are compiling all of the software for `pwsafe` on a "cloud" system inside GitHub?

**Comment by nobugshere** [comment]
> ...does that mean that you are compiling all of the software for pwsafe on a "cloud" system inside GitHub?

Yes, at least the Mac version.  It was using a macOS 12, x86_64 VM.  Now, they've added some M1 systems and made a new macOS 14.4 image for them.  However, pwsafe itself is still built as a universal binary targeting macOS 10.14 and up.

**Comment by seamusdemora** [comment]
hmm... *"new macOS 14.4 image"*  I _hope_ that doesn't mean I'll be forced to upgrade my OS to Sonoma (from Ventura) anytime soon??
