### ISSUE TITLE
Mac .dmg for v1.18.2 error: "can't be opened because Apple cannot check it for malicious software" 

### ISSUE THREAD

**Issue by tinker2much** [pwsafe/pwsafe#1098]
The latest Mac build (PasswordSafe-macOS-1.18.2-universal.dmg) [downloaded here](https://sourceforge.net/projects/passwordsafe/files/Linux/1.18.2/PasswordSafe-macOS-1.18.2-universal.dmg/download) fails with the message mentioned above and seen in the attached screenshot, below. 

This is on a MacBook Air M2 under Sonoma. 

 
![pwsafe_needs_updated](https://github.com/pwsafe/pwsafe/assets/57112204/e6e0383a-94e8-4141-a287-1abcdf6f17cb)

**Comment by nobugshere** [comment]
That is a standard "feature" of macOS to warn about apps that were not signed by an Apple issued (and paid for) developer certificate.  After you open it once, it won't complain any more.  At least, not until the next update :-( .  To validate the release, @ronys provides a GnuPG .sig file for the dmg package.

**Comment by tinker2much** [comment]
Ah! I saw the "cannot be opened" but completely missed the offered "open" button right below. You're correct, it opens fine the second time. Sorry to bother you.

**Comment by seamusdemora** [comment]
@nobugshere 
> That is a standard "feature" of macOS to warn about apps that were not signed by an Apple issued (and paid for) developer certificate. After you open it once, it won't complain any more. At least, not until the next update :-( . To validate the release, @ronys provides a GnuPG .sig file for the dmg package.

Richard - You're much too polite :)    **_"feature"_** indeed!
