### ISSUE TITLE
Password Safe is not buildible on Ubuntu 23.10

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1107]
On Ubuntu 23.10 I tried to build Password Safe from source code following official [Password Safe building instructions.](https://github.com/pwsafe/pwsafe/blob/master/README.LINUX.DEVELOPERS.md)

`$ git clone https://github.com/pwsafe/pwsafe.git`
Cloning into 'pwsafe'...
remote: Enumerating objects: 124546, done.
remote: Counting objects: 100% (4354/4354), done.
remote: Compressing objects: 100% (1635/1635), done.
remote: Total 124546 (delta 2803), reused 4021 (delta 2676), pack-reused 120192
Receiving objects: 100% (124546/124546), 121.50 MiB | 3.22 MiB/s, done.
Resolving deltas: 100% (87032/87032), done.
`$ cd pwsafe`
`$ sudo sh Misc/setup-linux-dev-env.sh`

Reading package lists...
Building dependency tree...
Reading state information...
cmake is already the newest version (3.27.4-1).
fakeroot is already the newest version (1.32.1-1).
g++ is already the newest version (4:13.2.0-1ubuntu1).
gettext is already the newest version (0.21-13).
git is already the newest version (1:2.40.1-1ubuntu1).
libgtest-dev is already the newest version (1.13.0-5).
libcurl4-openssl-dev is already the newest version (8.2.1-1ubuntu3.2).
libqrencode-dev is already the newest version (4.1.1-1).
libssl-dev is already the newest version (3.0.10-1ubuntu2.2).
libuuid1 is already the newest version (2.39.1-4ubuntu2).
libwxgtk3.2-dev is already the newest version (3.2.2+dfsg-4).
libxerces-c-dev is already the newest version (3.2.4+debian-1ubuntu0.23.10.1).
libxt-dev is already the newest version (1:1.2.1-1.1).
libxtst-dev is already the newest version (2:1.2.3-1.1).
libykpers-1-dev is already the newest version (1.20.0-3).
libyubikey-dev is already the newest version (1.13-6).
make is already the newest version (4.3-4.1build1).
pkg-config is already the newest version (1.8.1-2).
uuid-dev is already the newest version (2.39.1-4ubuntu2).
zip is already the newest version (3.0-13).
libmagic-dev is already the newest version (1:5.44-3).
ninja-build is already the newest version (1.11.1-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package dpkg-sig
dpkg-sig isn't mandatory

I checked the sh file and script fails at:
`apt-get install -qy dpkg-sig || (echo "dpkg-sig isn't mandatory"; true)`

I tried to execute command:
`sudo apt-get install -qy dpkg-sig`

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package dpkg-sig

From above error, package "dpkg-sig" is not available in Ubuntu 23.10. I have [searched the web and found](https://github.com/rstudio/rstudio/issues/14115) that Ubuntu 23.10 does not have this "dpkg-sig" package anymore in its repository.

Any other way to build Password Safe on Ubuntu 23.10?

**Comment by ronys** [comment]
That's not a failure. You should be able to proceed with building under Ubuntu.

**Comment by igor2x** [comment]
Yes, I was able to compile the Password Safe after all. I was just confused that script finished with "error" and it is fine.
