### ISSUE TITLE
Window resize value saved in pwsafe.cfg is off by factor of the Windows 11 system scale config value

### ISSUE THREAD

**Issue by sdbenting** [pwsafe/pwsafe#1112]
I just bought a new laptop which is using Windows 11.  (Windows 11 Home, 23H2 with os build 22631.3155, in case that matters.)  As I installed a fresh copy of pwsafe 3.65, I found that the window size was incorrectly saved (presumably after anything triggers a config change.)

I realized that with my 4k screen resolution, the default setting is to scale by 250% (which generally works well).  After forcing a size change by modifying pwsafe.cfg manually and saving a copy before restarting, I was able to confirm.  The position section of the file I modified manually reads:
```
      <Position>
        <top>0</top>
        <bottom>1518</bottom>
        <left>0</left>
        <right>1562</right>
      </Position>
```
But after the file was next saved when I closed the program, it was changed to 
```
      <Position>
        <top>0</top>
        <bottom>607</bottom>
        <left>0</left>
        <right>625</right>
      </Position>
```
A quick calculation shows that 1518/2.5 is 607.2 and 1562/2.5 is 624.8.  With integer rounding, that makes sense as though the scale is getting reset.

**Comment by sdbenting** [comment]
Forgot to mention that my old laptop was running Windows 10 with the same display resolution and scale settings, and that I didn't see this trouble with the version of 3.54 that I had been using.  Since I still have the old laptop, I updated to 3.65 and don't see this behavior -- the window size from the pwsafe.cfg file appears to be respected for window position.

**Comment by ronys** [comment]
There's a pre-release fix for this in https://sourceforge.net/projects/passwordsafe/files/PreReleases/3.65.1pre/
Unfortunately, support issues with the project's certificate provider (Certum) are preventing me from making a formal release with this fix. Hopefully this will be resolved in a few days.

**Comment by sdbenting** [comment]
Just downloaded the official 3.65.1 and it happily sized the window correctly.  Looks like this is good now.  Thanks for the quick turnaround.
