### ISSUE TITLE
Three times incorrect password attemts, differences between Windows and non-Windows

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1115]
In first dialog after Pasword Safe is started.

Type in incorrect password for 3 times and on Windows:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/f15fb2c7-044c-4d45-a38a-97a11cc5e695)

The same on Linux:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/cf7515d3-922a-45e7-97bc-d51839fadaaa)

Also on Windows OK button just closes current dialog and next try of master password can be entered.
On Linux it closes down Password Safe program.

I like Windows behavior more:
- error message is more descriptive
- why should we close down program - master password should be complicated, user probably typed in wrong password 3-times in a role (we should fight brute force with some other mechanism like 30 seconds password can't be entered or similar)

My suggestion is, make on Linux the same as on Windows:
- make the same wording
- don't close down program after 3-times incorrect master password

**Comment by igor2x** [comment]
On Linux, now I have also tested the Lock database and then try to unlock the database.
Dialogs are the same as on main Master Password Entry dialog. When changing it should be changed in one task.

Additionally what I see when master password is typed in three times or more (on locked database) the "Too many retries-exiting" dialog appears on Linux, but actually clicking on OK button Password Safe does not exit.

Suggestions:
- In my humble opinion we should unify dialogs  between Windows and Linux. Partially changed in [PR 1114.](https://github.com/pwsafe/pwsafe/pull/1114)
- On Linux if 3-times incorrect master password is entered, Password Safe program should not exit.

**Comment by rafaelx** [comment]
I'm not quite sure what exactly is left open? The fact that the application quits after entering the password incorrectly several times? The wording has already been adjusted, right?

**Comment by igor2x** [comment]
@rafaelx, left open: Linux three times incorrect password and Password Safe exists (on Windows, Password Safe does not exit after three times incorrect password attempt). There should be consistent behaviour.

TODO:
1. On Linux remove "exit" after three times incorrect password.
2. Change dialog wording after three times incorrect password (see my first post in this issue).
