### ISSUE TITLE
Yes/No buttons: Create new database 

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1120]
One additional Yes/No. Create new database and type in simple password and bellow dialog appears:

![image](https://github.com/pwsafe/pwsafe/assets/10895030/6ed1be6e-d4c5-4757-8f71-ca0cb5018c60)

1. Yes/No suggestion:
- change **No** with **Cancel** button
- change **Yes**  with **Use anyway** button

2. Different terminologies
- when new database is selected to be created there is "Safe Combination" terminology
- in dialog above there are two terminologies: "passphrase" and "Password"
I suggest to use only one terminology consistently to simplify wording.

**Comment by igor2x** [comment]
Exactly the same problem is selecting Manage | Change Safe Combination and selecting new weak password.

Dialogs are exactly the same.

**Comment by rafaelx** [comment]
Resolved by #1131
