### ISSUE TITLE
Cancel button Save changes dialog closes down Password Safe instead of cancels the action

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1132]
Password Safe v1.18.2 installed as flatpak on Ubuntu 23.10.

1. Manage | Options | Backups tab | make sure option "Save database immediately after any change" is unchecked.
2. Right click on entry or folder and delete it and when asked confirm delete action.
3. Click on "Close" button from toolbar.
4. Dialog appears with three buttons:
- No - if selected, database is closed down and changes are discarded. Works as expected.
- Cancel - PROBLEM. I expect this option would close down the dialog and do nothing. But two weird things happen. First the same dialog reappears (first problem), click on Cancel again and whole Password Safe is closed down (second problem). Positive is when I reopen the database data are not lost.
- Yes - if selected, database is closed down and changes are saved to database. Works as expected.

**Comment by igor2x** [comment]
Interesting if in step 2 click on "New" button the same dialog appears in step 4, but Cancel button works as expected, dialog is closed down without any change to existing database.

**Comment by ronys** [comment]
Fixed in 50815abc5
