### ISSUE TITLE
Merge dialog - Report dialog - change Finish button with Close button

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1136]
File | Merge - Report dialog.
![image](https://github.com/pwsafe/pwsafe/assets/10895030/42241d66-9775-4136-94df-640837746bcb)
I love description of first two buttons, but the last one **Finish** is not the best. Finish is used when there are several wizard dialogs with Next buttons and then finally user gets to Finish that confirms some drastic change will happen or user has gotten to the end of wizard. I think in this case it would be better to use **Close** button, because nothing special is performed, just dialog is closed down.

**Comment by rafaelx** [comment]
I agree, nothing special is done in the button event handler. Only the dialog is closed. The event handler itself is called OnClose and the button ID is wxID_CLOSE. “Close” would be appropriate here.
