### ISSUE TITLE
Unable to change Master Password is database is empty

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1140]
Password Safe v1.18.2 flatpak version on Ubuntu 23.10.

1. Start Password Safe and create new database.
2. Assign master password.
3. Now empty window is displayed as expected, because I have no group or entry yet.
4. Click on menu Manage and "Change Safe Combination" is greyed out. PROBLEM. I expect I can change a master password.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/d55f1c42-7a28-4316-91dc-1646e470e489)

If I add some group or entry then Manage | Change Safe Combination is normally selectable.

**Comment by ronys** [comment]
Fixed in commit d735e565a
