### ISSUE TITLE
UI: Password Safe icon on Windows looks inconsistent

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1143]
Password Safe 3.65.1on Windows 10. There is inconsistent icon. There are actually two icons.

This looks like nagging tiny problem, but it is highly important from branding point of view. Icon is starting point of program usage (double click to start a program).

In my humble opinion, there should be only one icon and icon looks great on Linux and on Windows on Master Password Entry dialog (the big icon).

Bellow print-screens of icons:

![image](https://github.com/pwsafe/pwsafe/assets/10895030/7302694e-b605-4d22-9c19-576c65832575)

**Comment by ronys** [comment]
NSIS icon is now correct size & color. d7715bad9
