### ISSUE TITLE
Web site Password Safe icon is not consistent

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1144]
This is similar problem then https://github.com/pwsafe/pwsafe/issues/1143, but I am reporting new issue, because this is not inside a program itself, but on web page.

Also first picture on top looks like it doesn't scale well. I like to read web pages in 150% to 200% the size of web page - in Firefox CTRL and key "+" to zoom.

It is just small tiny improvements, but idea is we make 1000 tiny improvements, that count for one huge improvement.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/0b7f3917-d0a7-488c-b57d-800134648604)

**Comment by igor2x** [comment]
By the way, if we are talking about branding then every text on web page should be 128,0,0 color.

Also reducing the number of red color shades improves professional look of web page.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/d727a182-0164-4491-b8c4-d3cb8e3644b1)

**Comment by ronys** [comment]
Fixed - thanks!

**Comment by igor2x** [comment]
Can you please update menu color as well to 128,0,0 color.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/3af1341b-b1e5-491b-97df-1301489fe0ee)

**Comment by ronys** [comment]
Done - thanks again!
