### ISSUE TITLE
New Entry and History fieds are editable 

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1147]
Password Safe v1.18.2 flatpak on Ubuntu 23.10.

1. Right mouse and Add Entry.
2. Type in something in Title, Password and Confirm fields.
3. Click on Additional tab.
4. Click inside table Set Date/Time or/and Password. Table fields are editable. I can type in any text. I think this fields should not be editable (problem). I expect tablet to be only read-only (like on Windows).

**Comment by ronys** [comment]
Fixed in commit bd0625489
