### ISSUE TITLE
Show button to display password shrinks Password field

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1148]
Password Safe v1.18.2 flatpak on Ubuntu 23.10.

1. Right click and Add Entry.
2. Click on Show button and Password field for some reason shrinks (problem). I expect the size of Password field to stay the same before and after click on Show button.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/a18b7831-2480-4801-8ecc-cb1a6e9ca634)

**Comment by rafaelx** [comment]
To change style properties of a wxTextCtrl function AddEditPropSheetDlg::UpdatePasswordTextCtrl is used to replace an existing control with a new one with the desired style flags. The reason for this could be the style flags wxTE_PASSWORD and wxTE_READONLY. According to the wxWidgets documentation (see [Styles section](https://docs.wxwidgets.org/stable/classwx_text_ctrl.html)), these properties can be changed at runtime in wxGtk builds, but not in wxMSW builds.

If a wxTextCtrl is replaced at runtime by AddEditPropSheetDlg::UpdatePasswordTextCtrl, it will be displayed in the wrong size. It is observed that when the user resizes the affected dialog, the layout and size of all controls are recalculated, thereby fixing the size of the control.
Unfortunately, a call to Layout() or SendSizeEvent() doesn't fix the problem.

In wxGtk builds, a wxTextCtrl does not need to be replaced with a new instance. Changing the style flags via SetWindowStyle should be enough.
For wxMSW builds, the style flags can also be changed, but based on Win32 mechanisms via SendMessage (EM_SETPASSWORDCHAR; EM_SETREADONLY).

**Comment by rafaelx** [comment]
What should be considered by a fix is the usage of function ShowHideText from wxUtilities which is used by YubiCfgDlg. The implementation of ShowHideText appears to be redundant to that of AddEditPropSheetDlg::UpdatePasswordTextCtrl.
The implementation of general wx functions should be in wxUtilities.

**Comment by nobugshere** [comment]
Just a data point, I am not able to reproduce this problem at all.  I've test with:
- macOS 14.4 local build with wxWidgets 3.2.4
- Fedora 39 ARM local build with wx 3.0.5 or 3.2.4
- Fedora 39 ARM with the current Flatpak version.

**Comment by rafaelx** [comment]
Here is what I have tested so far.

- Fedora 36 / Wayland / wx 3.1.5 -> Not reproducable
- openSuse / X-Server / wx 3.2.1 -> Not reproducable
- Manjaro / X-Server / wx 3.2.2 -> Reproducable
- Kubuntu / X-Server / wx 3.2.2 -> Reproducable

**Comment by nobugshere** [comment]
@igor2x ,
Is it possible your screenshots were taken from the original Flatpak build that used wxWidgets 3.2.2.1?  If so, could you, please, retest with the current build?  (I believe it is using 3.2.4.)

**Comment by igor2x** [comment]
@nobugshere, on Ubuntu 23.10 I have retested:
- Password Safe v1.8.2 on flatpak (it uses wxWidgets v3.2.4): WORKS FINE
- Password Safe v1.9-pre self-build from master repository (it uses xWidgets v3.2.2 - from Help | About): PROBLEM

Probably I have been playing around with pwsafe/master vs. pwsafe/flatpak and somehow mistyped the version I was using at that time.

By the way, flatpak wxWidgets version can bee seen from [flatpak manifest file:](https://github.com/flathub/org.pwsafe.pwsafe/blob/master/org.pwsafe.pwsafe.yml)
`  - name: wxwidgets`
    (few of the rows in between)
`        tag: v3.2.4`
