### ISSUE TITLE
Password Expirity is not remembered

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1149]
Password Safe v1.18.2 flatpak on Ubuntu 23.10.

1. Right mouse and Add Entry.
2. Fill in Title, Password and Confirm.
3. Click on Dates and Time tab.
4. Click at "In" option and leave 90 days and click checkbox Recurring.
5. Click OK button to save the entry.
6. Right click on entry.
7. Click on Date and Time tab. Problem appears Password Expiry is set to Never. Because in step 4 I have set "In" option, I expect "In" to be set.

**Comment by nobugshere** [comment]
This looks like an example of the problem mentioned in the [Feb 22 post of issue #935](https://github.com/pwsafe/pwsafe/issues/935#issuecomment-1440572485). It affects all the WX builds.  I guess it never made it back to the top of the todo list :-)

**Comment by igor2x** [comment]
I have now self-compiled the deb file from master repository and did the test.
The problem is exactly the same on Linux/deb version.

@ronys, can you please remove flatpak label, because this is not flatpak specific problem, but Linux problem at least.
