### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by gregdavisd** [pwsafe/pwsafe#1155]
- On android version it has case sensitive sorting. I'm not fussy with the capitalization of the first letter so I have to look through the capital letters then again through the lowercase beginning letters. This is fixed on Windows but not on Android.
- Different options for AutoType. On Windows it has one option to perform the autotype script. But with "remember my username" on most websites sometimes I need to type the full username/password and other times just the password. Have a "perform autotype password only" function.
- When creating a new entry the "username" field should have a drop down of previously used usernames. It has an option for a single default. But I find myself having to type one of the same sets of emails every time.
- Bip-39 passphrase generation. And possibly a smart autotype, e.g. first word *tab* second word *tab* etc...
- Integrate a 2fa generator private key store, like Authenticator apps.
- On desktop be able to hit a hot key and have a "type username", "type password" panel just like the Android keyboard feature. I want to minimize using copy/paste as the clipboard is notoriously insecure. PWSafe already has an onscreen keyboard but I can only get it to work for typing into PWSafe itself.

**Comment by igor2x** [comment]
@gregdavisd, that you for feature request feedback.

For second and forth point:
1. Right mouse click on entry.
2. Click on Additional tab.
3. In Autotype section there is Autotype input box.
4. Type in what you actually want for individual entry in syntax form:
   \u\t\p\n
   \u = username
   \t = Tab key
   \p = password
   \n = Enter key
   
   If you only need to type in password, then:
   \p\n

**Comment by igor2x** [comment]
@gregdavisd, can you please for each of feature request open new Issue, to follow one feature request or one issue per bug report. It is easier for developers to follow and create create new features if they are properly divided into single request.

Please also name the issues: Feature request: and-the-tile-of-new-feature request

After you open each of new request, please delete this current request to clean up.
