### ISSUE TITLE
Feature request: New entry and mouse cursor shoud be pointed to Title filed directly

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1158]
Password Safe self-build from master repository on Linux.

1. Add new group and right click Add Entry. Problem appears. Cursor is positioned at Group input box. This is confusing specially for new user. User may ask, why do I need to type anything in to Group field when I am entering new entry? And if Group field is change the entry will not appear where user right clicked on group before (additional confusion).

My suggestion. Position mouse cursor directly into Title field.

**Comment by ronys** [comment]
Fixed in #1161
