### ISSUE TITLE
Feature request: Simplify new entry dialog

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1159]
1. Currently Add Entry dialog looks to me little bit too complicated, specially for average Joe and Jane (non-geek).
   If we look at current design of labels:

   Current words are application developer internal workings labels:
   - group
   - entry

   But from end-user, user wants to save:
   - "usernames" and organize them into
   - "folders"

---

2. Users are used on "New" terminology instead of "Add". Add is term from application developer internal workings, because we add new entry to the hierarchy tree. But user wants to create "new" username, "new" password... In file manager, right click and you get "New Folder". I suggest to replace all "Add" with "New".

---

3. The order of input boxes. When I select "New Username" from right mouse icon, new dialog is opened and I expect to be directly pointed into "New Username" field, so I directly type in username, then password, confirm password, then all others fields are less important like title, group etc.

---
4. Add some grouping of input box, like adding some space between group entries. User needs to pause in thinking what entries are required to enter. In my mind username and password are one thinking step, then title and group is another thinking step and the last one is all other info (that are fully optional).

---

Suggestions:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/5280ef7c-85a1-4987-841c-0a096d1a9c3a)

In my humble opinion Password Safe should all be around simplicity of use.

**Comment by rafaelx** [comment]
Where is the survey, which proves that users expect the term Folder instead of Group in a password manager? ;-)

Certainly, the term Group is interchangeable. It could be replaced by the term Folder but also by the term Category. All these terms have their justification in this context and it is only a matter of determination.

**Comment by igor2x** [comment]
@rafaelx, now seeing your comment and sleeping over few days, I see I have overreacted with this suggestion. I have crossed the line of: "Everything should be made as simple as possible, but not simpler."

I am closing down this suggestion for now.
