### ISSUE TITLE
Feature request: Simplify group appeariance

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1160]
Password Safe self-compiled from master on Linux.

In my humble opinion simplifications:
1.  Rename all wording from "group" to "folder".
2. Change diamond icon with folder icon.
3. Currently there are two icons: a) groups with entries or subfolders, b) groups without entries and subfolders. From end-user perspective I can't see justification for two icons. In file manager there is never distinction between empty folder and folder with files and subfolders. In my humble opinion every icon should have some reasons to TELL user that he or she must be careful, because this is different element. Also on Windows there are aliases that have different color and seeing alias, "empty group", "non-empty group" etc. User expects to have some differences. My suggestion is to remove distinctions between "empty" vs. "non-empty" group.

Suggestion:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/5ca16902-b5d2-463f-b0b8-0decf6a076e3)

**Comment by rafaelx** [comment]
I would say that a file manager doesn't necessarily have to serve as a reference for a password manager, even though the management activities of the elements are very similar. A password manager serves a different purpose and may therefore be different from a file manager.
There is also an advantage for the user in the different icons. Based on the different group icons, the user can quickly see visually which group is empty and which group contains elements when the groups are collapsed.

**Comment by igor2x** [comment]
@rafaelx, now seeing your comment and sleeping over few days, I see I have overreacted with this suggestion. I have crossed the line of: "Everything should be made as simple as possible, but not simpler."

I am closing down this suggestion for now.
