### ISSUE TITLE
Window size/placement not restored on starting.

### ISSUE THREAD

**Issue by Bruce-95** [pwsafe/pwsafe#1190]
Running Windows 10 Pro 22H2 19045.4170 with display of resolution 1920x1080 and 125% scale.

Migrated from PwSafe64 v64.1 to v65.1.  Moved and resized PwSafe window to position of choice. Exited PwSafe. Restarted PwSafe and the window size and position are different from what it was when last exited. (Window is larger and moved halfway off right edge of screen.)

Installed and ran v65.0. Problem still exists.
Reinstalled v64.1 and no problems - window restores to last position and size. 

This is unfortunate as I wanted to take advantage of the new authentication token feature in v65.0. Please fix. Thank you.

**Comment by Bruce-95** [comment]
Possibly related to #1092?

**Comment by ronys** [comment]
Sounds like the same problem that was fixed in #1092.

Can you try 3.65.1 with your display set to both 100% and 125%?

**Comment by Bruce-95** [comment]
Well this is strange. I reinstalled v3.65.1 and was going to capture before and after pics of the problem but the main window is now displaying in the location/size as it was when the app was last closed.  Hmmm - working as designed. You can close this ticket. Sorry to bother.

P.S. I'm a years-long user (over 20) of PwSafe. Just want to say thank you very much for maintaining and enhancing the app.

**Comment by ronys** [comment]
Closed.
Thanks for your kind words.
