### ISSUE TITLE
File | Compare - suggestion to rename Finish button with Close

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1206]
Password Safe v3.65.1 on Windows 10.

1. File | Compare.
2. Check bot for advanced settings.
3. Click through dialogs and the last one looks like:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/d1643ab2-ff13-404b-b637-9c3a806a4ebc)

PROBLEMS
a) "Finish" button indicates there is going to happen some drastic change after e.g. wizard ends, but in this case dialog is just closed down. I suggest to rename "Finish" button to "Close".
b) Is there really a need for greyed out "Abort" button? I think it is not, so removing "Abort" button to simplify dialogs.

**Comment by ronys** [comment]
Re the "Abort" button: For large databases (hundreds of entries), compare/merge/sync operations can take a long time. During this time, the Abort button is active. At the end of the operation, there's no sense in aborting, so the button is deactivated. To me it's more consistent to disable a button then to show/hide it.
For Sync and Merge, "Finish" reminds the user that the changes are indeed committed. For Compare, this can indeed be changed to Close.

**Comment by ronys** [comment]
Actually, it's possible to edit entries from the compare results window, so I think leaving this as "Finish" makes more sense for Compare as well.
