### ISSUE TITLE
Fedora 24: some issues

### ISSUE THREAD

**Issue by sguazt** [pwsafe/pwsafe#122]
Hello,
Just installed Fedora 24 x86_64.
I'm facing some issues with 0.98.1BETA.

- If I install the RPM provided by this site (pwsafe-0.98.1BETA.x86_64.rpm), I get the following message:

```
10:20:53 PM: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1010,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8).
Could not initialize help subsystem.
```

the program will start but:
   1. it doesn't remember the history (every time I run it, it starts with an empty history)
   2. it doesn't install an entry in the system menu
   3. the UI is weird (instead of a window with white background I see a window with a grey background); but maybe this is the new look&feel of WxGTK3...?

- If I try to create my own RPM (I've used the spec file in the install/rpm directory), install it and run, I get the following message:

```
/usr/include/wx-3.0/wx/strvararg.h(456): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type
pwsafe:[14682]: PWSprefs - using existing config file: /home/sguazt//.pwsafe/pwsafe.cfg [R/W]
Segmentation fault (core dumped)
```

and the program won't start

Any idea?

Thank you very much!

Marco

**Comment by sguazt** [comment]
The new release (v.0.99) fixes most of the above issues.
Still we have:
* no application menu entry (I use XFCE desktop manager)


A possible fix is to copy file:
```
/usr/share/pwsafe/pwsafe.desktop
```
to
```
/usr/share/applications/pwsafe.desktop
```
and change the `Icon` property from:
```
Icon=pwsafe
```
to
```
Icon=/usr/share/pwsafe/pwsafe.png
```

This works for me.

**Comment by ronys** [comment]
Thanks. Care to create a pull request?

**Comment by sguazt** [comment]
OK. I'll work on it ASAP.

Cheers

**Comment by sguazt** [comment]
Just a question.
For creating the RPMs (the ones available in the GitHub "releases" page), are you using the `install/rpm/pwsafe.spec.tmpl`?
I'm asking this because this file seems OK (or at least seems to install the files in the right place):

```
install -d -m 755 ${RPM_BUILD_ROOT}/usr/share/applications
install -d -m 755 ${RPM_BUILD_ROOT}/usr/share/icons/hicolor/48x48/apps
...
install -m 644 ${RPM_BUILD_DIR}/%{name}-%{version}/install/desktop/fedora-pwsafe.desktop ${RPM_BUILD_ROOT}/usr/share/applications
install -m 644 ${RPM_BUILD_DIR}/%{name}-%{version}/install/graphics/pwsafe.png ${RPM_BUILD_ROOT}/usr/share/icons/hicolor/48x48/apps
...
```

but looks different from the result found in the RPMs.
For instance, try to download [passwordsafe-fedora24-0.99.0-BETA.x86_64.rpml](https://github.com/pwsafe/pwsafe/releases/download/0.99BETA/passwordsafe-fedora24-0.99.0-BETA.x86_64.rpml), and run this command:

```
rpm -qpl passwordsafe-fedora24-0.99.0-BETA.x86_64.rpml
```

You get this:

```
...
/usr/share/pwsafe/pwsafe.desktop
/usr/share/pwsafe/pwsafe.png
...
```

Best,

Marco

**Comment by ronys** [comment]
We're in the process of switching from a custom-built Makefile to cmake. The 0.99 rpm was built by running 'cpack -G RPM' using the toplevel CMakeLists.txt for input. That should have all the config details for packaging.

**Comment by sguazt** [comment]
Thanks.
I've found the way to change the destination path of desktop and icon files.
But before making any changes I've just tried to build the RPM of my own by running the CPack command: `cpack -G RPM`.
RPM creation is OK:

```
$ cpack -G RPM
CPack: Create package using RPM
CPack: Install projects
CPack: - Run preinstall target for: passwordsafe
CPack: - Install project: passwordsafe
CPack: Create package
CPackRPM: Will use GENERATED spec file: /home/sguazt/Projects/src/pwsafe/build/_CPack_Packages/Linux/RPM/SPECS/passwordsafe.spec
CPack: - package: /home/sguazt/Projects/src/pwsafe/build/passwordsafe-0.99.0-BETA-Linux.rpm generated.
```
but unfortunately it fails to install:
```
$ sudo dnf install ./passwordsafe-0.99.0-BETA-Linux.rpm
...
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction check error:
  file /usr/share/man from install of passwordsafe-0.99.0_BETA-1.x86_64 conflicts with file from package filesystem-3.2-37.fc24.x86_64
  file /usr/share/man/man1 from install of passwordsafe-0.99.0_BETA-1.x86_64 conflicts with file from package filesystem-3.2-37.fc24.x86_64
```

So my question is: after running `cpack -G RPM`, should I run some other commands?

Cheers,

Marco

**Comment by ronys** [comment]
Uh, no. First time I've seen this conflict. Looks like the PasswordSafe rpm is specifying the directories /usr/share/man and /usr/share/man/man1 as part of the package content, which ti really shouldn't.

**Comment by sguazt** [comment]
Yes, that's the same feeling I had.
Indeed, this is a well-known issue: http://public.kitware.com/Bug/view.php?id=13609

I've tried to fix these and it seems to work.
I'm creating a pull request.

Best,

Marco

**Comment by ronys** [comment]
Excellent! I've accepted the pull request. Many thanks for your help.
