### ISSUE TITLE
Recurring option is selectable when parent option is not selected

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1220]
Password Safe v1.19-pre master branch on Ubuntu 23.10

1. Click on entry and right click menu Edit Entry.
2. Dates and Times tab.
3. In Password Expiry, click on On or Never selection.
4. Now in row which starts with "In" click on checkbox Recurring. If "On" or "Never" is selected then Recurring checkbox should be greyed out.

**Comment by nobugshere** [comment]
It turns out the code is there to enable and disable the controls depending on the selected radio button.  But, it just doesn't work.  I suspect it's a problem in wxWidgets when the controls are contained within a panel.

**Comment by nobugshere** [comment]
Hi @igor2x,
I think this has been resolved by PR #1353

**Comment by igor2x** [comment]
I forgot to test this on v1.19.x, but I have now tested on v1.20 and this is fixed.
Thanks for fixing it.
