### ISSUE TITLE
File | Properties if password is saved to root level it is counted as empty group

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1233]
This is not super important issue, just small inconsistency.

Password Safe v1.19-pre from master branch on Ubuntu 23.10.

1. I created test database with some entries and then File | Properties.
![image](https://github.com/pwsafe/pwsafe/assets/10895030/6b79681f-4fd6-40d3-8db9-45cb92799dce)

What does: **1 (1 empty)** means? I have no empty groups.

2. If I add another group and "empty" gets increased by 1.
![image](https://github.com/pwsafe/pwsafe/assets/10895030/f1165439-2610-40ff-b133-ca1e91dca84b)

3. If I add an entry to empty group. I still have 2 empty groups.
![image](https://github.com/pwsafe/pwsafe/assets/10895030/9fce509b-056d-47f4-93c1-8ee338736eb6)

Suggestion:
1. Fix proper counting of empty groups.
2. Remove this "empty groups" information. I don't know if this is really relevant.

**Comment by igor2x** [comment]
I did some additional tests staring with empty database.

1. Empty database. Empty counting is correct.
![image](https://github.com/pwsafe/pwsafe/assets/10895030/c4142105-8f59-4dd0-8c58-2c80e02061de)
2. Add new group. Empty group increases by 1, correct.
![image](https://github.com/pwsafe/pwsafe/assets/10895030/c84d5b4f-aa10-45ef-87ff-db49c0e06a6f)
3. Add new entry. Problem appears. Empty group should now decrease by one, I expect to be 0.
![image](https://github.com/pwsafe/pwsafe/assets/10895030/bb1906e7-6922-455b-9be1-15ff43713988)

**Comment by rafaelx** [comment]
Related to #1142
