### ISSUE TITLE
No longer able to build - cmake error

### ISSUE THREAD

**Issue by dsg18096** [pwsafe/pwsafe#1239]
It's been a while since I've built a new RPM (I'm on Fedora 39) so today I went into my source clone directory, git pull and attempted to redo the build process but am getting the following error:

etecting CXX compiler ABI info
CMake Error:
  The detected version of Ninja (GNU Make 4.4.1

  Built for x86_64-redhat-linux-gnu

  Copyright (C) 1988-2023 Free Software Foundation, Inc.

  License GPLv3+: GNU GPL version 3 or later
  <https://gnu.org/licenses/gpl.html>

  This is free software: you are free to change and redistribute it.

  There is NO WARRANTY, to the extent permitted by law.) is less than the
  version of Ninja required by CMake (1.3).

CMake Error at /usr/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)
  CMakeLists.txt:3 (project)

Configuring incomplete, errors occurred!

I ran the environment script ages ago so everything is (should be?) installed.  in cmake-gui I see that the c and c++ compilers are set properly.

Just in case, I wiped my source directory and redid the clone.  Same thing happened, so it's not some weird turd left over from my last build.

What am I missing?

Thanks

**Comment by ronys** [comment]
Added ninja to setup-linux-dev.sh for all supported distros in 723303a00
