### ISSUE TITLE
Main Password Safe dialog can get resizes to minimal dialog too much to hide buttons

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1245]
I have [installed](https://github.com/pwsafe/pwsafe/actions/runs/8950267357) Password Safe latest version from [rafaelx's PR 1244 ](https://github.com/pwsafe/pwsafe/pull/1244)on Ubuntu 24.04.

I see dialog is improved a lot. The only issue is that dialog can get resized above minimal. In my humble opinion dialog should not get resized so much that buttons are hidden.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/4091c38f-ed51-429f-acab-e3910cc526d2)

P.S. I have tested several Password Safe versions including latest master and all have this issue, that is why I am reporting  new issue instead of commenting in any existing PR.

**Comment by rafaelx** [comment]
Should be fixed by #1232.

I'm surprised that the "Browse" and "New" button are so wide in the screenshots. In my case, the buttons look smaller, as shown in https://github.com/pwsafe/pwsafe/issues/1241#issuecomment-2091831307

**Comment by rafaelx** [comment]
This should be fixed by #1309. Can you confirm this?

**Comment by igor2x** [comment]
Tested: Password Safe v1.19.1 flatpak. Dialog can't be resized too much to hide dialogs. Fixed. Thanks.
