### ISSUE TITLE
Redudant line in Change Master Password dialog

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1246]
Password Safe from latest master on Ubuntu 24.04.

I see bellow dialog is something special comparing with other dialogs. It contains horizontal line. I think this line should be removed, because it does not separates anything.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/3558a1b2-c891-4dfa-98f1-307ab6ddae38)

Horizontal line and buttons under them is used when there is GUI with multiple tabs and line indicates that buttons bellow will effect all of the changes in tabs.

I think this line should be removed, to follow simplicity rule.

**Comment by rafaelx** [comment]
I will create a separate PR with the changes that result in the dialog as shown in https://github.com/pwsafe/pwsafe/issues/1226#issuecomment-2068186960

**Comment by rafaelx** [comment]
Fixed by #1299
