### ISSUE TITLE
Unlock dialog can be resized too much to hide buttons

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1247]
Password Safe from master branch on Ubuntu 24.04.

Similar to [issue 1245](https://github.com/pwsafe/pwsafe/issues/1245) Unlock database dialog can be resized too much so that buttons are hidden.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/1d0c5fb5-64cc-4267-bb70-8e9051f6cfaa)

P.S. Why is so much vertical empty space between Master Password input box and Cancel button? Is it some kind of placeholder for Yubikey? If yes, then it is OK, if not, then probably would be nice to reduce the spacing.

**Comment by nobugshere** [comment]
Hi @igor2x ,
Is this the way the window appeared on its own, or are you saying that manual resizing allowed the buttons to be hidden?

Just a data point, I cannot resize the dialog box smaller than its original size.
Fedora 39 ARM, wx 3.2.4, GTK 3.24.41, Xfce

**Comment by igor2x** [comment]
This: manual resizing allowed the buttons to be hidden.

**Comment by rafaelx** [comment]
This should be fixed by #1309. Can you confirm this?

**Comment by igor2x** [comment]
Tested: Password Safe v1.19.1 flatpak. Works fine. Dialog can't be resized too much to hide buttons. Fixed. Thanks.
