### ISSUE TITLE
Show stoppers bugs list for Password Safe stable release v1.19 on Linux/maxOS

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1253]
New Password Safe stable release for Linux/macOS is approaching. I did some tests today on latest commit from master branch and I have compiled the show stopper bugs that in my humble opinion must be fixed before new stable release. 

Show stopper bugs:
1. Double Show Master Password text and icon in File | Merge - [issue 1249](https://github.com/pwsafe/pwsafe/issues/1249)
2. Double Show Master Password text and icon in File | Compare - [issue 1250](https://github.com/pwsafe/pwsafe/issues/1250) 
3. Double Show Master Password text and icon in Manage | Change Master Password - [issue 1251](https://github.com/pwsafe/pwsafe/issues/1251)
4. Double Show Master Password text and icon in main dialog - [issue 1252](https://github.com/pwsafe/pwsafe/issues/1252)

@dskrvk, @nobugshere, @rafaelx and @ronys, can you please add your view of the show stopper bugs for new Linux/MacOS release.

@ronys, please do not forget to update translation files, that translators can start translating new version as soon as possible.

**Comment by rafaelx** [comment]
The biggest showstopper in my opinion is pull request #1232 "Fix layout issue when showing Yubi controls dynamically".
It blocks the finalization of #1244 "Modernization of the password entry dialog" and #1226 "Modernization of Change Password Dialog".
Since I cannot reproduce the problem described by ronys without a YubiKey, I am unable to provide a solution for this. :-/

**Comment by ronys** [comment]
src/ui/wxWidgets .pot and .po files updated

**Comment by nobugshere** [comment]
I created a branch, in my own repo, based on master with PR #1232 and #1244 merged-in.  So far, it seems to work well on macOS, also fixing issue #1230.  I'll test it on Fedora later.

If anyone else wants to try it, it's here: [Merged-PR-1232-1244](https://github.com/nobugshere/pwsafe/tree/Merged-PR-1232-1244)

**Comment by nobugshere** [comment]
I tested my merged branch on Fedora and the only anomaly I encountered turned out not to be a new problem, so I documented it as issue #1255.
Tested on: Fedora 39 ARM, Xfce, gcc 13.2.1, wx 3.2.4, GTK 3.24.41

**Comment by igor2x** [comment]
In my humble opinion specially annoying issue (problem already exists in Password Safe v1.18.2):
- Rename entry and Rename Group not working properly - [issue 1171](https://github.com/pwsafe/pwsafe/issues/1171)

**Comment by rafaelx** [comment]
I think we can close this 'show stoppers bug list' since the Password Safe 1.19 show has already started.

**Comment by igor2x** [comment]
I have checked all of the issues and I see they are all closed down.
