### ISSUE TITLE
Google Sync fail after time

### ISSUE THREAD

**Issue by Jomme5** [pwsafe/pwsafe#1261]
Android app fails to connect to Google drive. App says: "no files". The right account was selected, the app can't suddenly find the file on the G-drive. Log in app says: "Remove local file ..." Luckily it still on G-drive
There is no possibility to set the path in the app pointing to the google drive file.
Why isn't there a possibility to alter the file path, like you open a file?

**Comment by ronys** [comment]
Sorry, the Android app is developed and maintained by a separate team. You can contact them via https://sourceforge.net/p/passwdsafe/discussion/1067588/
