### ISSUE TITLE
Not a bug - linux build request

### ISSUE THREAD

**Issue by bendover22** [pwsafe/pwsafe#1268]
Could you add an AMD64_1.18.2  build for Mint 20.1 / Ubuntu 20.04?
There's already an ARM64 Ubuntu 20-1 vers uploaded on SF [passwordsafe-ubuntu20-1.18.2-arm64.deb].

Not sure it'd work under Mint 20.1, in addition to the arm64 version requiring adding arm64 foreign architecture (on an amd64 system), before deb installer would run.
Thanks.

**Comment by ronys** [comment]
Done for Ubuntu 20: https://github.com/pwsafe/pwsafe/releases/download/1.18.2/passwordsafe-ubuntu20-1.18.2-amd64.deb

**Comment by bendover22** [comment]
Thanks.
Curious, but is the link also found on a real page on Github - accessible by browser, to view other files?  (don't find it) 
No such page as https://github.com/pwsafe/pwsafe/releases/download/1.18.2/
or https://github.com/pwsafe/pwsafe/releases/download/

Also, the direct link gives no way to D/L a detached Sig file, other than adding ".sig" to end of the link (which worked).
This new build or sig file isn't loaded on SF - yet, so folks won't see it there.

**Comment by ronys** [comment]
Thanks for reminding me about SF - added the artifacts there as well.

What you're looking for is https://github.com/pwsafe/pwsafe/releases/tag/1.18.2
