### ISSUE TITLE
Virtual Keyboard in Master Password entry

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1280]
I have downloaded latest 1.19-prerelease on Ubuntu 22.04 and tested it according to the [PR 1278](https://github.com/pwsafe/pwsafe/pull/1278) and it looks like this:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/5c181aac-ee33-4768-957b-52c1da492614)

Everything works fine, just Virtual Keyboard icon (blue icon on bottom right) does not work, it produces the error:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/ff9d5af8-5d88-48d7-aa6a-093eae339525)

The error message indicates that xvkbd program is not installed which can be a cause of the problem, but in my case I am using Wayland (X-Server does not work on my laptop at all, just black screen and freeze after Ubuntu login) and xvkbd is X11 application and probably does not work at all on Wayland.

OPTIONS:
1. I don't know how useful Virtual Keyboard is, it protects against keyboard loggers, but if someone has compromised your computer with keyboard logger, then he or she can probably compromise your computer in other way to get master password like recording the screen. One option is to fully remove this feature from Password Safe.
2. Recognize if user is using X then display Virtual Keyboard and if not (like Wayland) then do not display this icon. If we look at the same logic if using Yubikey, which is displayed only if user has support for it, then Virtual Keyboard should be displayed only if user can use it.
3. At least change error message to indicate that if user is using Wayland (and you can probably check this) then Virtual Keyboard is not going to work.

NOTE: This issue is not restricted to his dialog alone, it appears whenever some dialog asks for Master Password entry.

**Comment by rafaelx** [comment]
The display manager could be determined using the environment variable XDG_SESSION_TYPE.
It would also be interesting to know whether the virtual keyboard can also be started on a Mac and whether this environment variable exists.

@nobugshere Could you please try reading the environment variable in a console?

```
echo $XDG_SESSION_TYPE
```

**Comment by nobugshere** [comment]
I never figured out how to launch the Mac virtual keyboard directly; the best I could do was to launch the Settings app to the right page and prompt the user to enable it.  There are no XDG_* environment variables on the Mac.  

However, my recent builds from master no longer have the keyboard button!  (Mac or Linux)  Has it already been removed?


In case it helps, this is what I have on Fedora 39 and 40:
```
XDG_CONFIG_DIRS=/etc/xdg
XDG_MENU_PREFIX=xfce-
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=xfce
XDG_SESSION_TYPE=x11
XDG_CURRENT_DESKTOP=XFCE
XDG_SESSION_CLASS=user
XDG_VTNR=2
XDG_SESSION_ID=2
XDG_RUNTIME_DIR=/run/user/1000
XDG_DATA_DIRS=$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/usr/share
```

**Comment by igor2x** [comment]
**EDIT:** It looks like I have posted bellow post in the wrong issue. I have now copied it here where it belongs and deleted from "mistaken" issue.

I did some dialog comparison. On left Password Safe v1.18.2 on right v1.19-pre from latest master:

![image](https://github.com/pwsafe/pwsafe/assets/10895030/82decdc9-28cc-4a20-8f15-5e6482024270)


And now to the dialog from first post and it looks like Virtual Keyboard icon has appeared in v1.19-pre (right) that was not there in v1.18.2 (left).
![image](https://github.com/pwsafe/pwsafe/assets/10895030/4294ed1d-94cc-4afd-870e-06782d83bc7c)

**Comment by rafaelx** [comment]
The button for the virtual keyboard should now appear in all dialogs that ask for a password. The dialogs have been standardized in this regard. This means that the user always has the option of starting the keyboard if they have not already done so.
