### ISSUE TITLE
pwsafe.org/latest.xml is out of sync to current release

### ISSUE THREAD

**Issue by tkvance** [pwsafe/pwsafe#1281]
On a whim, I looked to see if there was a newer version available via "About Password Safe". As shown, the latest version is 1.19 (0), but this appears to have not been released yet.
![Screenshot_20240528_164608](https://github.com/pwsafe/pwsafe/assets/42975939/be890ca7-1e67-4e14-96f8-ce34455b6d65)

It seems that https://pwsafe.org/latest.xml shows  v1.19
![Screenshot_20240528_170825](https://github.com/pwsafe/pwsafe/assets/42975939/68724e9d-f57f-40d5-a7e5-bdf5bf87776f)

**Comment by igor2x** [comment]
@tkvance, I think this issue is not relevant anymore, because v1.19.1 is released. Can you close down this issue please?

**Comment by tkvance** [comment]
@igor2x, I would happily close this, but I feel there is still some relevance.

When I check for a new version with v1.19.0 it says that the software is the latest release. So, the software is working exactly as designed. It retrieves the latest.xml file and compares it to the version that is running, they match, "This is the latest release!"

The latest version is v1.19.1.  Therefore the latest.xml file is currently out of date and we know that the software is not the latest release.

It seems that the latest.xml file is updated manually, but this is simply a wild guess on my part. 

![image](https://github.com/user-attachments/assets/537844b0-b746-495e-9324-be3acc7c749a)

**Comment by ronys** [comment]
Yes, latest.xml is updated semi-automatically.

Fixed - thanks!
