### ISSUE TITLE
Ever since pwsafe 3.63.0 x64, autotype cannot parse backslashes in the username field (\u). Password field (\p) works fine.

### ISSUE THREAD

**Issue by UoCKen** [pwsafe/pwsafe#1282]
Problem exists in every version of pwsafe64 since 3.63.0. I haven't tried the 32-bit version.

This is a problem if you store usernames in DOMAIN\USERNAME format (there is no "domain" field to use in AutoType).

**Comment by UoCKen** [comment]
Using Copy Username works fine as does Copy Password. Just AutoType seems affected.

**Comment by hxu1** [comment]
You mean the `\` character is not autotyped for username? Can you check if the build from #1292 works as expected?

**Comment by ronys** [comment]
Fix verified on Windows and documented in release notes - thanks!
