### ISSUE TITLE
[wx] Create new password database can be resized beyond minimal dialog size

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1288]
I have downloaded latest Password Safe  from master branch and installed on Ubuntu 22.04. Dialog looks like this:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/b0a29be1-53ba-4956-8e1a-33d94431443f)

Dialog can be resized beyond minimal, so buttons gets hidden and interesting last sentence from the text above fields gets also hidden like this:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/adc06bf1-6849-44db-b05f-989270cb66d9)

I retested on v1.18.2/flatpak and dialog can't be resized bellow minimal. This issue is regression in v1.19-pre.

**Comment by rafaelx** [comment]
I can't reproduce this under Ubuntu 23.10 (wx version 3.2.2 ; Wayland) and Kubuntu 24.04 (wx version 3.2.2 ; X11).

**Comment by rafaelx** [comment]
Does this actually affect all password entry dialogs with a row of buttons at the bottom?
Which wxWidgets version is used on Ubuntu 22.04 for the Deb package and the Flatpack version?
(The version is printed on the command line when the application is started from there and the About dialog is called.)

**Comment by igor2x** [comment]
**1. xwWidgets version**
[Flatpak version](https://github.com/flathub/org.pwsafe.pwsafe/blob/master/org.pwsafe.pwsafe.yml) is using xwWidgets v3.2.4.

Help | About:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/63939355-24ac-4b25-9565-109dbd901fec)


**2. Dialogs affected**

Dialogs that can go beyond minimal (problem hiding buttons):
- First dialog where Master Password is entered
- File New dialog
- right click on entry and Delete button

Not affected (works fine)
- right click on entry and Edit
- Manage | Options
- Manage | Change Master Password
