### ISSUE TITLE
missing *-src.tgz archive and gpg signature for 0.99BETA linux release

### ISSUE THREAD

**Issue by namarrgon** [pwsafe/pwsafe#129]
Will these return or was the omission intentional?

**Comment by ronys** [comment]
Github generated the source zip/tar automatically from the git repo. I can
download, verify and sign, but not this week. If you want me to, please
open a ticket.

Rony

**Comment by namarrgon** [comment]
Yes, that would be nice. The source tarball is the primary way of building it for non-deb/rpm distros and the only one without signatures.

**Comment by ronys** [comment]
It was easier for me to generate my own tarball, sign and upload it and the signature.
