### ISSUE TITLE
FR - perform autotype for auth code

### ISSUE THREAD

**Issue by tuotikka** [pwsafe/pwsafe#1301]
Current (version 3.66.1) way to type the generated auth code is to copy it to clipboard and then paste it to right window. Or then just manually typing the number the window that needs the code.

I'd prefer to have separate autotype functionality for _auth code only_ from the context menu. This way there wouldn't be need to copy-paste the number.

The functionality could be implemented as more general one too; One could have multiple autotype sequences defined per password entry. In addition there should then be a separate code for autotype auth code ( `\a` ?). Once user has defined the different sequences they would be shown as entries in an autotype submenu of the context menu. This would make autotyping much more powerful and flexible to use.

**Comment by ronys** [comment]
Autotype for auth code is certainly needed.

As to multiple autotype sequences, I'm not sure. Can you give me a scenario where this would be useful? In any case, this should be a separate FR.

**Comment by tuotikka** [comment]
One scenario would be this separate auth code autotype, so it could be just one separate sequence and there would be no need for separate feature for it :).

Earlier I had a need to just autotype the password as the account was the same, but various websites required the username in different formats. First I typed the username manually and then copied the password using clipboard. Then I learned to use shortcuts to solve the problem as you can change the username in the shortcuts. This works fine, unless some of the websites changes how username and password is entered. Fortunately this has not (yet) happened to me.

Above shortcut solution works just fine as long as all the sites require username and password in the same "form". I.e. one is able to change from username field to password field for example with `tab` key. Lately more and more websites have changed to first ask username and then one has to press `enter` to get the password field. In such a case above shortcut method do not work as the autotype sequence comes from the original entry and shortcut and original entry cases would need different autotype sequence.

Another case where I actually would have needed the feature is when the URL I have got already has embedded the account that is to be used and only the password needs to be entered on the web page. In these cases the only way has been to copy the password to clipboard and then paste it to the browser. If there would be multiple autotype sequences I could make one for both cases; with and without username.

I can create a separate FR over this multiple autotype sequences, no problem.

**Comment by ronys** [comment]
I think that the scenarios you've described is already addressed by setting custom autotype string for a given entry (In the "Additional" tab.
Am I missing something?

**Comment by tuotikka** [comment]
> I think that the scenarios you've described is already addressed by setting custom autotype string for a given entry (In the "Additional" tab. Am I missing something?

You are missing the fact the I need two (or more) separate autotype strings for the same entry. In current implementation I can have only one, either the default or then the custom. For the most cases this is enough, but for example in various corporate intranet services there are different tooling (web services) that ask the credentials in different ways. The credentials themself are the same for all the services. For example:

1. Service A wants a username in form of "username" and a password in the same web form so that one can move to password field with `tab` key.
2. Service B wants a username in form of "username@some-service-specific-thingy" and like above a password in the same web form so that one can go from the username field to the password field with `tab` key.
3. Service C wants a username in form of "email" and provides only username field. A password is asked after user presses `enter`.
4. Service D wants a username in form of "username" but does not provide the password field and one needs to press `enter` to get a password asked.
5. Service E contains the username in the URL that is used to access the service _only_ a passsword is asked.

If we take TOTP in count the possible cases are even more compilicated.

Services A and B above can be handled with the shortcuts so that the service A is the actual entry and it uses the default autotype string. For service B a shortcut can be defined so that it has modified username field. Because the password handling on the services is identical the default autotype string in the original entry works fine for service B too.

One can not though use shortcut to service A entry for service C as the behavior on service C is different (`tab` vs `enter`) when moving from username field to password field. The same is true also for service D, it can not be shortcut to A because of how password entry is handled by the service.

In theory one could create a entry for service C and modify its autotype string accordingly. Then one could make a shortcut to this entry for service D. This is not wanted though as the account behind all the services is the same and when password is to be changed it need to be then changed on multiple entries.

The service E is then totally separate case, where only one part of the entry information is needed.

As a total I would need three separate autotype strings to fulfill the ways the same account information is used in various services:

1. `\u\t\p\n` (the default, for services A and B)
2. `\u\n\p\n` for services C and D
3. `\p\n` for service E

Now it would be excellent if the pwsafe would provide a submenu under the autotype so that I could select which of the above three possible autotype strings I'd like to use once autotyping.

**Comment by tuotikka** [comment]
Here is an example from my database where _Windows_ entry is the "service A" in my earlier comment. _Lablogin_ is "service B" and _VPN_ is "service C".
![Example](https://github.com/pwsafe/pwsafe/assets/25635423/7e1ab963-1b0e-4623-9d94-8845a9a7b11c)

**Comment by ronys** [comment]
I think that the existing  "aliases" feature will address this use case: This allows different entries to share a password.
Look up "Alias" in the online help.

**Comment by tuotikka** [comment]
> I think that the existing "aliases" feature will address this use case: This allows different entries to share a password. Look up "Alias" in the online help.

Oh no! Alias exactly solves the problem I have.

I have used pwsafe years (I guess 10 or so), but how come I never before have heard about the alias feature. Maybe I just haven't understood the feature and passed it as curiosity.

Thanks a lot bringing this feature up!

So this FR is then just autotype for auth code, no need for multiple autotype strings.
