### ISSUE TITLE
How to create shortcuts

### ISSUE THREAD

**Issue by drei97** [pwsafe/pwsafe#1314]
Hi,

how to create shortcuts, i.e pressing a button for copying pw or user name into the clipboard?

I can create items, you call it "Shortcuts", but they seem to be only copies of a base entry which then can be put into another group. That's it.

How to link a button to an action?

The form Shortcuts in menu Options is only an empty table. The help function shows parts of the windows version which are not matching the linux version and therefore are not helpfull.

What I am doing wrong? Or is this functionality not yet implemented?

Greets

Joachim

**Comment by igor2x** [comment]
> how to create shortcuts, i.e pressing a button for copying pw or user name into the clipboard?
Default is pressing **<Shift>+double click** to copy password and **double click** for copying password. The settings are in Manage | Options | Miscellaneous and check for "Double-Click Action" and "Shift-Double-Click Action".

There is also setting for individual entry (if you really need this). Right click on entry and "Edit Entry", then Additional tab and there is "Double-Click Action" and "Shift-Double Click Action".

> I can create items, you call it "Shortcuts", but they seem to be only copies of a base entry which then can be put into another group. That's it.
If you have multiple computers and the same userid/password this can be handy. This are some kind of userid shortcuts.
On Windows there are also aliases, but unfortunately not yet implemented on Linux.

> How to link a button to an action?
Can you elaborate?

> The form Shortcuts in menu Options is only an empty table. The help function shows parts of the windows version which are not matching the linux version and therefore are not helpfull.
I have tried this, but it looks like Manage | Options | Shortcuts are not working or at least I can't figure it out. On Windows 
You can click on individual line and then press keyboard shortcut key. For example for  File | New default is CTRL+N, but you can set it for example to CTRL+X (or anything else) and then this new keyboard shortcut is used.

It looks like this feature is not implemented yet on Linux.

> What I am doing wrong? Or is this functionality not yet implemented?
Majority of features are implemented both on Windows and Linux. But few of them are not yet available on Linux, like shortcuts.

If you have additional question please provide more information:
1. What is your operating system and version?
2. What is your Password Safe version (from Help | About menu).
3. How did you install Password Safe? E.g. from Software application, downloaded deb, from [flatpak](https://flathub.org/apps/org.pwsafe.pwsafe), build from source or something else.

**Comment by drei97** [comment]
>  On Windows there are also aliases, but unfortunately not yet implemented on Linux.

> I have tried this, but it looks like Manage | Options | Shortcuts are not working or at least I can't figure it out. On Windows You can click on individual line and then press keyboard shortcut key. For example for File | New default is CTRL+N, but you can set it for example to CTRL+X (or anything else) and then this new keyboard shortcut is used.
> 
> It looks like this feature is not implemented yet on Linux.

That's also my conclusion for now. 

Thnx for your reply
