### ISSUE TITLE
Change of Dragbar visible is not recognized as a change

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1319]
Password Safe v1.18.2 flatpak on Ubuntu 24.04.
1. Open database in read-write mode.
2. Select _View | Dragbar visible_ and so toolbar is unchecked in menu.
3. Close down Password Safe and reopen it and dragbar is back again. I expect to be gone because of change from step 2.

Second test:
1-2 the same
3. Right click on some entry and Edit Entry.
4. Type something like "dummy" in Notes.
5. Step 3 from previous section and dragbar is gone like expected.

**Comment by nobugshere** [comment]
Just a note: I'm not able to reproduce this at all with Flatpak or local builds.  
Tested on:
macOS M1Max Sonoma 14.5, Xcode 15.4, wx 3.2.4 and 3.2.5
Fedora 40 ARM64, Xfce/X11, gcc 14.1.1, wx 3.2.4, GTK 3.24.42 (local build and Flatpak)
Fedora 40 ARM64, KDE/Wayland, gcc 14.1.1, wx 3.2.4, GTK 3.24.42 (local build and Flatpak)
Ubuntu 24.04 ARM64, Gnome/Wayland, gcc 13.2.0, wx 3.2.4, GTK 3.24.41 (local build and Flatpak)

**Comment by igor2x** [comment]
I did several tests and I can't reproduce the problem anymore. I don't know if there is some other step involved that this issue appears or I was just too clumsy. I am closing this issue down. If I find out exact steps to reproduce I will reopen the issue.
