### ISSUE TITLE
pwsafe stop with error message (/usr/include/c++/.....)

### ISSUE THREAD

**Issue by womonix** [pwsafe/pwsafe#1327]
pwsafe stops with the following message:

$ pwsafe
/usr/include/c++/14.1.1/bits/stl_vector.h:1130: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = std::__cxx11::basic_string<wchar_t>; _Alloc = std::allocator<std::__cxx11::basic_string<wchar_t> >; reference = std::__cxx11::basic_string<wchar_t>&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
abgebrochen

Systeminfo: 
 GTK: 3.24.42, xfce 4.18,   gcc 14.1.1, kernel 6.9.5-1  Manjaro
pwsafe version 1.19.0-1

**Comment by ronys** [comment]
This was fixed a few weeks ago. Can you try against the recently released 1.19.1?
Please re-open this ticket if the problem persists.
