### ISSUE TITLE
@ronys, today Password Safe v1.19.1 was released for Linux. Can you please build Password Safe for Ubuntu 22.04.

### ISSUE THREAD

**Issue by marcsous** [pwsafe/pwsafe#1330]
@ronys, today Password Safe v1.19.1 was released for Linux. Can you please build Password Safe for Ubuntu 22.04.
Ubuntu releases every 6 mounts, but every 2 years it releases LTS version that is then supported for 10 years (or 12 years...). Ubuntu LTS releases:
- Ubuntu 20.04 LTS  (released: April 2020) --> Password Safe v1.19.1 exists
- Ubuntu 22.04 LTS (released: April 2022)  --> Password Safe v1.19.1 is **missing**
- Ubuntu 24.04 LTS (release: April 2024) --> Password Safe v1.19.1 exists

Currently latest LTS release is Ubuntu 24.04, but majority of people are on Ubuntu 22.04, because before first fix level is released (24.04.1) upgrades to never LTS versions are not offered to people.

_Originally posted by @igor2x in https://github.com/pwsafe/pwsafe/issues/1313#issuecomment-2203514070_
            I was looking for password safe on Ubuntu 20.04 LTS version but couldn't locate it. It's referenced above.

**Comment by igor2x** [comment]
@marcsous, everything looks fine.

1. Go to: https://github.com/pwsafe/pwsafe/releases
2. There should be Password Safe v1.19.1 on Ubuntu 20.04 LTS.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/dedd1d70-cd20-4852-a791-b9def6e960d2)

If you can't see it, then it is maybe hidden. Show All xxxxx Assets" to display for all Linux distribution.

**Comment by ronys** [comment]
The Ubuntu 20 build listed above is for the ARM architecture (raspberry pi). Will build a package for amd64 soon.

**Comment by igor2x** [comment]
@ronys, thanks for head up. I just totally missed the "arm64" tage. My mistake.

Now I see you have already added "amd64" version which is x86_64 (the name I like more, because it is more distinctive, but with the same meaning).

![image](https://github.com/pwsafe/pwsafe/assets/10895030/72d4ec09-4171-4c94-8857-df6415eac8a1)

@marcsous, can you please check, download, test, and if everything is OK, close this issue.
