### ISSUE TITLE
Crash "Assertion '__n < this->size()' failed" on Password Safe v1.19.1 flatpak

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1334]
1. I have upgraded Password Safe to v1.19.1 **(EDIT: It was typo with v1.19.2)** and it looks like at startup program crashes with:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/697eb329-0743-469a-99da-12121d9b80f9)

2. I copied my password database .pwsafe3 file to safe location.

3. Uninstalled flatpak:
`flatpak uninstall -y org.pwsafe.pwsafe`

4. I Opened "Software" GUI and manually delete all of the flatpak remainings.
![image](https://github.com/pwsafe/pwsafe/assets/10895030/a645aeed-d07f-49e9-a28b-0cd214e91e8a)

5. Installed flatpak:
`flatpak install -y org.pwsafe.pwsafe`

6. Started flatpak:
`flatpak run org.pwsafe.pwafe`

and I have got the same error message. Strange... Password Safe v1.18.2 flatpak was working fine!

7. I see similar [issue 1329](https://github.com/pwsafe/pwsafe/issues/1329) was closed down few days ago and suggested to upgrade to v1.19.1 which is the version I am using.

My distribution:
- Blufin 40 that is based on Fedora 40 Atomic Silverblue.

**Comment by ronys** [comment]
I'm confused. Looks like you're running 1.18.2, and not the new 1.19.1.
(There is no 1.19.2, at least, not yet)

**Comment by igor2x** [comment]
@ronsys, v1.19.2 was typo in my first post, I have updated first post to be more clear now.

Version on Flathub.org is source code v1.19.1 with info _Version_ 1.18.2. Confusing? Because when you have updated flatpak, you have forgotten to update _org.pwsafe.pwsafe.metainfo.xml_ file in _github.com/pwsafe/pwsafe/_ repository. Please see [my post](https://github.com/pwsafe/pwsafe/issues/1320#issuecomment-2214837199) in issue 1320.

I assume when update *.metainfo.xml file and publish new version of flatpak, then v1.19.1 will be displayed on Flathub.org.

----

Current issue: I have v1.19.1 and I get above error. And... I have cleansed all of the config files (I hope I did it correctly - just like I described above).

**Comment by nobugshere** [comment]
I can reproduce this problem on Fedora, with the current flatpack release, if I do not already have a pwsafe.cfg file in ~/.var/app/org.pwsafe.pwsafe/config/pwsafe. (Which would be the case on first run.) I can not reproduce it with my native build.

Fedora 40 ARM64 VMware, Xfce/X11, gcc 14.1.1, wx 3.2.4, GTK 3.24.42

**Comment by igor2x** [comment]
I can now reproduce a problem on Ubuntu 24.04 as well following steps from my original post.

When I clean everything (like on a clean install) and reinstall Password Safe, then program crashes.
![image](https://github.com/pwsafe/pwsafe/assets/10895030/490d98df-d985-42e0-bd9e-df6cad2cf9f0)

Now this makes sense, flatpak should not be Linux distribution dependent, when it works it should work on all of supported ones and when it doesn't it should not work on any of them.

**Comment by igor2x** [comment]
I was playing little bit more with this issue.

1. Have removed official Password Safe flatpak's directory.
`rm -rf $HOME/.var/app/org.pwsafe.pwsafe/`

2. Tried to start Password Safe.
`flatpak run org.pwsafe.pwsafe`

And I get crash

> /usr/include/c++/13.2.0/bits/stl_vector.h:1125: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = std::__cxx11::basic_string<wchar_t>; _Alloc = std::allocator<std::__cxx11::basic_string<wchar_t> >; reference = std::__cxx11::basic_string<wchar_t>&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

3. List all of the commits in flathub.org for Password Safe.
`flatpak remote-info --log flathub org.pwsafe.pwsafe`

It lists all of the commits and the previous last commit is:
17893d5acce968a86b739d30910f7f4f9099393c9ac109c2caaf9037569c0841

4. Revert back to previous knowing good commit.
`sudo flatpak -y update --commit=17893d5acce968a86b739d30910f7f4f9099393c9ac109c2caaf9037569c0841 org.pwsafe.pwsafe`

5. (Optional) Freeze (mask) the flatpak, so it does not get automatically updated.
`sudo flatpak mask org.pwsafe.pwsafe`

6. Start Password Safe.
`flatpak run org.pwsafe.pwsafe`
and Password Safe starts up successfully.

7. Double check. Delete the flatpaks directory again (just like in step 1).
`rm -rf $HOME/.var/app/org.pwsafe.pwsafe/`

8. Start Password Safe again.
`flatpak run org.pwsafe.pwsafe`
and it starts up successfully.

9. Check the directory structure.
`tree $HOME/.var/app/org.pwsafe.pwsafe/`
![image](https://github.com/pwsafe/pwsafe/assets/10895030/63d595d2-1642-4772-80ae-6adc6e8566ff)
and it is obvious Password Safe version automatically rebuilds directory structure.

From tests above I conclude that since last flatpak minor update there was some change in source code that produces this error. It looks to me if latest flatpak version config files get deleted (or are missing at first install) then it just fails to start up.

Can someone more knowledgeable look at the source code for latest changes about Password Safe config directories?

**Comment by ronys** [comment]
Problem is common to non-flatpak as well as flatpak, but for some reason only hits the assert on the latter.
Working on a fix, will update soonest.

**Comment by igor2x** [comment]
I think I have found a commit that is causing this issue.
![image](https://github.com/pwsafe/pwsafe/assets/10895030/82d792d5-7995-4aa6-b722-9d0162f37864)

**Details:**
1. From Flathub.org I have downloaded manifest file.
https://github.com/flathub/org.pwsafe.pwsafe/blob/master/org.pwsafe.pwsafe.yml
2. Opened File manifest file.
3. I commented out the line 97 (added # as the first character in line).
4. Then I have went to the github.com/pwsafe/pwsafe source code and copied the individual commit.
4. I have build flatpak according to falatpak documentation https://github.com/pwsafe/pwsafe/blob/master/README.LINUX.FLATPAK.md
5. After each of attemts I did some cleaing: `flatpak uninstall -y org.pwsafe.pwsafe ; rm -rf org.pwsafe.pwsafe`

The results:

| Date       | Commit                                   | Status | Notes           |
| -----------|------------------------------------------|--------|-----------------|
| 2024-05-29 | bb981b1be1d5455e97831f61d27327cb00d1b9e3 | Error  |                 |
| 2024-05-28 | 6273aee1214e190a9eb6e609e495af8e4e8cd080 | Error  |                 |
| 2024-05-23 | df70d486da6723e54851920df6dfc6dbd5ed688f | Error  | First failing   |
| 2024-05-19 | 0d751f212a8c6d6cb3f10bc9288fb6ebcd6bef7a | OK     | Last known good |
| 2024-05-19 | 8434929821ad794513df6fb12bd8071bf15eb318 | OK     |                 |
| 2024-05-18 | d7715bad9fcd08c094fc0e9d172ded297f3fa687 | OK     |                 |
| 2024-05-18 | cc86bb63264997dbc752c66565a10afbd3edac68 | OK     |                 |
| 2024-05-18 | 2fe6079e3c73eeae4ff0b8b0cfdc3c182cbf7b10 | OK     |                 |
| 2024-05-17 | 83d7d1c212263daa137981c88d691d1348fcb509 | OK     |                 |
| 2024-05-14 | 8e76294d17d9c541f488530be8c8526ece011653 | OK     |                 |
| 2024-05-11 | 4a0454124dcea505e7c3f765c7657ef86bdbbff8 | OK     |                 |
| 2024-05-07 | 05718fbb9a589bfd6d92c214b45289d51f9a7f7c | OK     |                 |

**Comment by igor2x** [comment]
I see yesterday https://github.com/pwsafe/pwsafe/commit/de20536e8fa3a35eff52538389686bec432c5504 commit was done to master repository.

I have build flatpak from latest commit from master branch and Password Safe starts on clean install. Looks to me problem fixed.
