### ISSUE TITLE
Built for Manjaro/Arch/SuSe?

### ISSUE THREAD

**Issue by PotatoCarl** [pwsafe/pwsafe#1345]
Hi
is it possible to get a build for openSUSE Tumbleweed and Manjaro?
Thanks.

**Comment by igor2x** [comment]
@ronys, can you give some feedback for creating native packages for those distributions?

@PotatoCarl, have you considered installing [Password Safe](https://flathub.org/apps/org.pwsafe.pwsafe) as [flatpak.](https://flathub.org/setup)?

**Comment by PotatoCarl** [comment]
Obivously not... Thanks for pointing out that possibility.

**Comment by ronys** [comment]
Flatpak's a good option.
Also built and tested for OpenSUSE and arch (tested under Manjaro):
https://github.com/pwsafe/pwsafe/releases/download/1.19.1/passwordsafe-opensuse-tumbleweed-1.19.1.rpm
https://github.com/pwsafe/pwsafe/releases/download/1.19.1/pwsafe-1.19.1fp1-1-x86_64.pkg.tar.zst

**Comment by PotatoCarl** [comment]
Flatpak is not working here, as I cannot access my password file. I do not see any files when searching with the file manager and when I enter it manually, it just says "file not found".

**Comment by igor2x** [comment]
@PotatoCarl, if I understand correctly what you are trying to do is access Password Safe database that was created with native package and access it with flatpak one.

Native Password Safe package stores its files into $HOME/.pwsafe directory. Flatpak version does not have access to this directory. Flatpak version stores its files to $HOME/.var/app/org.pwsafe.pwsafe/config/pwsafe/ directory.

Options:
1. Close down Passwrod Safe if it is opened and copy files from $HOME/.pwsafe/ directory to $HOME/.var/app/org.pwsafe.pwsafe/config/pwsafe/
2.  If you would like to preserve Password Safe current directory for setting and database:
  a) then use flatpak command to assign permissions:  `flatpak override org.pwsafe.pwsafe --filesystem=<path_here>`
  b) or use tool GUI tool like FlatSeal (can be installed as flatpak) and select Password Safe from left side of flatpak list and them assign permissions to specific directory in _File System_ section.
![image](https://github.com/user-attachments/assets/b2978aa3-d5e5-4a2b-abb2-d73989f03312)
