### ISSUE TITLE
Inconsistent naming Database vs. Safes

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1346]
Password Safe v1.19.1 on Ubuntu 24.04:
1. Manage | Options | System and there is option _Recent Databases on File Menu rather then as a sub-menu_
2. Close down Password Safe and reopen (Note: No info in program this is required).
3. Menu File and there is option _Recent Safes_.
4. Compare wording from step 1 (Database) with wording in step 3 (Safes). If I remember correctly we have already defined somewhere that "safes" is outdated and should be replaced with "database".

![image](https://github.com/user-attachments/assets/a8e4f87e-c23f-4d45-9713-7fb24dd5fc1b)

**Comment by rafaelx** [comment]
In other applications I have seen that the menu entry for clearing the list is part of the list and is therefore in the submenu.
