### ISSUE TITLE
Question: Date time formats to use with CLI commands

### ISSUE THREAD

**Issue by cjlotz** [pwsafe/pwsafe#1349]
Hello

I'm trying to set the `Created Time` when adding an entry via the CLI command but I'm not able to figure out in what datetime format to provide the value.  I've tried File time UTC and ISO 8601 formats.  The CLI command returns exit code zero, but when I view the entry in the Safe, the Created On is not set

![image](https://github.com/user-attachments/assets/f9ae39e7-bee3-4dc3-86ab-e59eebe13e2d)

What format should I specify the value in?

**Comment by rafaelx** [comment]
I had success with the following command line under Linux.

```
./pwsafe-cli pwsafe.psafe3 --add=Title=TestTitle,Username=TestUsername,Password=TestPassword,"Created Time"="2020/10/02 12:13:14"
```

The keyword "now" can also be used to refer to the current time.

```
./pwsafe-cli pwsafe.psafe3 --add=Title=TestTitle,Username=TestUsername,Password=TestPassword,"Created Time"=now
```

**Comment by cjlotz** [comment]
Thank you so much.  I got it working using your examples.
