### ISSUE TITLE
Question:  Examples of using CLI to create hierarchical structure

### ISSUE THREAD

**Issue by cjlotz** [pwsafe/pwsafe#1350]
Hello

I'm trying to use the CLI to create a hierarchical structure of groups with entries

```
Root
  - Subgroup 1
    - Entry 1.1
    - Entry 1.2
  - Subgroup 2
    - Entry 2.1
```   

I've tried adding a group only using `--add=Group=Root` but that results in an error stating _Title must be specified for new entries_.  I'm currently unable to figure out how to add a group without an entry and how to create a nested structure.  What would be the sequence of CLI commands to create a structure like this?  

Are there any further documentation examples available on how to use the different CLI commands like adding, updating an existing entry?

**Comment by rafaelx** [comment]
I would suggest using the [discussion](https://sourceforge.net/p/passwordsafe/discussion/) forum on SourceForge for such questions as it has a larger user base.

If you want to add a new entry, the title is a required field, while all other fields are optional. If no password is specified, a password is generated.

This means that to create a new group, at least one entry must be created in it.

(Written by a non-CLI user :)

**Comment by cjlotz** [comment]
Will revert to discussion forum, thanks
