### ISSUE TITLE
[cli] Segfault in pwsafe-cli when exporting a DB with a custom policy

### ISSUE THREAD

**Issue by nobugshere** [pwsafe/pwsafe#1351]
When I try to export a database in XML format I get a segfault if the DB contains a custom policy.  I was able to determine the location of the error, but I don't really understand the code well enough to know what's intended.  I'm hoping someone else can fix it easily :)

It fails at `CoreImpExp.cpp:571` because `il` was not passed as a parameter, so it defaulted to nullptr.
`stringT pwpolicies = GetXMLPWPolicies(il)`
Called from `impexp.cpp:37`
`core.WriteXMLFile(std2stringx(ua.opArg), all, L"", 0, 0, L' ', L"", N)`

This command line failed on macOS with the 1.19.1 release:
`pwsafe-cli segfault.psafe3 --exp --xml --passphrase t`

This test DB has one entry and a custom policy "testpol16"
[segfault.psafe3.zip](https://github.com/user-attachments/files/16448698/segfault.psafe3.zip)

---
EDIT: This case does _not_ fail in the pwsafe GUI app.

**Comment by ronys** [comment]
Thanks. The fix was the straightforward one, treat a null il as an indication that named policies are to be exported, not policies of specific entries.
Not passing an il parameter was only done in the cli, which was written long after WriteXMLFile().
