### ISSUE TITLE
Browser Command Line parameters not sticking and Miscellaneous Help Missing

### ISSUE THREAD

**Issue by user-629782** [pwsafe/pwsafe#1374]
Trying to add "--private-window" command line parameter for Firefox in the Miscellaneous settings of pwsafe, however this does not work (stay saved). Using Ubuntu 22.04.04 Gnome (Wayland) Linux and pwsafe version 1.19.1
Also, the Help file for Miscellaneous is missing (although I suspect this is already known) and when clicked yields the following error:

![help-error](https://github.com/user-attachments/assets/beb98a24-f16b-4a5d-9992-a86ec4225211)

Thank you

**Comment by user-629782** [comment]
Hello @ronys, thanks for looking into this issue. However after trying v1.20.0 it appears it is not working as expected. I might be missing something but after populating both the Alternate Browser field and the Browser Command Line parameters field it does not appear to be used.

For example, if I use /usr/bin/firefox as the Alternate Browser with --private-window as the only Command Line parameter and then right-click a password entry and select Browse to URL, I would expect the URL of the entry to appear in a private window. Unfortunately, using ps, it shows the default /usr/lib/firefox/firefox-bin executable running with the URL and no --private-window parameter.

I tried using different methods and options but could not get it to work. It appears that PWSafe is launching Firefox through some other means not associated with the fields in the Miscellaneous page. Did you actually get this to work after fixing the wx front-end bits?

Please let me know if I am doing something wrong or there is another way of approaching this problem.

Thanks

**Comment by rafaelx** [comment]
Maybe the instruction that the alternative browser should be used for the URL is simply missing?

From the documentation:

> **Alternate Browser**
The browser you specify in this field  will be used when using the "Browse To" function for a selected entry, when the entry's URL has "[alt]" before the URL, e.g., "[alt]http://www.foo.net". This is useful, for example, if your default browser is Firefox, and you wish to access a website that works best with Internet Explorer, in which case you should specify the Internet Explorer as your alternate browser (typically "C:\Program Files\Internet Explorer\iexplorer.exe).

**Comment by user-629782** [comment]
Yay, thank you so much @rafaelx that does work placing the [alt] tag with the URL. That little nugget of info would have saved me some time if was on the Help->Miscellaneous page. Missed that in the documentation. Thanks again....
