### ISSUE TITLE
Wrong link to release notes for 1.20.0

### ISSUE THREAD

**Issue by hansfn** [pwsafe/pwsafe#1403]
On https://github.com/pwsafe/pwsafe/releases/tag/1.20.0 the link [ReleaseNotesWX.md](https://github.com/pwsafe/pwsafe/blob/1.120.0/docs/ReleaseNotesWX.md) should be https://github.com/pwsafe/pwsafe/blob/1.20.0/docs/ReleaseNotesWX.md

**Comment by ronys** [comment]
Fixed - thanks!
