### ISSUE TITLE
The 1.20.0 release is missing something...

### ISSUE THREAD

**Issue by nobugshere** [pwsafe/pwsafe#1404]
Hi @ronys,
I don't mean to be a nag, but the macOS build is missing from the 1.20 release assets.
And don't forget to update the Flatpak build :-)

**Comment by ronys** [comment]
Both are on the release checklist, will get around to them soonest

**Comment by ronys** [comment]
All done: dmg added, PR submitted to flathub repo, adjusted SF files location.

**Comment by igor2x** [comment]
On SF there is still 1.20 folder in incorrect location:
![image](https://github.com/user-attachments/assets/9447c618-d9e1-439f-98e4-1f9000d7a97e)

Additionally I also see 1.20 in Linux dir which is OK.
![image](https://github.com/user-attachments/assets/ec4bf247-dc70-4988-b9f9-18569fa49c57)

**Comment by ronys** [comment]
This is a side effect of SF's sync mechanism, which is a bit inflexible.
Fixed - thanks.
