### ISSUE TITLE
Blank Screen using Blast

### ISSUE THREAD

**Issue by neongreen88** [pwsafe/pwsafe#1413]
When using password safe on VDI over blast connection on version 3.64 or newer screen turns black when accessing password safe and cannot access password safe. Tested successful on version 3.63 password safe. When connecting VDI over PCIOP works on all versions.

**Comment by ronys** [comment]
This is due to the screen capture protection added to PasswordSafe in 3.64.
You can disable this at install time by unchecking "Screen capture Protection" in the installation wizard.
