### ISSUE TITLE
PasswordSafe New Entry(Linux 0.99)

### ISSUE THREAD

**Issue by peter-hb** [pwsafe/pwsafe#143]
PasswordSafe 0.99 (Linux BETA) under Debian 8.5 and KDE 4

A new entry does not offer password generation.

**Comment by romanpitak** [comment]
Hi could you elaborate on reproducing this? I'm also using using `v0.99 beta` (on Gentoo, KDE 5)

![image](https://cloud.githubusercontent.com/assets/2676459/17461215/46907328-5c85-11e6-9c72-f20d2e00d840.png)

and after clicking on `"Add New Enry"` I get a dialog with a working `"Generate"` button. 

![image](https://cloud.githubusercontent.com/assets/2676459/17461226/889fc08e-5c85-11e6-9aa2-c6573da6108a.png)

**Comment by peter-hb** [comment]
My mistake. The initial dialogue box was only sized to embrace the "Show" button. I had assumed that it was a fixed size, but on stretching the right-hand edge I found "Generate". Perhaps that is the bug?

**Comment by romanpitak** [comment]
I was lucky :) My box partially covered the `"Show"` button which made me resize the window. 

> Perhaps that is the bug?

It is a bug, but not this one. You should probably open a new issue (with a screenshot) regarding the *initial window size*; and close this issue.

**Comment by peter-hb** [comment]
Agreed.
