### ISSUE TITLE
Read-only when opening PassSafes v.20?

### ISSUE THREAD

**Issue by allywilson** [pwsafe/pwsafe#180]
In the latest versions of PassSafe V3.38 and V3.39 we are unable to edit PassWord safes created with a v2 database. I can't see an option to convert/upgrade the database either.

The files appear to always be in Read-Only mode. If you lock, then unlock, it lets you create new entries, but it is unable to Save the changes.

**Comment by ronys** [comment]
To convert a V2 database, just save it via File->Save. It will be save in the V3 format, which can be opened and edited.
