### ISSUE TITLE
Provide signed source tarballs along with the signed .deb and .rpm packages

### ISSUE THREAD

**Issue by namarrgon** [pwsafe/pwsafe#190]
I'm sorry to bring this up again after #129.
I don't know how the *.deb and *.rpm packages are being generated and signed, whether this is an automatic or manual process, but could the source tarballs be incorporated into this so we can use them for non-rpm/deb distributions?

**Comment by ronys** [comment]
Hm. As I wrote in #129, signing the sources is a manual process. I'll see how I can automate it, though. Will close this one I've signed the current ones.

**Comment by ronys** [comment]
tarball and zip downloaded compared to my source tree and signed.
Signatures uploaded.

**Comment by namarrgon** [comment]
Thank you!
