### ISSUE TITLE
Status of OS X port?

### ISSUE THREAD

**Issue by kainjow** [pwsafe/pwsafe#23]
What is the status of the OS X port with wxWidgets? Is this going to become an official build? I haven't tested the Linux or Windows build yet, so I'm not sure of what functionality is actually missing from wxWidgets, but there definitely are several issues I've seen with the UI. For example:

- On-screen keyboard buttons do nothing
- Some help pages, for example Edit Menu, throw up an error "iCCP: known incorrect sRGB profile" when displayed. I imagine a re-save on the PNGs should fix that.
- Help > Visit Password Safe website does nothing (seems duplicate functionality with the About box)
- English is the only language that can be chosen
- Delete Group contextual menu is disabled
- Customize Main Toolbar menu does nothing

I wouldn't mind contributing improvements for the Mac version. I started working on my own password manager but really would prefer working on an existing open source project instead of duplicating efforts.

Lastly, I think moving to CMake would greatly simplify the project files. It could replace all the project files for Visual Studio, Xcode, CodeLite and CodeBlocks. I could contribute the initial version to replace the Xcode project.

**Comment by ronys** [comment]
Hi Kevin,

I would love to make the wx/Mac build part of the official offering. The
main limiting factor is the lack of resources.

Note that we're planning on merging v4 into master in a few weeks. Most of
the work is in core, so anything you do in ui/wx shouldn't be too badly
affected, though.

As to cmake, Sami has got the basics of this working in his fork at
https://github.com/Safari77/lumimaja - you might want to start from there -
I'll be glad to switch to it once the nits have been fixed.

Cheers,

  Rony

**Comment by kainjow** [comment]
Great, I will take a look at lumimaja.

The other benefit of using CMake is CPack, which makes it very easy to generate Windows installers (WiX/NSIS), OS X DMGs, debs, zips, etc.

**Comment by kainjow** [comment]
Closing. I will start submitting pull requests slowly over time :)

**Comment by ronys** [comment]
Hi Kevin,

​Any progress on cmake? I'm looking into it myself. Let me know if you've
made any progress, to avoid duplicate work.

Cheers,

  Rony​
