### ISSUE TITLE
layout problem when username is displayed in tree view

### ISSUE THREAD

**Issue by guidorice** [pwsafe/pwsafe#241]
Hi I hope this is the right place to report issues! Also thanks so much for the Linux version, it is working great. Using is v1.0.1Beta (Dec22) on Ubuntu 16.04 LTS. By going to Manage | Preferences | Display | 'show username in tree view' then the layout increases to a huge amount of vertical space between items. Everything still works fine, it just is visually a bit off.

![screenshot from 2016-12-31 11-33-55](https://cloud.githubusercontent.com/assets/766758/21578823/110aae86-cf4d-11e6-964b-6231b65c7d84.png)

**Comment by ronys** [comment]
Odd, I can't duplicate this on my Ubuntu VM. This might be a font issue. Can you try changing fonts via View->Change Font

**Comment by guidorice** [comment]
Hi Rony, OK I tried several different fonts, and restarting the app, but still same results: when username is displayed in tree view, it the layout gets all expanded like my screenshot.

**Comment by guidorice** [comment]
Actually NVM- I solved it. I scrolled through all my categories and looked at the usernames and I had one that was a very long string, which I had obviously copy pasted in there at some point. I edited that, restarted the app, and fixed the problem. Thanks so much & sorry for the noise!
