### ISSUE TITLE
Segfault in Fedora 25

### ISSUE THREAD

**Issue by rhasti** [pwsafe/pwsafe#249]
Starting Application does work. 
Segfault appears anytime you open a safe file.
Tried RPM and building from source.

**Comment by ronys** [comment]
Yes, this is an issue with the wx library and the new X windows implementation in Fedora 25. Not something that I can fix in PasswordSafe code.

**Comment by ronys** [comment]
Here's a workaround that's reported to work (Thanks to Thorsten Fuchs):

You can set the environment variable "GDK_BACKEND=x11" before starting pwsafe to make it run without having to completely change to X11.

There are two options:
1. Start through terminal:
Type "GDK_BACKEND=x11 pwsafe" every time or create a small shell script
2. Start through gnome: 
Change the "Exec" field in the .desktop file to "env GDK_BACKEND=x11 pwsafe %f"
