### ISSUE TITLE
Customize Main Toolbar adds wrong buttons

### ISSUE THREAD

**Issue by Th1990** [pwsafe/pwsafe#267]
Version: 3.41
OS: Windows 7
Installed in portable mode

When I go to Manage > Customize Main Toolbar and add new button to the toolbar sometimes wrong button gets added.

For example, when I add button "Add group" all looks fine in the selection tool. But the button that gets actually added to the toolbar is "Manage Filters". Similarly adding button "Password Policies" actually adds button "Add Group."

Many other buttons, such as "Run command" get added correctly.

**Comment by ronys** [comment]
Thanks for reporting this - it was fixed in commit ed46cc9 a few days after 3.41 was released.
(see also https://sourceforge.net/p/passwordsafe/bugs/1384/)
