### ISSUE TITLE
Features of upcoming release

### ISSUE THREAD

**Issue by jlanzarotta** [pwsafe/pwsafe#292]
Is there a list of new features that will be available in the upcoming release?  Or possibly a release schedule?

Thanks,

**Comment by ronys** [comment]
We're starting to think of a release in a few weeks, with some minor fixes
and tweaks. Do you have something specific in mind?

**Comment by jlanzarotta** [comment]
I was really looking for a timeline of when the upcoming releases were going to happen and what features were thought to be in each release.  It was mainly looking out of curiosity.

Then, I was wondering if there were thoughts of adding an option to clear the clipboard after X number of seconds after something was copied to it.  I downloaded the code and was thinking about taking a crack at adding something like that.  However, before I took on that challenge, I wanted to check...

**Comment by ronys** [comment]
Since this is a "spare time" project, it's hard to commit to a timeline.

The clipboard can already be set to clear upon minimize, which can be set to occur after X minutes of inactivity. I'm not sure that an additional timer on the clipboard would be worthwhile, but am willing to be convinced...
