### ISSUE TITLE
PGP signatures for Linux release 1.02BETA source archives are missing

### ISSUE THREAD

**Issue by georgefx** [pwsafe/pwsafe#329]
The PGP signatures for the source archives are missing:
```
https://github.com/pwsafe/pwsafe/archive/1.02BETA.zip.sig
https://github.com/pwsafe/pwsafe/archive/1.02BETA.tar.gz.sig
```
This blocks building passwordsafe from the AUR on arch linux:
https://aur.archlinux.org/packages/passwordsafe/

Thanks!

**Comment by Zerout** [comment]
This is also the case for the 1.02.1BETA release.

By the way the correct URL pattern for the .sig files is https://github.com/pwsafe/pwsafe/releases/download/$(version)/$(version).$(archive_extension).sig, which still indicates that the PGP signatures for both 1.02BETA's and 1.02.1BETA's source code is still missing.

**Comment by ronys** [comment]
Added - sorry about the delay. I need to remember to download the sources that github creates and check them against my own before signing...
