### ISSUE TITLE
verify signing key for 3.42.1

### ISSUE THREAD

**Issue by bryan-p** [pwsafe/pwsafe#330]
I can't seem to locate where I can verify the signing key for the latest versions pwsafe. It seems a new key is being used to sign the latest version of pwsafe.  fingerprint is: C8876BE69A8EC6414C8C8729B131423D7F2F1BB9

Would like to verify before installing. Thanks.

**Comment by ronys** [comment]
See the bottom of the contact page https://pwsafe.org/contact.php and/or http://pgp.mit.edu:11371/pks/lookup?op=get&search=0xB131423D7F2F1BB9

**Comment by bryan-p** [comment]
ahh, ok thanks.  Perhaps you could link to it in the ReadMe file, would be easier to locate that way.
