### ISSUE TITLE
When scanning pwsafe64-3.42.0.exe flagged with W32.eHeur.Malware08 from Virustotal

### ISSUE THREAD

**Issue by cptfrankdatank** [pwsafe/pwsafe#335]
Could you look into why VirusTotal detects possible malware associated with the .exe? This could be a false positive but I wanted to bring it to your attention. 

https://virustotal.com/en/file/484862ab2612821df15c22ff1d6014a987119dda0fa4c392686d4db4a894923f/analysis/1497290419/

**Comment by ronys** [comment]
Hi,

1. In my experience, one (or even two) detections out of 61 scans is a false positive.
2. Current version is 3.42.1, not 3.42.0...

Please reopen if you have other indications of a problem.

**Comment by cptfrankdatank** [comment]
The 32bit is coming up whit 3 hits. I assumed its a false positive as well but I wanted to share. 

https://virustotal.com/en/file/a7c710329b869caa7bd59fa902e0377ab65b856c6512c7d09b188ffd3889a822/analysis/

**Comment by ronys** [comment]
Where did you get the rar file from? You might want to download from the github repo. https://github.com/pwsafe/pwsafe/releases/tag/3.42.1
