### ISSUE TITLE
pwsafe-cli aborts with a broken assertion when doing a --search

### ISSUE THREAD

**Issue by ghost** [pwsafe/pwsafe#356]
I ran: `src/ui/cli/pwsafe-cli ~/.pwsafe --search=protonmail` and got:

```
Enter Password [/home/user/.pwsafe.dat]: 
pwsafe:[5797]: PWSprefs - using existing config file: /home/user//.pwsafe/pwsafe.cfg [R/W]
pwsafe-cli: PWSfileV1V2.cpp:385: size_t PWSfileV1V2::ReadCBC(unsigned char&, StringX&): Assertion `wcLen != 0' failed.
Aborted
```

**Comment by ronys** [comment]
Also hit the same assert with the GUI version. Looks like an encoding problem with .dat files. Not surprising, since non-ASCII support was a bit problematic in early versions...

**Comment by libBletchley** [comment]
That doesn't make sense to me.  If early versions had a problem with non-ASCII support, then the current version would not be falling over on non-ascii input.  But this is the opposite case, where the old version works fine, and the current version pukes.  Also, the db the current version is opening was produced by this version: https://github.com/skx/pwsafe (which is old), thus would not contain non-ASCII chars.  So the non-ascii scenario does not seem to be in play here.

The current GUI instance handles the db without issue.  In principle, there's no reason why the GUI and CLI instances of the same version should differ w.r.t db parsing.  This suggests a design flaw, whereby code is not being shared or reused between GUI and CLI instances to the extent that it should be.

**Comment by ronys** [comment]
Please provide a sample database that works with the GUI version but not with the CLI.

**Comment by libBletchley** [comment]
It may be a while before I can come through with that.. it's a large database that I'd have to scrub and reduce and the installation is not on a system that I use regularly.

**Comment by rafaelx** [comment]
Can't reproduce.
