### ISSUE TITLE
Wrong codepage for Russian in pwsafe-3.44.0 installers

### ISSUE THREAD

**Issue by mwz-ru** [pwsafe/pwsafe#357]
There is a wrong codepage for Russian both in pwsafe-3.44.0.exe and pwsafe64-3.44.0.exe installers.
No such problem in pwsafe-3.43 installers.

See the attached screenshot with "Please, close all the running Password Safe instances" dialog in v3.43 and v3.44.

![pwsafe-344_inst](https://user-images.githubusercontent.com/32673165/31386668-45361616-add0-11e7-974d-9e277ce510d9.gif)

**Comment by ronys** [comment]
The only cause I can think of is that I've switched computers before release 3.44. Perhaps there's an issue with the installer generator version on the new machine.

Attached is a sample installer program that only demonstrated the installer (NSIS) language support. Can you run this on your machine and let me know if the Russian texts are displayed correctly?
[languages.zip](https://github.com/pwsafe/pwsafe/files/1384590/languages.zip)

**Comment by mwz-ru** [comment]
Thank you, seems to be Ok now:

![image1](https://user-images.githubusercontent.com/32673165/31677793-93ca1102-b374-11e7-85d1-46dbaca0a0f0.gif)

**Comment by ronys** [comment]
Could you please check the version of PasswordSafe I've uploaded to https://pwsafe.org/tmp/pwsafe-3.44.1.exe ?

**Comment by mwz-ru** [comment]
Nah... Even more terrible:

![pwsafe_wrong2](https://user-images.githubusercontent.com/32673165/32148053-f105046c-bd01-11e7-903d-22b4b37a7bdd.gif)

(unfortunately I can continue to discuss this only in a week, presumably on Saturday).

**Comment by ronys** [comment]
OK, I've uploaded a new version to the same place (https://pwsafe.org/tmp/pwsafe-3.44.1.exe).
No rush, but let me know what you find.

Thanks.

**Comment by mwz-ru** [comment]
A new 32-bit version — no problem at all steps. :)

Tested with:
Win-10 x64 en-US
Win-7 x64 RUS
Win-7 x86 RUS

Thank you!

**Comment by ronys** [comment]
Thanks for reporting and testing, and thanks to @pm-kan for the fix.
