### ISSUE TITLE
Command Line -s not working

### ISSUE THREAD

**Issue by jlanzarotta** [pwsafe/pwsafe#359]
Hello,

I am using Password Safe V3.44 (g52211c406+) 64-bit, upgraded from V3.43.0.

I have a shortcut in the Windows->Startup Folder that starts Password Safe automatically on startup.  My command line is "C:\bin\PasswordSafe\pwsafe.exe -s "%HOMEDRIVE%%HOMEPATH%\Documents\My Safes\pwsafe.psafe3".  This command line use to work great in the previous version where the application would indeed start minimized.  However, in the new version the application is started not minimized.

Any ideas?

Thanks.

**Comment by ronys** [comment]
Fixed in commit d8923b5a5, will be in next release.
