### ISSUE TITLE
Icon color when no database opened is Green

### ISSUE THREAD

**Issue by B00ze64** [pwsafe/pwsafe#360]
Good day.

Updated to 3.44 just now Win7 x86 version. Noticed this in release notes: 

> The option that allows you to change the color of the system tray icon displayed when Password Safe is initially started and when there's no open database has been removed. The standard PasswordSafe brown icon will be used.

Well, the icon that appears in my Systray when the program is first started is Green, not brown. This is kinda confusing, I'm thinking "Did I forget to exit PWSafe the last time?"

Also noticed that if I start PWSafe, but click on CANCEL instead of opening a database, the icon remains in the Systray (until we hover over it with the mouse). If I do this several times I end-up with a nice line of PWSafe icons in the Systray. EDIT: Well previous version (3.43) has the same behaviour, the icon stays in the Systray if we quit without opening a database...

Thank you.
Best Regards,

**Comment by ronys** [comment]
Thanks for reporting this. Will address this in the next release.

**Comment by ronys** [comment]
Fixed in commit f0116ac2d. Will be in next release.
