### ISSUE TITLE
[enhancement] cannot add groups to the root, group (content) move

### ISSUE THREAD

**Issue by grinapo** [pwsafe/pwsafe#366]
It seems I cannot "add group" to the root after the first group, as it adds the group under the currently selected one and I cannot _deselect_ the actual entry (or select root). I can create groups under root by editing one entry's "group" field.

Similar problem is that it's not simple to move the content of a group, like merging two into one or to move a group from sub1.sub2.group to sub1.group, for example (or under the root, as it appeared when examining the problem above).

**Comment by rafaelx** [comment]
The first part, adding of groups/items to the root at tree view, should be resolved by #607.

**Comment by KaiZin2018** [comment]
With actual code version in macOS clicking into empty space lower than the tree list the selection is removed and a new group can be created in the root folder.

**Comment by ronys** [comment]
Closing as obsolete.
Both issues have been addressed.
