### ISSUE TITLE
Search remains open after database has been closed

### ISSUE THREAD

**Issue by HeroicKatora** [pwsafe/pwsafe#375]
Potentially exposes information about a closed database.

Description
-------------
This appears to be a bug in the UI exposing some internal information from the last opened database. When closing a database while the search bar is open, the search string and the metadata of the results (count and other search parameters) are still visible. This also happens when the database is locked due to inactivity.

Reproduction steps
-------------
1. Open a password database
2. Bring up the search bar and search for an existing entry
3. Close the database
4. The search bar, its entries and the count of search results is still visible

Expected behaviour
-------------
Since search results represent information about the contents of the database, they should not be accessable after the database has been closed.

Environment
-------------
Version: 1.03BETA-2 linux
Operation system: Arch

**Comment by ronys** [comment]
Fixed in commit d1763b12c
