### ISSUE TITLE
WX build fails due to commit "Fix build failures with wxgtk 3.0.3.1"

### ISSUE THREAD

**Issue by diomhaireachd** [pwsafe/pwsafe#381]
Both the static casts need to be enclosed in ()
`std::wistringstream is(static_cast<const wchar_t*>pos_str.wc_str());`
to
`std::wistringstream is(static_cast<const wchar_t*>(pos_str.wc_str()));`

**Comment by ronys** [comment]
Thanks - Fixed in commit c77da2dfd
