### ISSUE TITLE
Auto Type replaces @ with ⅛

### ISSUE THREAD

**Issue by vansieleghemstijn** [pwsafe/pwsafe#41]
Every time I use auto type and the username containts an @ character, it is replaced with ⅛.

I'm using v0.96-beta on Ubuntu Linux.

3.16.0-54-generic #73~14.04.1-Ubuntu SMP Tue Nov 10 17:46:26 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Safari77** [comment]
for me @ is replaced with \u201d
```
201D;RIGHT DOUBLE QUOTATION MARK;Pf;0;ON;;;;;N;DOUBLE COMMA QUOTATION MARK;;;;
```

**Comment by Safari77** [comment]
also, **`** is deleted and **|** is replaced with **<** , **^** is replaced with \u201e
```
201E;DOUBLE LOW-9 QUOTATION MARK;Ps;0;ON;;;;;N;LOW DOUBLE COMMA QUOTATION MARK;;;;
```

**Comment by sauravg** [comment]
If you can build the latest code from github, it should fix these issues. If not, please post the following details:

1. Your keyboard layout
2. Your language settings
3. Some test data (please create a small safe with dummy username/password) that can be used to repro the problem
4. Outputs of "xmodmap -pk"  & "xmodmap -pm"
5. File generated by "xkbprint :0"
6. The keystrokes you press to generate the symbols pwsafe is mangling up.
