### ISSUE TITLE
System tray icon colors and transparency in Linux

### ISSUE THREAD

**Issue by tknarr** [pwsafe/pwsafe#43]
The system tray icons in Linux have a white background instead of being transparent, and there's no way to set the color of the closed-database icon like there is in Windows (looks bad on a dark system tray background).

I'm working on a fix for this on my fork.

**Comment by tknarr** [comment]
Pull request #44 created for this issue: https://github.com/pwsafe/pwsafe/pull/44

**Comment by ronys** [comment]
Thanks for submitting a fix. I recall there was some issue where clicking on the "transparent" parts of the system tray icon would have no effect, and making them white was the workaround we found for this.
Need to check if this fix is a regression w.r..t that issue or not, hopefully within a couple of days.

Cheers,

  Rony

**Comment by tknarr** [comment]
It may be tray-specific. Under the Xfce system tray clicking on the transparent bits brings up the dialog or menu like it should. If it misbehaves on other trays I can add a white/black/transparent background option and make it use the appropriate set of icons.
