### ISSUE TITLE
New logo design for PW SAFE

### ISSUE THREAD

**Issue by sametceylan** [pwsafe/pwsafe#442]
Hello sir, my name is Samet Ceylan and I am a designer. If you want and let me, I want to design a creative logo for PW SAFE. I want you to know that I will do it for you. I do not want any compensation. If you would like me to design and if you have any particular detail, please contact me.

**Comment by ronys** [comment]
Hi Samet,

Your kind offer is much appreciated.

I'm not sure I want to replace the distinct brown triangle that harks back to the very beginning of the project, but perhaps something similar in spirit that takes advantage of a wider color palette or the higher resolution available today would be nice.

What I would really like to replace is the orange-ish "Password Safe" text on the opening screen. I'm sure a professional designer could do much better than that quite easily!

Let me know how you'd like to proceed.

Thanks,

  Rony

**Comment by rafaelx** [comment]
@sametceylan are you still interested in creating a new design?

**Comment by sametceylan** [comment]
Hahahaha. After one and half year? No way dude...
