### ISSUE TITLE
Install issue with Ubuntu 18.04

### ISSUE THREAD

**Issue by ProfM2** [pwsafe/pwsafe#445]
Following the guide from README.LINUX.DEVELOPERS.md, I can get PasswordSafe to compile.  The executable that is created does run, and appears to open my safes correctly, but it does have a blank warning popup when a safe is opened.

However, the DEB refuses to install, because of an unmet dependency: libxerces-c3.1
The version that is currently available is libxerces-c3.2, but it isn't recognized as a met dependency. NOTE: This applies to the current 1.05BETA on SourceForge, AND to the built DEB direct from the source.

**Comment by bblough** [comment]
For a quick fix, I think you should be able to find/replace libxerces-c3.1 with libxerces-c3.2 in CMakeLists.txt before building.

I think the ideal long-term solution is to have cmake detect what version is installed and supply that to the package control file (I assume this is possible - I'm not that familar with cmake).

Also, you'll still have the warning pop-up, as 1.05 has an issue finding the help files.  This is fixed in git, so if you're going to compile anyway, you might consider pulling it from the repo, rather than using the tarball.

**Comment by ProfM2** [comment]
Thanks for the info ... I'll go ahead and try that.

As far as the help file goes, I'm actually seeing that it cannot initialize the help system error, in addition to right after trying to open a safe, it pops up another warning box.
[https://image.ibb.co/mweTBx/pwsafe_warning.png](https://image.ibb.co/mweTBx/pwsafe_warning.png)

**Comment by bblough** [comment]
Are you still getting the popups after the successful build/install?

**Comment by ProfM2** [comment]
Yes, see the link above.

However, the error for the help file no longer appears, and help seems to work correctly from within PasswordSafe.

**Comment by bblough** [comment]
I don't have access to an Ubuntu machine right now, but I cloned git and did a cmake build on my Debian machine.  With the database directory read-only, I do get a pop-up saying that it couldn't create a lockfile.  So I guess the puzzle is why the text isn't showing up for you.  What are your locale settings?

**Comment by bblough** [comment]
Also, if it's not too much trouble - could you try uninstalling the deb you built and installing 1.04 from the Ubuntu repositories and see if it behaves the same way?

**Comment by ProfM2** [comment]
My **locale**:

    LANG=en_US.UTF-8
    LANGUAGE=
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=

Well, I uninstalled the 1.05 that I created, and installed the Ubuntu package for 1.04.  It does the exact same blank popup.  What's really bizarre is the permissions for both my Dropbox and Downloads is identical, yet its behaving like it cannot read/write the Dropbox location.  The permissions on the Dropbox folder is 770 (which hasn't been changed from when it was installed)

When I was running Ubuntu 17.10, I had PasswordSafe 1.03, and had no similar issues, even with the Dropbox folder.

**Comment by bblough** [comment]
Thanks for the additional info.

You might still have a lock file hanging around in your Dropbox folder.  It would be the same name as your DB file, but with a .plk extension.  That would cause the DB opened from that location to give a "read-only" error.  I use service similar to Dropbox, and I wound up filtering the plk files so they don't get sync'd to other systems and cause similar issues.

Of course, that still doesn't explain why your message box has no message in it...

**Comment by bblough** [comment]
OK, I spun up an 18.04 VM, and installed 1.04 from the repository.  If I force the lock error message (by opening the same database twice, or by putting a lockfile when there shouldn't be one), I get the "read-only" popup, but it has the expected text in it.

I'm not sure what other messages can be triggered on unlock.  It's possible that you're getting a different message and that's what's broken.  Or it's possible it could be something specific to your installation.

**Comment by ProfM2** [comment]
It very well could be something specific with my installation.

Regardless of the popup warning on a safe in Dropbox, the bigger issue has been answered, installing 1.05 on Ubuntu 18.04.

Thanks for point me in the right direction for the CMakeLists.txt.
