### ISSUE TITLE
NO_QR Option Doesn't Prevent Building With qrencode.h Dependencies (Linux)

### ISSUE THREAD

**Issue by PorcelainMouse** [pwsafe/pwsafe#447]
I set NO_QR option, but my build fails with:

g++ -c -o GCCUnicodeDebug/pwsqrencode.o  /usr/bin/wx-config-3.0 --debug=yes --unicode=yes --inplace --cxxflags -DUNICODE -I../.. -fPIC -ggdb -D_DEBUG -O0 -Wall -DUSE_XML_LIBRARY=XERCES -DWCHAR_INCOMPATIBLE_XMLCH   -std=c++11 pwsqrencode.cpp

pwsqrencode.cpp:11:10: fatal error: qrencode.h: No such file or directory

 #include <qrencode.h>
          ^~~~~~~~~~~~

Do you see this or am I doing something else wrong.  I ran through the README.CMAKE a couple times.  I'm at tag 1.05BETA.

**Comment by ronys** [comment]
Just checked - this works for me.
You should click on Configure, followed by Generate in cmake-gui after checking NO_QR.

Closing this ticket - contact me directly if the problem repeats and I'll try to help.
