### ISSUE TITLE
3.47 copy url to clipboard no longer works

### ISSUE THREAD

**Issue by redranamber** [pwsafe/pwsafe#476]
It was working on 3.46 but after updating nothing happens when I try to copy a url.

**Comment by ronys** [comment]
What version of Windows are you using?

**Comment by redranamber** [comment]
Windows 10 1803

**Comment by redranamber** [comment]
Right, none of them are working I hadn't noticed because I was using autotype which is working.

**Comment by rafaelx** [comment]
Related to reported [issue 1468](https://sourceforge.net/p/passwordsafe/bugs/1468/) on SourceForge.
