### ISSUE TITLE
Dependency problem: 3.4.4-1+b2

### ISSUE THREAD

**Issue by tubby1981** [pwsafe/pwsafe#478]
I can't install the new beta on Ubuntu 16.04. I get the following error

passwordsafe depends on libqrencode3 (> = 3.4.4-1+b2); But:
Version of libqrencode3: amd64 on this system is 3.4.4-1.

After changing the control file from:

Depends: libc6 (>= 2.7-18lenny4), libuuid1 (>= 1.41.3-1), libwxgtk3.0-0 (>= 3.0.0-2) | libwxgtk3.0-0v5 (>= 3.0.0-2), libxtst6 (>= 2:1.0.3-1), libxerces-c3.1 (>= 3.1.1-1+b1), libykpers-1-1 (>= 1.7.0-1), libqrencode3 (>= 3.4.4-1+b2

to:

Depends: libc6 (>= 2.7-18lenny4), libuuid1 (>= 1.41.3-1), libwxgtk3.0-0 (>= 3.0.0-2) | libwxgtk3.0-0v5 (>= 3.0.0-2), libxtst6 (>= 2:1.0.3-1), libxerces-c3.1 (>= 3.1.1-1+b1), libykpers-1-1 (>= 1.7.0-1), libqrencode3 (>= 3.4.4-1)

Now i can install the new beta after changing this and rebuilding the package.

**Comment by rafaelx** [comment]
I've downloaded "passwordsafe-ubuntu16-1.06.0-BETA.amd64.deb" and checked its dependencies. It depends on "libqrencode3 (>= 3.4.4-1)". Only the Debian package should depend on "libqrencode3 (>= 3.4.4-1+b2)" according to the build script (CMakeLists.txt).

Is it possible that you have used the Debian package instead the one for Ubuntu 16?

**Comment by ronys** [comment]
Closing as obsolete.
If anyone still needs a build for Ubuntu 16, please reopen.
