### ISSUE TITLE
libmagic on Linux

### ISSUE THREAD

**Issue by Safari77** [pwsafe/pwsafe#48]
/usr/bin/file uses libmagic, I believe it would be a better idea to use `magic_file()` (see `man 3 libmagic`) instead of executing `/usr/bin/file`.

**Comment by ronys** [comment]
You're probably right. Care to submit a patch?

**Comment by Safari77** [comment]
I don't have a patch for this, just looking at V4 changes...

**Comment by kluete** [comment]
does it make more sense to handle the mime type in the UI layer? I only see it used from wx-enabled upstream functions where wxMimeTypesManager could be used

**Comment by Safari77** [comment]
wxMimeTypesManager seems to only guess based on file extension on non-Windows?

**Comment by cmaritan** [comment]
Hello everyone, I don't know if it's still needed/useful by I can submit a PR for media.cpp using libmagic.
I'm just crawling pwsafe source code as an hobbist coder but maybe I can help with something else.

Bye.

**Comment by ronys** [comment]
I see you've submitted a PR - thanks! Will discuss it there.
