### ISSUE TITLE
PasswordSafe Linux opens the password database in Read Only mode

### ISSUE THREAD

**Issue by dacianstremtan** [pwsafe/pwsafe#483]
version 1.06 beta for Linux
Couple of issues with this version: 
1. the database opens read only, so I cannot add new entries.
2. The help subsystem cannot initialize

Compiled and running on Gentoo Linux.  Same issue I get if I compile it on CentOS 7.x

**Comment by dskrvk** [comment]
Do you get a message that "Database is locked by ..., opening R/O"? In my case the lock files frequently get left behind on reboot, so I have to remove them manually.

**Comment by dacianstremtan** [comment]
No.  The Read-Only button is not checked.  Also if I go to version 1.02 then I do not get any of the errors mentioned above.

**Comment by dacianstremtan** [comment]
![screenshot from 2018-08-21 14-54-20](https://user-images.githubusercontent.com/35844628/44422817-3337db00-a552-11e8-8cc2-c44ae77323e5.png)
see screenshot.  The blank Warning window (I think it is not sized properly to display the message) it the warning about read-only.

**Comment by dskrvk** [comment]
Before you start pwsafe, check if `${PWSAFE_DIR}/pwsafe.{plk,lck}` exist. The presence of these files forces the db to open as R/O. I believe there's a problem with how these are cleaned up, but haven't had a chance to dig deeper.

**Comment by bblough** [comment]
Did you use autotools or cmake?  Did you do a release build or a debug build?

**Comment by dacianstremtan** [comment]
I used cmake to build it.

**Comment by dacianstremtan** [comment]
the pwsafe.lck is the issue.  After I removed it, the database opened Read-Write.  Thank you.
