### ISSUE TITLE
Linux: Segmentation fault when checking for the latest version

### ISSUE THREAD

**Issue by afita** [pwsafe/pwsafe#50]
How to reproduce:
1. start pwsafe from a terminal (to see the Segmentation fault message)
2. go to Help->About
3. click on "Here" to check for the latest version
4. click "Ok" to confirm the database close
5. Result: the windows close and in the terminal appears "Segmentation fault"

Using: passwordsafe 0.97BETA downloaded from Github on Linux Mint Rosa 17.3 (based on Ubuntu 14.04 LTS).

```
$ aptitude show passwordsafe
Package: passwordsafe                    
State: installed
Automatically installed: no
Version: 0.97BETA
Priority: optional
Section: utils
Maintainer: Rony Shapiro <ronys@users.sf.net>
Architecture: amd64
Uncompressed Size: 5,120 k
Depends: libc6 (>= 2.11.1-0ubuntu7.2), libuuid1 (>= 2.17.2-0ubuntu1), libwxgtk3.0-0 (>= 3.0.0-2), libxtst6 (>= 2:1.1.0-2), libxerces-c3.1 (>= 3.1.0-1), libykpers-1-1
         (>= 1.7.0-1)
Conflicts: pwsafe, pwsafe
Description: Portable version of popular password manager program
[...]
```

**Comment by ronys** [comment]
Yes, this was fixed (ironically) in the last version:

commit 2f26ae78dc98c802d6328c1e1cdf8c018e8bd9db
Author: ronys <ronys@pwsafe.org>
Date:   Fri Oct 9 21:25:36 2015 +0300

    wx: Fail gracefully if wxURL isn't in latest version check

    Root cause is that wxURL doesn't seem to support https.
    Changing "https" to "http" results in a redirect message being returned,
    so currently there's no workaround that will get to the actual XML file.
