### ISSUE TITLE
Linux: "Recent Databases on File Menu" option doesn't work

### ISSUE THREAD

**Issue by afita** [pwsafe/pwsafe#52]
Toggling the option "Recent Databases on File Menu rather than as a
sub-menu" from Manage->Options->System doesn't do anything in
the Linux version. On Windows, when I toggle this option and restart the
process, the Recent Databases list changes between being displayed in a
sub-menu and directly in the File menu.

I'm using Passwordsafe for Linux version 0.97BETA.

Confirmed by another person on the forum: https://sourceforge.net/p/passwordsafe/discussion/134801/thread/423341de/.

**Comment by ronys** [comment]
Fixed in commits 06bfd2e and af35f7b. Also moved the file list (or its submenu) to be above the Clear Recent Entries menuitem, instead of at the bottom of the File menu.

Like Windows, the application has to be restarted for the change in the preference to take effect.
