### ISSUE TITLE
Missing signatures for the source tarball

### ISSUE THREAD

**Issue by namarrgon** [pwsafe/pwsafe#521]
I'm sorry to have to open another one of these but could you please add the signatures to the release routine when you publish new releases?
I understand that it is tedious since it is apparently a manual process but passwordsafe is a security-related application and the chain of trust is important.
A viable alternative would be to sign the git commits but that takes a certain amount of work and discipline as well.

**Comment by ronys** [comment]
Thanks for the reminder.
Problem is that github creates the source tarballs for each release. I have to download these, unzip, compare to the sources I have, sign, and upload the sig file.
Any suggestion as to how to automate this would be greatly appreciated...
