### ISSUE TITLE
Some pwsafe dialogs are unreadable in OSX Mohave's Dark Mode

### ISSUE THREAD

**Issue by sauravg** [pwsafe/pwsafe#531]
See the attached screenshot

![screenshot 2019-02-18 at 12 04 14 pm](https://user-images.githubusercontent.com/8086899/52932350-6c240180-3375-11e9-867a-7ab998e3945b.png)

The Compare & Generate Password dialogs also Lok that way. the others look fine, even if they don't confirm with the "Dark Mode" looks.

**Comment by ronys** [comment]
Odd. Wouldn't this be a wx issue?

**Comment by sauravg** [comment]
Don't think so. If it was a wx issue, it would affect all windows. There
are other dialogs that look fine, and some are even dark, having the native
dark mode look.

For the ones that don't look ok, may be we are forcing a background color
or something.

**Comment by rafaelx** [comment]
Might be related to [18146](https://trac.wxwidgets.org/ticket/18146).

**Comment by ronys** [comment]
Yep, looks relevant. Nice to see wx is still being maintained.

**Comment by KaiZin2018** [comment]
Running with version 3.1.3 or newer wxWidgets will support dark mode. Actual pwSafe code is supporting the dark mode as well.
