### ISSUE TITLE
File encryption doesn't seem to work

### ISSUE THREAD

**Issue by pepa65** [pwsafe/pwsafe#532]
Unless I am misunderstanding, `pwsafe -e FILE` should encrypt the file `FILE`, but instead GUI is trying to use `FILE` as a password-store.

**Comment by ronys** [comment]
I'm afraid you misunderstood.

**Comment by pepa65** [comment]
So what is supposed to happen when you enter `pwsafe -e FILE`? Or are the commandline options no longer functional??

**Comment by ronys** [comment]
After prompting for the password (and confirmation), a file FILE.PSF is created which is the encrypted version of FILE.
Deletion of the original file is the user's responsibility.
To decrypt, specify '-d' and FILE.PSF

**Comment by pepa65** [comment]
Well, that is not happening in version 1.07 beta. Like I said, when I do `pwsafe -e FILE`, there is no prompt for passwords, but the normal window comes up asking to Open the Password Database, and FILE is filled into the top box where normally the PasswordSafe Database is filled in.

**Comment by ronys** [comment]
Aha. I should have asked what version/platform you're running.

**Comment by pepa65** [comment]
Sorry, I should not have assumed all are the same... This is from passwordsafe-ubuntu18-1.07.0-BETA.amd64.deb

**Comment by rafaelx** [comment]
File encryption and decryption is not implemented, yet.
I think that I have already seen a bug report regarding this issue, but cannot find it anymore.

**Comment by rafaelx** [comment]
Got it! This issue was mentioned in the [discussion](https://sourceforge.net/p/passwordsafe/discussion/134800/thread/5d5ce118/) forum at Source Forge, but no bug report was created so far. - So, thanks for creating one.
