### ISSUE TITLE
[Linux] v1.06 not detecting Yubikey

### ISSUE THREAD

**Issue by r4nd0m123** [pwsafe/pwsafe#540]
Hi,

I've recently purchased a new laptop which is running a Debian derivative. I've installed PasswordSafe through apt-get and the application no longer detects my Yubikey.

Kernel version
`4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64 GNU/Linux`

PasswordSafe version
`v1.06 BETA Sep 16 2018`

dmesg
```
[ 2357.455755] usb 1-2: new full-speed USB device number 14 using xhci_hcd
[ 2357.605199] usb 1-2: New USB device found, idVendor=1050, idProduct=0110, bcdDevice= 3.18
[ 2357.605209] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 2357.605215] usb 1-2: Product: Yubikey NEO OTP
[ 2357.605221] usb 1-2: Manufacturer: Yubico
[ 2357.610513] input: Yubico Yubikey NEO OTP as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:1050:0110.0009/input/input27
[ 2357.668116] hid-generic 0003:1050:0110.0009: input,hidraw0: USB HID v1.10 Keyboard [Yubico Yubikey NEO OTP] on usb-0000:00:14.0-2/input0
```

Does anyone know what I could be doing wrong?
Thanks

**Comment by bblough** [comment]
I haven't been able to reproduce the issue on Debian 9 with 1.06 backported from Debian 10.  I haven't tried to reproduce it under Debian 10 proper, yet.

Which distro is it that you're running?  I could spin up a VM and see if I can reproduce it that way.

Also, as a data point, have you tried (or can you try) on of the debs from the releases section here on github? That could at least help us identify if it's an issue with the code, or an issue with the Debian packaging or downstream distribution.

**Comment by r4nd0m123** [comment]
I'm using PureOS.

I tried the Debian version but encountered dependency issues. I installed the 1.07 Ubuntu 18.04 version and it still isn't detecting my Yubikey NEO.

Any ideas or further information I could provide that could be of use to you?

**Comment by bblough** [comment]
I'm able to reproduce this running PureOS in a VM.  I'm not 100% certain that USB passthrough is working like it should, but it will still let me do some investigation while I try to scrounge up some functional hardware to test it on.

**Comment by r4nd0m123** [comment]
I wonder if this issue is related to a libyubikey0 update?

https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1670577.html

**Comment by bblough** [comment]
That would be consistent with my testing so far.  Once the fix is uploaded to Debian (which should be soon) I'll test it.  I don't know what the process is for getting the update into PureOS, though.

**Comment by bblough** [comment]
Just to follow up on this - the fix for this went into the buster version of yubikey-personalization (1.19.3-3), and it's now behaving correctly, based on my testing.  It also looks like PureOS has imported this version into their repo, so this should hopefully be fixed for you.

**Comment by r4nd0m123** [comment]
Thanks @bblough! It is detecting Yubikeys again.
