### ISSUE TITLE
Linux rpm package is missing xvkbd dependency

### ISSUE THREAD

**Issue by ykne** [pwsafe/pwsafe#544]
However even after installing xvkbd package on screen keyboard key clicks don't seem to enter anything in safe combination field.

**Comment by rafaelx** [comment]
If I start the virtual keyboard I have first to click into one of the text entry fields to give the dialog the focus back. Once done, it behaves as expected.

**Comment by ronys** [comment]
Fixed in commit 997002a - added xvkbd as suggested rpm package.
