### ISSUE TITLE
menu item to unlock DB

### ISSUE THREAD

**Issue by bryan-p** [pwsafe/pwsafe#549]
Could a menu option be added to allow to unlock DB when locked on the linux version, or even just a keyboard shortcut?  I see issue #451 added this when the sys tray icon was not available but I could see this being useful in other cases as well (such as my case when using a tiling wm). So perhaps good idea to always have it available when DB is locked.

**Comment by rafaelx** [comment]
Isn't the behavior such that when the database gets locked the application is automatically minimized? In this case, the menu item couldn't be reached from the applications main window for unlocking. However, an unlock would be still possible from the applications menu from the system tray, if the window manager supports it.

**Comment by bryan-p** [comment]
In my case I'm using i3 window manager, which is a tiling wm and there isn't really a concept of minimizing.  So in my situation the window is always there in whichever layout I have configured.  Also it does not pop up the dialog to unlock the db, so I"m having to ctrl-w, ctrl-o to close then open the db.  So maybe this is a corner case and not worth implementing but I don't see an issue with adding an extra menu item, or just shortcut to unlock the db. Really the keyboard shortcut is what I'm after, my goal is always less or no mouse use.
