### ISSUE TITLE
v3.49 Command Options for -s not working on Windows 10 

### ISSUE THREAD

**Issue by mrjackwills** [pwsafe/pwsafe#550]
I have been using the -s feature, so that when windows 10 first loads, pwsafe loads the db to the taskbar, meaning I can double click, then enter password, whenever it is needed, without having to locate and load the db file. 

This is done with the following line in a shortcut in my Windows 10 startup start menu folder

"C:\Program Files (x86)\Password Safe\pwsafe.exe" -s "C:\safe\location\db.psafe3"

However, starting with version 3.40 the -s flag no longer has any effect, and pwsafe window will always open up with what appears to be no db loaded. However, closing this windows, and then double clicking the taskbar icon will make the password entry window appear, and after which everything is back to normal

thanks

**Comment by rafaelx** [comment]
Related with #359

**Comment by ronys** [comment]
Fixed in commit d8923b5a5, will be in next release.
