### ISSUE TITLE
MINT 19.1 Pwsafe requires libcurl3 but 4 is installed

### ISSUE THREAD

**Issue by IanBlakeley** [pwsafe/pwsafe#551]
Linux MINT 19.1

After installing virtualbox 6 libcurl3 gets replaced by libcurl4, this breaks pwsafe. If I reinstall libcurl3 `apt install libcurl3 libcurl-openssl1.0-dev` then libcurl4 is removed along with virtualbox cannot have both versions of libcurl installed at the sametime.

**Comment by dskrvk** [comment]
I faced the same issue on Ubuntu 18.04 and fixed it by changing the
dependency to libcurl4 and recompiling. I can submit a pull request.

**Comment by ronys** [comment]
Fixed in commit fdf4298ae.

Will be in 1.08.1

**Comment by ronys** [comment]
1.08.1 released with .deb for Mint 19.1

**Comment by wickedsp1d3r** [comment]
Could you make this change also to Debian builds? Debian 10 (Buster) just released and this issue exists.

**Comment by ronys** [comment]
Done. 1.08.2 just released with 64 bit Debian 10 support.
