### ISSUE TITLE
Intermittently unable to restore minimised safe / or if open cannot read [Linux MINT]

### ISSUE THREAD

**Issue by IanBlakeley** [pwsafe/pwsafe#559]
I've been seeing this issue intermittently for the last few versions and on both Mint 18 and Mint 19. Very occasionally it is not possible to open / close or restore a minimised safe or if it is open then cannot close or read any of the entries. I am unsure what triggers this, is there any log or data I can retrieve when this happens that would assist in finding the issue?

For information I usually have 2 instances running, one is local only with a simpler password the other is synced to currently OneDrive with a more complex password stored in the first instance. The issue seems to effect either instance, I have only ever had one freeze never so far both at the same time.

**Comment by bblough** [comment]
I've had this happen as well.  I'm still trying to find a way to reliably reproduce it.

**Comment by IanBlakeley** [comment]
Happening a lot more on the safe with more entries, don't know if that is a clue or not, also has a longer password

**Comment by IanBlakeley** [comment]
Still seeing this, had both instances freeze yesterday. Cannot reliably reproduce

**Comment by IanBlakeley** [comment]
Can confirm problem persists in the latest version 



![image](https://user-images.githubusercontent.com/36182904/72658446-1d9b3f00-39ec-11ea-85a7-24bc736cdf72.png)

**Comment by IanBlakeley** [comment]
Sill occurs on 1.10, twice today so far

**Comment by IanBlakeley** [comment]
Been a while an now idea what the trigger might be but now seen on 1.11 too. It has been a number of weeks since I last saw it.

**Comment by IanBlakeley** [comment]
Recently upgraded to MINT 20, still seeing this

**Comment by boscorama** [comment]
The easiest way to reproduce this (at least on KDE) seems to be to leave the 'Edit Entry' window open when the app auto-locks and minimizes to the systray.

It _appears_ that the modal dialog retains focus even though it never comes back from the minimize.  In fact I can't even locate the dialog window in any way (xwininfo or wmctrl).  The only recourse is to kill the app.

Kubuntu: 18.04.x LTS, 20.04.x LTS
PasswordSafe: v1.10, v1.11, v1.12

**Comment by IanBlakeley** [comment]
> The easiest way to reproduce this (at least on KDE) seems to be to leave the 'Edit Entry' window open when the app auto-locks and minimizes to the systray.
> 
> It _appears_ that the modal dialog retains focus even though it never comes back from the minimize. In fact I can't even locate the dialog window in any way (xwininfo or wmctrl). The only recourse is to kill the app.
> 
> Kubuntu: 18.04.x LTS, 20.04.x LTS
> PasswordSafe: v1.10, v1.11, v1.12

Confirmed in MINT20 PWSafe V1.12 that the steps referenced do give rise to the problem as detailed. Not sure this is 100% what always happens as I think it has happened on occasions when I have not access the app other than to open the safe first thing.

**Comment by IanBlakeley** [comment]
Can confirm with 1.15 I no longer have this issue.
