### ISSUE TITLE
__time64_t and 32bit platform

### ISSUE THREAD

**Issue by yopito** [pwsafe/pwsafe#563]
while packaging passwordsafe 1.08.1BETA, build fails for 32bit platform.

Context: VoidlLinux distribution with gcc 9.1 and glibc 2.29 or musl libc 1.1.22

Example of fail build: https://travis-ci.org/void-linux/void-packages/jobs/535496599e

Offending starts at is https://github.com/pwsafe/pwsafe/blob/master/src/os/unix/pws_time.h#L18 

my points:
* "`__time64_t`" typedef is defined on 32bit platform, even if "`__time64_t`" define statement is not
* fill confused that "`__time64_t`" typedef is defined in `pws_time.h`, that is a structure defined in libc headers (see [1])
* libc header (see [1]) also states that "`__time64_t`" is always a 64bit type (via `__TIME64_T_TYPE`)

Fixed myself build via replacing L18 with 
```#if !defined(__time64_t) && !defined(__TIME64_T_TYPE)```
It's working, but I'm not sure this is the right way to fix it

So `pws_time.h` should not redefine `__time64_t` or use another name for that ?  
I'm not enough fluent in C/C++ to propose a good patch, sorry.

[1] Gnu libc `include/bits/time64.h` states:
```
26  /* Define __TIME64_T_TYPE so that it is always a 64-bit type.  */
27
28  #if __TIMESIZE == 64
29  /* If we already have 64-bit time type then use it.  */
30  # define __TIME64_T_TYPE                __TIME_T_TYPE
31  #else
32  /* Define a 64-bit time type alongsize the 32-bit one.  */
33  # define __TIME64_T_TYPE                __SQUAD_TYPE
34  #endif
35
36  #endif /* bits/time64.h */
```

**Comment by ronys** [comment]
Fixed in commit 497246d. I took your fix, and removed the unused __time32_t typedef.

It's not that pwsafe is redefining __time64_t, but rather defining it for environments where it's missing, making the rest of the code more consistent.

**Comment by yopito** [comment]
cool, quick response.
FYI, with your fix, build with various arch and libc combinations is fine (voidlinux).  
See https://travis-ci.org/void-linux/void-packages/builds/554874381 for instance

**Comment by ronys** [comment]
Nice. Interesting to see builds for ARM as well.

Care to submit a pull request to integrate voidlinux support into the main repo?

**Comment by yopito** [comment]
Thanks for your interrest to VoidLinux, but I don't well understand how it could be achieved in pwsafe context: specific entry in CmakeList.txt ? Voidlinux as travis target ?

**Comment by ronys** [comment]
- Well, if you made any changes to the source code besides the fix we've discussed, that would be of interest.
- If cmake supports voidlinux packages, then changes to CmakeList.txt would be relevant
- If the voidlinux package can be built by a script on a voidlinux system, then that script can be added under the install directory in the project repo.
- Adding voidlinux to the existing travis.yml file would also be useful, I think.

**Comment by yopito** [comment]
sorry for late reply. It feels difficult to answer you clearly, so here my points.

VoidLinux distributes passwordsafe as an official package:
* source packaging is here: https://github.com/void-linux/void-packages/tree/master/srcpkgs/passwordsafe/
* Currently, there are minor changes against passwordsafe source code to achieve packaging (see "`template`" file). There will be even less changes in next version.
* Currently in version 1.07BETA, but a PR is opened to update in 1.08.1BETA:  
    https://github.com/void-linux/void-packages/pull/11854/  
    This one contains the patch you wrote about the current PR

To achieve packaging, VoidLinux uses a integrated tree that contains both the source packaging definition of all packages and the shell build utility and its helpers (`xbps-src`).  
So:
* The packaging of a given application has to be maintained in that tree
* I could provide you a copy of the templating file for passwordsafe, but it sounds a bit useless since `template` directives heavily rely on the build ecosystem that is constantly evolving (this is a rolling distribution). Difficult to maintain ?
* Travis does not offer a VoidLinux image. VoidLinux uses travis on top of Ubuntu image with a static package manager and retrieve the combined tree to launch test packaging. Official build is achieved on dedicated systems of the project. So using VoidLinux as a QA target for passwordsafe can be tricky ?

Anyway, I will be glad to help you on any of these points if you want to move on.

**Comment by ronys** [comment]
Thanks for clarifying. Based on your explanation, I don't see any real value in adding voidlinux specifics to the main passwordsafe repo.
