### ISSUE TITLE
Implement Mandatory Integrity Control for Windows

### ISSUE THREAD

**Issue by agyild** [pwsafe/pwsafe#566]
A higher integrity process should make code injection or memory scanning attempts harder for unauthorized processes. It is a feature available on Windows Vista and later and since Password Safe is for Windows 7 and later it should be compatible. More information can be found [here](https://docs.microsoft.com/en-us/windows/win32/secauthz/mandatory-integrity-control) and [here](https://securityinternals.blogspot.com/2014/01/windows-integrity-checks-mandatory.html). In addition higher integrity password safe files are also open to debate.

Edit: As a side bonus it should also make it possible to drop pwsafe objects (username, password etc.) on higher integrity windows.

**Comment by agyild** [comment]
Currently it is possible to run pwsafe.exe with high integrity level by setting its integrity level to high (i.e. `icacls pwsafe.exe /setintegritylevel H`) and running it as administrator. Although the latter step makes the former unnecessary since elevated programs run with high integrity by default. The only caveat is running the program as an administrator. As secure by default principle, I think pwsafe should run elevated by default and the users should be able to disable it at their own discretion. In addition it requires persistence mechanism to be moved to e.g. task scheduler since the startup folder does not allow running elevated programs.

Password safes also can be set to have higher integrity but then as a side effect e.g. potential cloud synchronization software ran by the user will be affected negatively. I am looking into it, but worst case scenario the user has to configure the file ACLs at their own discretion if there is no out-of-the-box working solution.

**Comment by ronys** [comment]
Is this still relevant under Windows 10/11?
If so, let's discuss.
