### ISSUE TITLE
Window on top option gets disabled

### ISSUE THREAD

**Issue by agyild** [pwsafe/pwsafe#573]
I cannot pinpoint the exact reason of the bug. But after I autotype with `CTRL + T` and especially after an unsuccessful autotype attempt "Always keep Password Safe on top" option gets disabled internally even though the option itself is checked. In order to reactivate on top mechanism one needs to reenable the option in the settings by unchecking and rechecking it. I propose inspecting the on top option whenever the window is in the background ([with window messages](https://docs.microsoft.com/en-us/windows/win32/winmsg/messages-and-message-queues)) and force enabling it again if the option is actually checked in the settings.

**Comment by ronys** [comment]
- What version of Windows are you using?
- What version of PasswordSafe?
- 32 or 64 bit?
- What values are you using for the following:
-- Misc->Minimize after Autotype
-- Security->Lock password database on minimize
-- System->Put icon in System Tray

**Comment by agyild** [comment]
>- What version of Windows are you using?
>- What version of PasswordSafe?
>- 32 or 64 bit?
>- What values are you using for the following:
>Misc->Minimize after Autotype
>Security->Lock password database on minimize
>System->Put icon in System Tray

- 10.0.18362 (1903)
- 3.49.01
- 64 bit
- True / False / True (From top to bottom)

**Comment by ronys** [comment]
Please check if https://pwsafe.org/tmp/3.56pre/pwsafe64-3.56.0pre.exe resolves this issue.

**Comment by ronys** [comment]
Confirmed, closing.
