### ISSUE TITLE
Right-click drag menu scaling bug

### ISSUE THREAD

**Issue by tovodeverett** [pwsafe/pwsafe#591]
I'm seeing an interesting Windows 10 (1903) scaling bug in Password Safe.  I'm using right-click to drag a password entry from one safe to another (with the intent of selecting "Copy" from the menu so I can copy the entry).  I have the Windows 10 display scaling set to 125% (the "Change the size of text, apps, and other items" setting).

Upon release of the right-click, the pop-menu to select Move, Copy, or Cancel displays, but it is larger than expected and is offset from the mouse position to the lower right (i.e. positive for both vertical and horizontal screen directions relative to the monitor 0,0 coordinate in the upper left corner).  In order to successfully Copy, I ended up moving the destination safe window to the upper left of my monitor to minimize the offset and make it easier to aim at the menu (since the mouse pointer was offset from the actual menu highlighting).

I'm seeing the bug under 3.49.1, but I see nothing in the change log to suggest the issue is resolved in 3.50.  I am running 64-bit Password Safe.  Let me know if you have any issue reproducing in 3.50 and I'll upgrade and retest.

**Comment by ronys** [comment]
This may be related to the 4K monitor display issue resolved in 4.50. In any case, I couldn't reproduce this using 4.50 on my Windows 10 machine. Please upgrade and retest.

**Comment by tovodeverett** [comment]
I should have upgraded before reporting!  I suspect the 4K monitor display issue resolved this as well.  Sorry for wasting your time.
