### ISSUE TITLE
please update README.LINUX.DEVELOPERS.md

### ISSUE THREAD

**Issue by ykne** [pwsafe/pwsafe#596]
1. Issue #543 was closed long time ago but `pwsafe/Misc/mock-build.sh` is not mentioned in `README.LINUX.DEVELOPERS.md`
2. `README.LINUX.DEVELOPERS.md` modified to add `file-devel` but `pwsafe/Misc/mock-build.sh` is not.

**Comment by ronys** [comment]
Thanks for the reminder - Fixed in commit 0dc67a299
