### ISSUE TITLE
Cannot install in Fedora 31 due to missing libqrencode.so.3

### ISSUE THREAD

**Issue by aevernon** [pwsafe/pwsafe#597]
```
$ sudo dnf install -y passwordsafe-fedora30-1.08.0-BETA.amd64.rpm
Last metadata expiration check: 0:13:45 ago on Tue 29 Oct 2019 01:30:07 PM EDT.
Error: 
 Problem: conflicting requests
  - nothing provides libqrencode.so.3()(64bit) needed by passwordsafe-1.8.0_BETA-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

Fedora 31 comes with package `qrencode-libs` version 4.0.2. Systemd depends on version 4 of this library, so it cannot be downgraded.

**Comment by aevernon** [comment]
For anyone else with this problem, here is a workaround until it is fixed:

1. Download the RPM for Password Safe from [here](https://github.com/pwsafe/pwsafe/releases/download/1.08BETA/passwordsafe-fedora30-1.08.0-BETA.amd64.rpm).
1. Download `qrencode-libs-3.4.4-8.fc30.x86_64.rpm` from [here](http://rpm.pbone.net/index.php3/stat/4/idpl/56946620/dir/fedora_other/com/qrencode-libs-3.4.4-8.fc30.x86_64.rpm.html).
1. Extract the RPM  by navigating to it in Files, right-clicking it, and choosing "Extract Here".
1. Inside the directory where you extracted the RPM, move the shared libraries with this command: `sudo mv usr/lib64/* /usr/lib/64`.
1. Install the Password Safe package with this command: `sudo rpm -i --nodeps passwordsafe-fedora30-1.08.0-BETA.amd64.rpm`.

**Comment by rafaelx** [comment]
Related to issue [1499](https://sourceforge.net/p/passwordsafe/bugs/1499/) on SourceForge.

**Comment by ronys** [comment]
Please try https://github.com/pwsafe/pwsafe/releases/download/1.08.2BETA/passwordsafe-fedora31-1.08.2-BETA-amd64.rpm which was built on a Fedora 31 VM.

**Comment by aevernon** [comment]
It works for me. Thank you.
