### ISSUE TITLE
Please add signatures for Linux releases on Github

### ISSUE THREAD

**Issue by bblough** [pwsafe/pwsafe#6]
On the old sourceforge site, PGP signatures were included for all releases, including Linux source tarballs.  While the releases have made it over to Github (thanks!) the signatures have not, which can break automated verification of the source downloads.

**Comment by ronys** [comment]
This will take some effort, as github, unlike SF, generates the source gz/zip files automatically, meaning that I'll have to download, verify, sign and upload sig. Doable, but not trivial.
