### ISSUE TITLE
Issues building 1.08.2BETA for Mac

### ISSUE THREAD

**Issue by tinker2much** [pwsafe/pwsafe#600]
I'm new to this project, bear with me. I got through all of the steps in the Mac Developers document just fine, up to the actual build in Xcode. Then I got this:

Ld /Users/peter/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-gbkqalrqmaevghepawoxmagztzem/Build/Products/Release/pwsafe.app/Contents/MacOS/pwsafe normal x86_64 (in target 'pwsafe' from project 'pwsafe-xcode6')
    cd /Users/peter/Documents/pwsafe-1.08.2BETA/Xcode
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-macos10.7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/peter/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-gbkqalrqmaevghepawoxmagztzem/Build/Products/Release -F/Users/peter/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-gbkqalrqmaevghepawoxmagztzem/Build/Products/Release -filelist /Users/peter/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-gbkqalrqmaevghepawoxmagztzem/Build/Intermediates.noindex/pwsafe-xcode6.build/Release/pwsafe.build/Objects-normal/x86_64/pwsafe.LinkFileList -Xlinker -object_path_lto -Xlinker /Users/peter/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-gbkqalrqmaevghepawoxmagztzem/Build/Intermediates.noindex/pwsafe-xcode6.build/Release/pwsafe.build/Objects-normal/x86_64/pwsafe_lto.o -stdlib=libc++ -L/usr/local/lib -L/Users/peter/Documents/wxWidgets-3.0.4/static-release/lib /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_xrc-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_qa-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_baseu_net-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_html-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_adv-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_core-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_baseu_xml-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_baseu-3.0.a -lpng -ljpeg -ltiff -lexpat -lwxregexu-3.0 -lz -lpthread -liconv -lcurl -lcore -los -framework Carbon -framework OpenGL -framework Cocoa -framework IOKit -framework QuartzCore -Xlinker -dependency_info -Xlinker /Users/peter/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-gbkqalrqmaevghepawoxmagztzem/Build/Intermediates.noindex/pwsafe-xcode6.build/Release/pwsafe.build/Objects-normal/x86_64/pwsafe_dependency_info.dat -o /Users/peter/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-gbkqalrqmaevghepawoxmagztzem/Build/Products/Release/pwsafe.app/Contents/MacOS/pwsafe

Undefined symbols for architecture x86_64:
  "CryptKeyEntry::CryptKeyEntry(CryptKeyEntry::Mode)", referenced from:
      PwsafeApp::OnInit()::$_0::operator()(CryptKeyEntry::Mode, std::__1::function<bool (std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, S_Alloc::SecureAlloc<wchar_t> > const&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >&)>) const in pwsafeapp.o
  "CryptKeyEntry::~CryptKeyEntry()", referenced from:
      PwsafeApp::OnInit()::$_0::operator()(CryptKeyEntry::Mode, std::__1::function<bool (std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, S_Alloc::SecureAlloc<wchar_t> > const&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >&)>) const in pwsafeapp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any suggestions what I should do? My only thought so far is to try the latest from git instead.

**Comment by ronys** [comment]
Hm,

There's been some refactoring of the code, and it looks like the Mac Xcode hasn't been updated accordingly. I'd start with the current master on git, and update Xcode as needed. I'll be glad to help hunt down link errors, if needed.

**Comment by tinker2much** [comment]
Regarding versions of things: 

I have just cloned the pwsafe master.

I had previously chosen to download and build the *stable* version of wxWidgets. Do think I need their latest too?

I'm doing this on MacOS Catalina, and I currently have Xcode 11.1. The App store is offering to update me to 11.2 as we speak; may I skip that for now? I have a slow connection and the 7.8 gigabytes would take 4 hours.

In any case, I'll go ahead and see how I do with what I have on hand.

**Comment by ronys** [comment]
I'm unaware of any bugs or limitations of the stable wx on Mac that justify upgrading to the latest. Likewise for Xcode.

**Comment by tinker2much** [comment]
It fails right away, saying that "os/typedefs.h" file not found. 

I must have something really fundamental wrongly configured to get that error. The file clearly exists. 

Here is the debug config I generated:

`OTHER_LDFLAGS = -L/usr/local/lib -L/Users/peter/Documents/wxWidgets-3.0.4/static-debug/lib /Users/peter/Documents/wxWidgets-3.0.4/static-debug/lib/libwx_osx_cocoau_xrc-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-debug/lib/libwx_osx_cocoau_qa-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-debug/lib/libwx_baseu_net-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-debug/lib/libwx_osx_cocoau_html-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-debug/lib/libwx_osx_cocoau_adv-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-debug/lib/libwx_osx_cocoau_core-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-debug/lib/libwx_baseu_xml-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-debug/lib/libwx_baseu-3.0.a -lpng -ljpeg -ltiff -lexpat -lwxregexu-3.0 -lz -lpthread -liconv 
HEADER_SEARCH_PATHS = /Users/peter/Documents/wxWidgets-3.0.4/static-debug/lib/wx/include/osx_cocoa-unicode-static-3.0 /Users/peter/Documents/wxWidgets-3.0.4/include `

Here is the release config I generated:

`OTHER_LDFLAGS = -L/usr/local/lib -L/Users/peter/Documents/wxWidgets-3.0.4/static-release/lib /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_xrc-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_qa-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_baseu_net-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_html-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_adv-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_core-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_baseu_xml-3.0.a /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_baseu-3.0.a -lpng -ljpeg -ltiff -lexpat -lwxregexu-3.0 -lz -lpthread -liconv 
HEADER_SEARCH_PATHS = /Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/wx/include/osx_cocoa-unicode-static-3.0 /Users/peter/Documents/wxWidgets-3.0.4/include `

**Comment by ronys** [comment]
This is a compile-time, not link-time error.
It means that for some reason the 'src' directory isn't in the search path for include files. In other words, "-I .../pwsafe/src" is missing from the compilation flags.

**Comment by rafaelx** [comment]
When doing the refactoring I've noticed that some files were missing in the XCode configuration/project file so I created issue #590.

**Comment by tinker2much** [comment]
Would it be too much of a kludge to just add that -I to the HEADER_SEARCH_PATHS string in the generated configs? I'm guessing that it really belongs somewhere else?

**Comment by tinker2much** [comment]
Doesn't work anyway - a kludge that doesn't even work is a doubly bad idea
 ;-)

**Comment by tinker2much** [comment]
I'm just rooting around, doing manual diffs (not git diffs) between various files in the 1.08.2BETA and master and noted this:

`< CPPFLAGS := $(CXXFLAGS) -fPIC -Wall -I.. $(CPPFLAGS)
---
> CPPFLAGS := $(CXXFLAGS) -fPIC -Wall -I. -I.. -I../.. $(CPPFLAGS)
108c110`

**Comment by tinker2much** [comment]
try that again...

```
< CPPFLAGS := $(CXXFLAGS) -fPIC -Wall -I.. $(CPPFLAGS)
---
> CPPFLAGS := $(CXXFLAGS) -fPIC -Wall -I. -I.. -I../.. $(CPPFLAGS)
108c110

```

**Comment by ronys** [comment]
This could be a reasonable diff if the Makefiles are on different levels in the source tree.

**Comment by tinker2much** [comment]
I've no experience with Xcode, but you tell me what to do and I'll follow your instructions. But which path to follow? The original BETA path where a lot seemed to work and there were a few link errors, or the master path which is the future, but which has apparently been through a lot of refactoring and renaming of files, and which unexpectedly fails on a simple include?

My reasons for pursuing this: I had always used Password Safe on Windows. When I gave up on Windows and switched to Macs, I ran Password Safe under Wine, but now Wine and Password Safe don't work on Mac OS Catalina now that it's disallowed 32-bit apps. I think my only avenue on this machine, under this OS, is to build Password Safe natively. 

Note: I'm still happily using pwsafe under wine on another mac running High Sierra, and on an ex-Chromebook with an Intel chip running Debian. I'm also happily using the Linux version of pwsafe, that I easily compiled myself, on a Raspberry Pi with an arm chip running Raspbian, a flavor of Debian.

**Comment by rafaelx** [comment]
During the first step, the file renaming, the content of .../Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj was also updated, which lists all source files. In the second step some class names were changed.
The error message from your initial post points to "PwsafeApp::OnInit()" which is in the latest version on the master branch "PWSafeApp::OnInit()". Additionally, the error message also points to "CryptKeyEntry" which was renamed to "CryptKeyEntryDlg". As described by #590, an entry for "CryptKeyEntryDlg" seems to be missing in the Xcode project file. The dialog "CryptKeyEntryDlg" was added on 15th of October, so it might be that the Xcode settings hasn't been updated by a Mac user/developer.
Have you already fixed the problem with "CryptKeyEntryDlg" and the remaining problem now is "os / typedefs.h"?

**Comment by tinker2much** [comment]
To clarify and recap: There are two cases here: 
1) When I tried using the source form the last BETA release, I got link errors for CryptKey stuff. 
2) When I tried the latest code on the master branch, I got errors about finding header files. 

Questions - are there particular developers/maintainers that are responsible for the Mac builds? Is there anyone for whom the Mac is actually their main development platform? 

It would be more efficient for such an actual expert to get to a working Mac build and then update the instructions if necessary, but I want this enough that I'm willing to fumble around myself or take suggestions from anyone having more knowledge about Xcode or more experience on this project than I have (which would be most anybody). I have a lot of experience developing command-line or batch applications in C under Linux using gcc, very little GUI experience anywhere, and no experience using Xcode. But I'm willing to learn and I know my way around the command line.

**Comment by tinker2much** [comment]
... and I apologize for the intermittency of my replies, more like postal chess than internet speed. I'm still interested.

**Comment by tinker2much** [comment]
... and FWIW, I have updated to Xcode 11.2 from 11.1 since last trying either case (BETA or master). 
This is on MAcOS Catalina 10.15.1.

**Comment by tinker2much** [comment]
@rafaelx : Regarding my case 1 (BETA), where I'm having trouble with CryptKeyEntry in the link. 

Here's something I noticed - the Makefile at /Users/peter/Documents/pwsafe-1.08.2BETA/src/ui/wxWidgets/Makefile says "Makefile generated by DialogBlocks" but it had what may have been a hand-added line for CryptKeyEntry.cpp that wasn't indented with tabs like all the other lines. I hand changed that line to indent using a tab (which I seem to remember is required in makefiles.) I tried to rebuild the project but still got the same link failure. DO I need to change this upstream, so that  DialogBLocks will generate the Makefile with the tab, or do I need to make some change to Xcode project settings to get this file built?

**Comment by ronys** [comment]
Right. I've forwarded this ticket to the person who wrote the original OSX port of PasswordSafe. He's been quiet lately, but hopefully he'll be able to help you.

**Comment by ronys** [comment]
- DialogBlocks was used to generate the original Linux UI project and Makefiles, but is no longer updated.
- In general tabs v.s. spaces is significant for Makefiles, but not in this case, as the preceding line ends with '\' .
A link error means a missing object file or library...
Did you try generating the Xcode project using cmake?

**Comment by tinker2much** [comment]
First, I installed cmake using homebrew, I got version cmake-3.15.5.catalina.

Then, to use it, I gleaned tips from [here](https://stackoverflow.com/questions/16700415/cmake-generate-xcode-project-from-existing-sources#16701018) and then fiddled a bit to fit this project, which resulted in the following: 

```
peter@Peters-Mac-mini pwsafe-1.08.2BETA % mkdir build; cd build; cmake -G Xcode ..
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- The C compiler identification is AppleClang 11.0.0.11000033
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found UnixCommands: /bin/bash  
-- Failed to find 'wx-config' executable:
   Tip: can be pointed from command-line this way:
        $ cmake -D wxWidgets_CONFIG_EXECUTABLE=/path/to/wx-config .
CMake Error at /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindwxWidgets.cmake:990 (find_package_handle_standard_args)
  CMakeLists.txt:135 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/peter/Documents/pwsafe-1.08.2BETA/build/CMakeFiles/CMakeOutput.log".

```
So I followed their tip and pointed make to the wx-config executable, which I guessed was in the wxWidgets project, and I pointed to the release version as noted below:

```
peter@Peters-Mac-mini build % cmake -D wxWidgets_CONFIG_EXECUTABLE=/Users/peter/Documents/wxWidgets-3.0.4/static-release/wx-config -G Xcode ..
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- The C compiler identification is AppleClang 11.0.0.11000033
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found UnixCommands: /bin/bash  
-- Failed to find 'wx-config' executable:
   Tip: can be pointed from command-line this way:
        $ cmake -D wxWidgets_CONFIG_EXECUTABLE=/path/to/wx-config .
-- Found wxWidgets: -L/Users/peter/Documents/wxWidgets-3.0.4/static-release/lib;;;-framework IOKit;-framework Carbon;-framework Cocoa;-framework AudioToolbox;-framework System;-framework OpenGL;/Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_baseu_net-3.0.a;/Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_html-3.0.a;/Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_adv-3.0.a;/Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_core-3.0.a;/Users/peter/Documents/wxWidgets-3.0.4/static-release/lib/libwx_baseu-3.0.a;-lpng;-ljpeg;-ltiff;-lwxregexu-3.0;-lz;-lpthread;-liconv (found version "3.0.4") 
CMake Error at /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindOpenSSL.cmake:413 (find_package_handle_standard_args)
  CMakeLists.txt:138 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/peter/Documents/pwsafe-1.08.2BETA/build/CMakeFiles/CMakeOutput.log".

```

OK, a few steps forward. I'll try to find OPENSSL later this evening.

**Comment by tinker2much** [comment]
I found openssl as already installed by homebrew. 

I did this and the cake process seemed to work:

`OPENSSL_ROOT_DIR=/usr/local/opt/openssl cmake -D wxWidgets_CONFIG_EXECUTABLE=/Users/peter/Documents/wxWidgets-3.0.4/static-release/wx-config -G Xcode ..
`

So, what next?

**Comment by tinker2much** [comment]
of course, that was "the cmake process". What use is spelling correction on a code site?

**Comment by tinker2much** [comment]
I saved the original Xcode project directory, and copied the newly created Xcode project directory over. 

I chose to build "pwsafe" and it failed : unable to find xercesc/util/XercesDefs.hpp.

Do I need to separately obtain xercesc?

**Comment by tinker2much** [comment]
I see that xerces-c is available through homebrew...

**Comment by ronys** [comment]
Note that the Mac build maintainer just submitted some fixes to the Xcode project. You might want to pull the master branch and try that.

**Comment by tinker2much** [comment]
I git cloned the latest pwsafe code from [pwsafe](https://github.com/pwsafe/pwsafe.git), per the doc "README.MAC.DEVELOPERS.txt", point 2. "GET PASSWORDSAFESOURCES".
I had previously downloaded and built the latest STABLE release of wxWidgets from [wxWidgets](https://www.wxwidgets.org/downloads/), which was v3.04, per point 3. "wxWidgets".
I generated  configs again, per point 3.4 "Point Xcode to your Xcode build".
Following Point 4. "Building pwsafe". I pointed Xcode to the pwsafe project file and it began "indexing". 

It chugged for just a short while, then I got the error "os/typedefs.h file not found" in core/StringX.h.

NOTE: 
I am building "pwsafe" for "My Mac".
This is Xcode 11.2, on MacOS Catalina 10.15.1, both of which are the latest available.   
I can see that os/typedefs.h exists, right in the browser pane to the left, so what's up?

**Comment by sauravg** [comment]
> It chugged for just a short while, then I got the error "os/typedefs.h file not found" in core/StringX.h.
> 
> NOTE:
> I am building "pwsafe" for "My Mac".
> This is Xcode 11.2, on MacOS Catalina 10.15.1, both of which are the latest available.

I just built it successfully from the latest sources using Xcode 11.2, but on Mohave.  Can you please verify

1. Your head is at `dce41c7c3 - (HEAD -> master, origin/master, origin/HEAD) Fix Xcode build (14 hours ago) <sauravg>`
2. git diff shows nothing
3. A clean diff doesn't build it either.

> I can see that os/typedefs.h exists, right in the browser pane to the left, so what's up?

I fixed that exact issue yesterday. Can you copy/paste the text from the compiler's command-line as highlighted in the attached screenshot, for the .cpp file that failed to compile?

![xcode-compile-cmd](https://user-images.githubusercontent.com/8086899/68655007-36ebbf00-0555-11ea-9beb-bd2ed0fc8c0a.png)

**Comment by tinker2much** [comment]
```
git log | head
commit dce41c7c309cedbefdc2b2c58664d1b3cd80ce84
Author: sauravg <sauravg@users.noreply.github.com>
Date:   Mon Nov 11 22:47:38 2019 +0530

    Fix Xcode build
    
    * Add new & moves files to appropriate groups/targets
    * Fix Include path for 'os'
    * Include headers required for symbols used in sources



```

```
git branch
* master

```

```
git diff; echo "Nothing"
Nothing

```

By "clean diff" I think you mean, if I had any differences get rid of them and see if it builds that way? But there aren't any. 

I did CMD-B and got an error in something else. I thought to clean the build folder, then did CMD-B again and it did 200 tasks and said it built successfully!. The docs say that the pwsafe.app should be in Xcode/build/Debug or Xcode/build/Release, but there are no such directories. a find command doesn't find any .app files within the whole git project directory.

**Comment by tinker2much** [comment]
I started looking and did find these: 
```
find ~ -name pwsafe.app -ls 2>&1 | grep -v "^find:" 
12898585524        0 drwxr-xr-x    3 peter            staff                  96 Nov 12 09:10 /Users/peter/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Products/Release/pwsafe.app
12898517668        0 drwxr-xr-x    3 peter            staff                  96 Nov 10 12:19 /Users/peter/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-gbkqalrqmaevghepawoxmagztzem/Build/Products/Release/pwsafe.app

```
I don't know why the earlier one is there, because I don't believe any build was successful before, but I could open the latest app, and then open an expendable copy of my password safe database. Success, apparently!

Is it expected that you find the app like I did and move it somewhere more standard?

**Comment by tinker2much** [comment]
![Screen Shot 2019-11-12 at 9 40 04 AM](https://user-images.githubusercontent.com/57112204/68685918-70f69a00-0530-11ea-9480-e4a526f01cf2.png)

**Comment by tinker2much** [comment]
And it did more than start, the database opened and I could get in and see all my entries, go in to edit one, etc. I'm just not showing that in a screenshot. ;-)

**Comment by sauravg** [comment]
The default build directory could change from one version of Xcode (or
macOS) to other, based on many things like whether it should be part
of backups, etc. The standard way to find the app (build products) is
to right-click on pwsafe.app in the Products group on left side in
Xcode and select "Show in Finder".

I think the textbook way to copy the app to a proper location is to
use the Deployment option in build settings, but I've never used that.

**Comment by tinker2much** [comment]
Thank you very much, everyone, for all the help you have given to me here. 

I would like to return the favor. I do intend to use and test the app that I built. Would you like me to be an informal tester and report any issues or differences that I see?

**Comment by ronys** [comment]
Please do. Detailed and reproducible bug reports are always useful!
