### ISSUE TITLE
__time64_t is not defined on arch linux x86_64

### ISSUE THREAD

**Issue by namarrgon** [pwsafe/pwsafe#602]
The addition of the ```#if !defined(__time64_t) && !defined(__TIME64_T_TYPE)``` guard in https://github.com/pwsafe/pwsafe/commit/497246d4beffcd9347b443b1622e4ea64a7b389c breaks on x86_64 arch linux, with glibc 2.30 and gcc 9.2, where ```__time64_t``` is not defined but ```__TIME64_T_TYPE``` is defined in this scope.

As a result ```__time64_t``` stays undefined and yields a wave of ```error: ‘__time64_t’ does not name a type; did you mean ‘__timer_t’?``` errors during build.

**Comment by ronys** [comment]
That's odd - so how's the 64 bit representation of time type named with this glibc/gcc combination?

**Comment by ronys** [comment]
Also broke on Fedora 31.
Fixed in commit 412458d28

**Comment by namarrgon** [comment]
Thanks, that works at least on x86_64 glibc 2.30, I haven't tested it on x86.
