### ISSUE TITLE
Cannot upgrade to Linux release 1.09.0 version in MINT 19.3 wrong qrencode version

### ISSUE THREAD

**Issue by IanBlakeley** [pwsafe/pwsafe#616]
Install requires libqrencode >= 4.0.2-1 for the Ubuntu version Mint has 3.4.4-1build1 installed as it is based on earlier Ubuntu release 18.04

**Comment by ronys** [comment]
Which version of Mint is that?

**Comment by IanBlakeley** [comment]
Sorry. It is 19.3, latest version

`ian@bilbo2:~$ uname -a
Linux bilbo2 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
ian@bilbo2:~$ 
`

**Comment by rafaelx** [comment]
A Linux Mint specific installation package depends according to the build script on "[libqrencode3](https://packages.ubuntu.com/bionic/libqrencode3) (>= 3.4.4)", which should be the expected version for Linux Mint 19.3 (Ubuntu 18.04).
The installation package for Ubuntu 19 has a dependency to "[libqrencode4](https://packages.ubuntu.com/disco/libqrencode4) (>= 4.0.2-1)" and should therefore not be compatible with Linux Mint 19.

A Linux Mint specific installation package should fix this.

**Comment by ronys** [comment]
Can you try https://github.com/pwsafe/pwsafe/releases/download/1.09.0/passwordsafe-debian10-1.09-amd64.deb ?

**Comment by IanBlakeley** [comment]
That one complains
![Selection_147](https://user-images.githubusercontent.com/36182904/71789161-09f2ee80-3064-11ea-8362-f48cf6af0cc9.png)
 of a missing libcurl dependency

**Comment by ronys** [comment]
sudo apt install libcurl4 should resolve this.

**Comment by IanBlakeley** [comment]
Says that it is already the latest version

`ian@bilbo2:~$ sudo apt install libcurl4
[sudo] password for ian:              
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcurl4 is already the newest version (7.58.0-2ubuntu3.8ppa2).
`

**Comment by rafaelx** [comment]
What about https://github.com/pwsafe/pwsafe/releases/download/1.09.0/passwordsafe-linuxmint19-1.09-amd64.deb ?

**Comment by Karneades** [comment]
This was already tried (see above) and the libcurl4 error message was produced as I understand - the thing is, that the most current version for libcurl4 in Ubuntu 18.04 is 7.58 (https://packages.ubuntu.com/bionic/libcurl4). So it's not compatible with this Mint version.

**Comment by ronys** [comment]
My bad - I sent the wrong link, rafaelx sent the correct one: https://github.com/pwsafe/pwsafe/releases/download/1.09.0/passwordsafe-linuxmint19-1.09-amd64.deb
This should install correctly on Linux Mint. Sorry about the confusion.

**Comment by IanBlakeley** [comment]
Thanks so much. That installs fine
