### ISSUE TITLE
Build on Raspberry Pi?

### ISSUE THREAD

**Issue by MrPaz** [pwsafe/pwsafe#620]
I tried to compile on a Raspberry Pi 2 B running [Ubuntu Mate](https://ubuntu-mate.org/raspberry-pi/) as described in the README.LINUX.DEVELOPERS.md.  I was able to make the Debian package successfully (`cmake -G DEB ..`), but when I tried to install the package (`sudo dpkg -i passwordsafe-ubuntu18-1.09-armv7l.deb`) I got the following error:
`dpkg: error processing archive passwordsafe-ubuntu18-1.09-armv7l.deb (--install):
 package architecture (armv7l) does not match system (armhf)
Errors were encountered while processing:
 passwordsafe-ubuntu18-1.09-armv7l.deb`

So apparently it compiled for armv7l architecture rather than the pi's armhf architecture. Is it possible to compile for armhf instead?  If so, could someone please guide me how to do so??

I also tried `sudo dpkg --force architecture -i passwordsafe-ubuntu18-1.09-armv7l.deb` but there were dependency problems, and also to `sudo dpkg --add-architecture armv7l`, updated and tried again to install with no luck.

Thank you

**Comment by mioux** [comment]
I have a very crappy solution...

    git clone https://github.com/pwsafe/pwsafe.git
    mkdir build
    cd build
    cmake ..
    grep armv7l -rl | sed -i 's/armv7l/armhf/g' # Replace all occurrences of armv7l in generated files
    cpack -G DEB ..

The package is build correctly

![image](https://user-images.githubusercontent.com/6904170/82728135-d6e98880-9cee-11ea-8a73-e94271dfd11b.png)

**Comment by ronys** [comment]
Fixed in commit 04f961c30
Next Linux (wxWidgets) release will include a .deb for Raspbian 10 armhf
