### ISSUE TITLE
Function void TreeCtrl::OnContextMenu(wxContextMenuEvent& event) declared but not defined

### ISSUE THREAD

**Issue by quirxmode** [pwsafe/pwsafe#625]
This breaks the build under linux with wxWidgets 3.1.1. Actually, to get to that error you have to get to the linking step, where it will say something like `<artificial>:(.text.startup+0x3b1): undefined reference to `TreeCtrl::OnContextMenu(wxContextMenuEvent&)'`
But to get there you already need to fix code: the function `TreeCtrl::OnMouseRightClick` is not declared but defined in TreeCtrl if wxWidgets 3.1.1 is available, leading to a compilation error. The ifdef

`#if wxCHECK_VERSION(3, 1, 1)
  EVT_CONTEXT_MENU(TreeCtrl::OnContextMenu)
#else
#ifdef __WINDOWS__
  EVT_RIGHT_UP(TreeCtrl::OnMouseRightClick)
#else
  EVT_RIGHT_DOWN(TreeCtrl::OnMouseRightClick)
#endif
#endif // wxCHECK_VERSION(3, 1, 1)
`

on lines ~src/ui/wxWidgets/TreeCtrl.cpp:111 imho also needs to be repeated for the implementation, where OnMouseRightClick is implemented on line ~822, and `TreeCtrl::OnContextMenu(wxContextMenuEvent&)'` needs to be implemented.

**Comment by rafaelx** [comment]
Could you please give the following branch a try?

https://github.com/rafaelx/pwsafe/tree/Issue625

If it builds successfully it would be interesting whether the context menu is properly working if a tree item is clicked but also if clicking into an empty area of the tree.

**Comment by quirxmode** [comment]
Compiles, works, doesn't crash.
You get the same context menu when you click on an entry or in the empty space to the right of the entry. In both cases this highlights the entry.
If you click in empty space below you do not get a context menu.
I did not test every entry in the context menu, the copy password function does appear to copy the password of the selected entry though.

**Comment by rafaelx** [comment]
Fixed by #635
