### ISSUE TITLE
Clearing the username field is not saved

### ISSUE THREAD

**Issue by postiffm** [pwsafe/pwsafe#634]
1. Create new test entry. It is pre-populated with a default username which is one of my email addresses. Save it.
2. Right click on it, edit, clear the username field, hit Apply and OK. The listing for this entry still shows test [myusername]. Notice that after you hit apply, the "Edit Entry" window still has a blank username, but the listing of passwords in the main window still shows test [myusername].
3. Right click on it, edit, the username is back. It is "stubborn" about being removed.

If instead I change the username to something non-blank, it DOES save it properly. Its like pwsafe always wants to put back the default instead of a blank, even when I tell it I want it blank. (This default is set in Options | Misc. | Default Username.)

So I guess the issue is that if the Default username field has something in it, you don't let any entry have a blank username?  That's not quite right, because if I create a new user test2 and clear the username field at the time of creation, and hit OK, it DOES save the entry with no username.

**Comment by ronys** [comment]
Thanks for the clear write-up. Fixed in commit 3477e3485, will be in next release.
