### ISSUE TITLE
Request: Builds for LTS Releases of Ubuntu

### ISSUE THREAD

**Issue by BloodBlight** [pwsafe/pwsafe#636]
Neither the Debian or Ubuntu DEBs will install on 18.04 LTS due to dependencies for version 1.09.0.

Seems like the last version that works is passwordsafe-ubuntu18-1.08.1-BETA.amd64.deb

**Comment by ronys** [comment]
Do you need a 32 or 64 bit build?

**Comment by BloodBlight** [comment]
64 bit:
`Linux CBSH285340-L 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
$ sudo gdebi passwordsafe-ubuntu19-1.09-amd64.deb 
[sudo] password for bpwoods: 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libqrencode4 (>= 4.0.2-1)
```

libqrencode3 is the latest available on LTS 18:
`libqrencode3/bionic,now 3.4.4-1build1 amd64 [installed,automatic]`

**Comment by ronys** [comment]
https://github.com/pwsafe/pwsafe/releases/download/1.09.0/passwordsafe-ubuntu18-1.09-amd64.deb
https://github.com/pwsafe/pwsafe/releases/download/1.09.0/passwordsafe-ubuntu18-1.09-amd64.deb.sig
