### ISSUE TITLE
PasswordSafe Linux 1.09.0 opens the password database always in Read Only mode

### ISSUE THREAD

**Issue by mrl5** [pwsafe/pwsafe#640]
I am not able to add new entry to a fresh aka new aka vanilla database. It's locked in read-only mode and it does not matter if I tick/untick `Open as read-only`

This bug does not occur in version 1.08_beta (tested on the same database). I did not check other previous versions (1.08.1_beta, 1.08.2_beta)

FYI I'm compiling from sources maybe it does matter in this case?

Anyway I've seen issue #483 and it's not the case here. `*.plk` file appears when I unlock DB and disappears when I close entirely passwordsafe

**Comment by rafaelx** [comment]
Seems to be related to #619 and should already have been fixed.

**Comment by ronys** [comment]
Just to eliminate the obvious: What are the file permissions on the DB file and its directory?

**Comment by mrl5** [comment]
@rafaelx is right looks like #619 when I've created a new item in `1.08_beta` and then opened DB in `1.09.0` I was able to add new entries

@ronys 
```
$ ls -laZ ~/. | grep pwsafe
drwx------.   2 mrl5 mrl5 staff_u:object_r:user_home_t              4096 Mar 23 09:25 .pwsafe
$ ls -laZ ~/.pwsafe/
total 24
drwx------.  2 mrl5 mrl5 staff_u:object_r:user_home_t      4096 Mar 23 09:25 .
drwx------. 81 mrl5 mrl5 staff_u:object_r:user_home_dir_t 12288 Mar 23 09:18 ..
-rw-r--r--.  1 mrl5 mrl5 staff_u:object_r:user_home_t       734 Mar 23 09:24 pwsafe.cfg
-rw-r--r--.  1 mrl5 mrl5 staff_u:object_r:user_home_t       376 Mar 22 17:46 pwsafe.psafe3
```

yes SELinux is present on the OS - it does not matter if it's turned on or off (enforcing or permissive) so I suppose it's not related with the issue (anyways it worked on `1.08_beta` in the same OS so...)

**Comment by rafaelx** [comment]
With #619 the problem should be solved. Do we have here a new issue that needs attention or can this ticket be closed?

**Comment by mrl5** [comment]
ok, so I didn't notice that the fix is not included in 1.09.0 (am I right? https://github.com/pwsafe/pwsafe/compare/1.09.0...master)
before you close could pls confirm that it should be fixed in next release?

**Comment by rafaelx** [comment]
The code freeze for 1.09 was on 2nd of January, the release on 3rd of January and the fix was provided on the 5th of Janurary. So, the fix didn't make it into 1.09, hence will be included in the next version.

If you are already compiling pwsafe from the sources you can safely use the latest commit from the master branch.

**Comment by mrl5** [comment]
> If you are already compiling pwsafe from the sources you can safely use the latest commit from the master branch
good to know, thanks for sharing this info

thanks @rafaelx and @ronys for your help and responsiveness

**Comment by Unixware** [comment]
same issue with 1.10 too (Fedora 32) "password gorilla" can edit the database, "read only" on pwsafe, also your debug messages are broken too: displays a "warning" alert, no other info what's about. thx
