### ISSUE TITLE
Entries not in sorted order. Groups not first.

### ISSUE THREAD

**Issue by Ben-Voris** [pwsafe/pwsafe#643]
PasswordSafe (linux) v1.09 running on Ubuntu 18.04.

I have checked "Put Groups first in Tree View" but this is not honored. 

And, entries are not sorted by title.

The the title of the first entry starts with "O". IT is followed by several groups (which are, themselves, not sorted by name) Eventually, an entry with a title that begins with "A" shows.

**Comment by r4nd0m123** [comment]
The same thing happens for me on Ubuntu 18.04.4 using v1.10.
Could it be an issue with an updated dependency? 

![Screenshot from 2020-05-18 14-21-14](https://user-images.githubusercontent.com/22472188/82180323-e2b20500-9912-11ea-9c15-142ff3ba4a32.png)

**Comment by Ben-Voris** [comment]
Thank you.

**Comment by Ben-Voris** [comment]
Will this be available for Ubuntu 18.04 LTS?

**Comment by ronys** [comment]
> Will this be available for Ubuntu 18.04 LTS?

Uploaded 32 and 64 bit debs for Ubuntu 18 under https://github.com/pwsafe/pwsafe/releases/tag/1.11.0

**Comment by JerryDurand** [comment]
Works, perfect!  Thanks.
