### ISSUE TITLE
I've been pwned: duplicate password finder?

### ISSUE THREAD

**Issue by postiffm** [pwsafe/pwsafe#653]
Is there a report in pwsafe that shows which entries have duplicate passwords? I'm trying to root out all duplicates but with hundreds of passwords, that is tough. A tool/report to find duplicates would be very helpful.

**Comment by ronys** [comment]
The quickest way to check this with the existing version is to switch to List view, add the Password to the set of displayed fields (right-click on the columns title row to select), and then sort by Password.
This will make the duplicates very easy to find by a quick visual scan.

**Comment by postiffm** [comment]
That will work fine--didn't know I could do that. Thanks @ronys
