### ISSUE TITLE
Cannot launch in Fedora 32 due to symbol lookup error

### ISSUE THREAD

**Issue by aevernon** [pwsafe/pwsafe#654]
Installed from `passwordsafe-fedora31-1.10-amd64.rpm`.

`
pwsafe: symbol lookup error: pwsafe: undefined symbol: _ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEE9_M_createERmm, version WXU_3.0`

**Comment by ronys** [comment]
Fixed by building a package for Fedora32: https://github.com/pwsafe/pwsafe/releases/download/1.010.0/passwordsafe-fedora32-1.10-amd64.rpm

**Comment by aevernon** [comment]
Works perfectly. Thank you.
