### ISSUE TITLE
Can't install on Ubuntu 20.04, Focal Fossa

### ISSUE THREAD

**Issue by troywweber7** [pwsafe/pwsafe#656]
I downloaded the deb and tried to run `sudo apt install ./path/to/pwsafe.deb` and get the following error:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'passwordsafe' instead of '/home/troy/Software/PwSafe/pwsafe.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 passwordsafe : Depends: libwxgtk3.0-0 (>= 3.0.0-2) but it is not installable or
                         libwxgtk3.0-0v5 (>= 3.0.0-2) but it is not installable
                Depends: libxerces-c3.2 (>= 3.2.2+debian-1+b1) but it is not going to be installed
                Recommends: xvkbd (>= 3.3-1+b1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by rafaelx** [comment]
Related to issue [514](https://sourceforge.net/p/passwordsafe/support-requests/514/) on SourceForge.

**Comment by troywweber7** [comment]
Okay so I'm not the only one. That's good. Is there a workaround to replace the dependency with libwxgtk3.0-gtk3-0v5 or do we need to wait until another release for the DEB to be fixed?

**Comment by troywweber7** [comment]
Also I don't have experience creating DEB but if there is something I can do to jump in and help fix this bug, if be happy to help.

**Comment by troywweber7** [comment]
Also I don't have experience creating DEB but if there is something I can do to jump in and help fix this bug, if be happy to help.

**Comment by rafaelx** [comment]
A new DEB package, which explicitly targets Ubuntu 20.04, is being baked and will be available shortly.
Please follow the activities at [514](https://sourceforge.net/p/passwordsafe/support-requests/514/) to keep up to date.

**Comment by ronys** [comment]
A new package has been created:
https://github.com/pwsafe/pwsafe/releases/download/1.010.0/passwordsafe-ubuntu20-1.10-amd64.deb

Works for me, please confirm that it works in a non-developer environment.

**Comment by troywweber7** [comment]
@rafaelx @ronys Works for me. Thank you very much, guys! I really appreciate it.
