### ISSUE TITLE
Can't add add new entry unless a group is selected (in the main window)

### ISSUE THREAD

**Issue by atleta** [pwsafe/pwsafe#666]
A new entry can only be added if I select a group from the list or if no item is selected (i.e. right after opening the db). In this case, the add entry popup opens, with the selected group (correctly) displayed in the 'Group' drop down. If I want to add the item at the top level, I have to delete the group (from the drop down).

If I don't select a group, then none of the 'add entry' controls work (the menu item is disabled, the shortcut doesn't work and the toolbar icon is disabled as well).

version: 1.10
OS: Ubuntu 20.04 / Gnome 3.36

**Comment by ronys** [comment]
I'm not sure I understand your description. Can you attach a sample database and describe the exact steps needed to reproduce the problem?

**Comment by atleta** [comment]
It's a UI issue, not related to the DB (or so it seems). But anyway, here is a trivial db with one entry.

I may have not used the same terminology you do, but here is a screenshot showing the problem (with the sample db):
![Selection_01315](https://user-images.githubusercontent.com/6267837/84560501-24cd3b80-ad45-11ea-8970-7754050cb130.png)

The steps are:
* select a password entry by clicking it with the mouse
* see that 'add entry' actions are disabled
* then select a group, see actions get enabled (now you can add a new entry)

I kind of understand the reason behind this, it wants to tell the user that you can't add an entry to another one, only to a group. But besides I think it's unnecessary (and unusual), there is no way to 'unselect' an entry (other than selecting a group). At least I wasn't able to find any. Except for with the sample db when I clicked below the entry, but that doesn't work with my real db as that has around 800 entries. Maybe I'm just missing something, but it wasn't a problem earlier. (But I've been using a few years old version until now, so the change may have occurred in an earlier release.)

[test.plk.gz](https://github.com/pwsafe/pwsafe/files/4774096/test.plk.gz)

**Comment by rafaelx** [comment]
I wonder how the Windows version behaves in this regard. In the Windows version, is it possible to cancel the selection by clicking on the empty area to the right of the element?

**Comment by atleta** [comment]
I'd say being able to cancel is not the solution to this issue as that would still be an unnecessary and unusual extra step. I just mentioned it to help identify the cause.

**Comment by rafaelx** [comment]
At the moment this behavior seems very logical, but it seems also to be somewhat user-unfriendly. At least in case of a database with many entries.
So if a password item is selected, the UI elements for adding an item should be enabled and the editing dialog should be filled with the group name of the selected item?! Wouldn't a selected group be expected to add a new group? Hmmm, maybe it's just a matter of definition.

**Comment by rafaelx** [comment]
If a password element is selected in the Windows version, a new password element can be added to the group of the selected password.
@ronys Should we follow the same approach for the Linux version and relax the current logic a bit?

**Comment by atleta** [comment]
Well, calling it very logical and somewhat user friendly seems like a strange way to put it. At least for me. The whole point of this app is to make the secure and thus preferred user behavior (that is, to use unique and random passwords) user friendly. Which, otherwise is so much of a pain, that most users just don't bother and use the same (non-random) password everywhere.

So I think with this app (and, for that matter most end-user apps) the importance of user-friendliness is paramount. I'd also argue that the current behavior is not very logical. I could even say it's dumb, because the app does not do what the user is (very likely) to mean to do, but tries to teach the user a lesson or at least exposes an internal (and, from the users' perspective) irrelevant constraint. The users know very well that they can't add an entry to an entry, so it wouldn't make sense anyway, so they probably don't mean to do it, so when they want to add an entry while having a selected entry, then it has to mean something else. Context matters.

I think the older versions of the app (I've used 0.9x before uprgading to 1.10) simply left the group field empty when the selection wasn't directly on a group. But what you're suggesting and what the windows version seems to do is indeed what I'd expect to do it too. (And this also seems to be what other apps do in similar situation, which also adds to the "is it the logical behaviour" aspect: whatever most other applications do, will usually seem logical to the users.) E.g. my IDE does the same when you want to create a new file.

**Comment by rafaelx** [comment]
Logically purely from the implementation point of view, if it can be expressed like this. Whatever. I fully agree here that it is not user friendly from the end user's perspective. It should be changed. After all, the application should be there for the user and not vice versa. - Thank you for raising awareness of the problem.

**Comment by atleta** [comment]
@rafaelx @ronys I've just installed v1.11 (linux) that contains the fix and it did not solve the issue. The 'Add' actions (both the menu and the icon) are still disabled unless the selection is on a group.

**Comment by rafaelx** [comment]
Hm, version 1.11 was [released](https://github.com/pwsafe/pwsafe/releases/tag/1.11.0) on 13th of June and the [fix](https://github.com/pwsafe/pwsafe/pull/670) was merged in on the 19th of June. So, it should be included in the next release.
