### ISSUE TITLE
Feature query: Google Titan 2FA

### ISSUE THREAD

**Issue by mhudec** [pwsafe/pwsafe#669]
Would it be possible to use Google Titan for two factor authentication eventually? I have USB-C variant of this key. Thanks for considering.

**Comment by ronys** [comment]
From what I've read, Google Titan isn't suitable for use as a 2FA for PasswordSafe. Sorry.

**Comment by mhudec** [comment]
Well, older Google Titans (USB-A and Bluetooth/NFC) were manufactured by Chinese based Feitian, where there were some security concerns, but this newer Google Titan (USB-C variant, which I mentioned) is manufactured by US based Yubico (and PasswordSafe offers YubiKey for 2FA, which is Yubico product...).

**Comment by ronys** [comment]
Well, what I really need to check the feasibility is a technical description of their programming interface (API), which I couldn't find online, and of course a sample device to test against.
