### ISSUE TITLE
Yubikey button not displayed v1.10/1.11 on Fedora 32

### ISSUE THREAD

**Issue by antigenx** [pwsafe/pwsafe#674]
The builds for Fedora 32 do not show the yubikey button when i insert my yubikey.
Instead the console fills up with the following messages:

(pwsafe:101752): Gtk-WARNING **: 11:13:15.007: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(pwsafe:101752): Gtk-WARNING **: 11:13:15.502: Negative content width -19 (allocation 1, extents 10x10) while allocating gadget (node button, owner GtkButton)

**Comment by antigenx** [comment]
from syslog:

insert event:
Jul 16 11:27:31 xx kernel: usb 2-2: new full-speed USB device number 15 using xhci_hcd
Jul 16 11:27:31 xx kernel: usb 2-2: New USB device found, idVendor=1050, idProduct=0116, bcdDevice= 3.37
Jul 16 11:27:31 xx kernel: usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Jul 16 11:27:31 xx kernel: usb 2-2: Product: Yubikey NEO OTP+U2F+CCID
Jul 16 11:27:31 xx kernel: usb 2-2: Manufacturer: Yubico
Jul 16 11:27:31 xx kernel: input: Yubico Yubikey NEO OTP+U2F+CCID as /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0/0003:1050:0116.02D2/input/input745
Jul 16 11:27:31 xx kernel: hid-generic 0003:1050:0116.02D2: input,hidraw3: USB HID v1.10 Keyboard [Yubico Yubikey NEO OTP+U2F+CCID] on usb-0000:00:14.0-2/input0
Jul 16 11:27:31 xx kernel: hid-generic 0003:1050:0116.02D3: hiddev97,hidraw4: USB HID v1.10 Device [Yubico Yubikey NEO OTP+U2F+CCID] on usb-0000:00:14.0-2/input1
Jul 16 11:27:31 xx mtp-probe[105884]: checking bus 2, device 15: "/sys/devices/pci0000:00/0000:00:14.0/usb2/2-2"
Jul 16 11:27:31 xx mtp-probe[105884]: bus: 2, device: 15 was not an MTP device
Jul 16 11:27:31 xx kernel: input: Yubico Yubikey NEO OTP+U2F+CCID as /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0/0003:1050:0116.02D4/input/input746
Jul 16 11:27:31 xx kernel: hid-generic 0003:1050:0116.02D4: input,hidraw3: USB HID v1.10 Keyboard [Yubico Yubikey NEO OTP+U2F+CCID] on usb-0000:00:14.0-2/input0

Jul 16 11:27:32 xx fido_id[105924]: 2-2:1.0: Failed to open report descriptor at '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0/report_descriptor': No such file or directory
Jul 16 11:27:32 xx kernel: input: Yubico Yubikey NEO OTP+U2F+CCID as /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0/0003:1050:0116.02D6/input/input748
Jul 16 11:27:32 xx kernel: hid-generic 0003:1050:0116.02D6: input,hidraw3: USB HID v1.10 Keyboard [Yubico Yubikey NEO OTP+U2F+CCID] on usb-0000:00:14.0-2/input0
Jul 16 11:27:32 xx pwsafe[105091]: Negative content width -19 (allocation 1, extents 10x10) while allocating gadget (node button, owner GtkButton)
Jul 16 11:27:32 xx pwsafe[105091]: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)
Jul 16 11:27:32 xx pwsafe[105091]: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)
Jul 16 11:27:32 xx pwsafe[105091]: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)
Jul 16 11:27:32 xx pwsafe[105091]: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)
Jul 16 11:27:33 xx kernel: input: Yubico Yubikey NEO OTP+U2F+CCID as /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0/0003:1050:0116.02D7/input/input749
Jul 16 11:27:33 xx kernel: hid-generic 0003:1050:0116.02D7: input,hidraw3: USB HID v1.10 Keyboard [Yubico Yubikey NEO OTP+U2F+CCID] on usb-0000:00:14.0-2/input0
Jul 16 11:27:33 xx pwsafe[105091]: Negative content width -19 (allocation 1, extents 10x10) while allocating gadget (node button, owner GtkButton)
Jul 16 11:27:33 xx pwsafe[105091]: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)
Jul 16 11:27:33 xx pwsafe[105091]: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)
Jul 16 11:27:33 xx pwsafe[105091]: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)
Jul 16 11:27:33 xx pwsafe[105091]: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)
Jul 16 11:27:33 xx kernel: input: Yubico Yubikey NEO OTP+U2F+CCID as /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0/0003:1050:0116.02D8/input/input750
Jul 16 11:27:33 xx kernel: hid-generic 0003:1050:0116.02D8: input,hidraw3: USB HID v1.10 Keyboard [Yubico Yubikey NEO OTP+U2F+CCID] on usb-0000:00:14.0-2/input0

**Comment by rafaelx** [comment]
Resolved by #683
