### ISSUE TITLE
DMG artifact problem

### ISSUE THREAD

**Issue by ronys** [pwsafe/pwsafe#679]
Here's the text of the "Problem Report for pwsafe" which was NOT sent to Apple

Appears a lib was missing from the .app??

I could also try on my Mojave or High Sierra systems if that would help

---

Process:               pwsafe [74992]
Path:                  /Users/USER/Desktop/pwsafe.app/Contents/MacOS/pwsafe
Identifier:            org.pwsafe.pwsafe
Version:               1.0 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           pwsafe [74992]
User ID:               502

Date/Time:             2020-07-30 04:52:31.501 -0500
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Bridge OS Version:     4.5 (17P5300)
Anonymous UUID:        [...]

Sleep/Wake UUID:       [...]

Time Awake Since Boot: 2300000 seconds
Time Since Wake:       10000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/wxmac/lib/libwx_osx_cocoau_xrc-3.0.dylib
  Referenced from: /Users/USER/Desktop/pwsafe.app/Contents/MacOS/pwsafe
  Reason: image not found

Binary Images:
       0x10f4e9000 -        0x10f759ff7 +org.pwsafe.pwsafe (1.0 - 1) <4643F588-22C9-3EB4-9FDB-9E660E486618> /Users/USER/Desktop/pwsafe.app/Contents/MacOS/pwsafe
       0x115f49000 -        0x115fdaeff  dyld (750.5) <E4698FBD-806A-3396-B279-E685BA37430B> /usr/lib/dyld

Model: MacBookPro16,1, BootROM 1037.120.87.0.0 (iBridge: 17.16.15300.0.0,0), 8 processors, 8-Core Intel Core i9, 2.3 GHz, 64 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro5500MItem, AMD Radeon Pro 5500M, spdisplays_pcie_device, 8 GB
Memory Module: BANK 0/ChannelA-DIMM0, 32 GB, DDR4, 2667 MHz, Micron, -
Memory Module: BANK 2/ChannelB-DIMM0, 32 GB, DDR4, 2667 MHz, Micron, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Apr  7 2020 13:09:12 version 9.30.357.41.32.5.49 FWID 01-617711e7
Bluetooth: Version 7.0.5f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: Apple T2 Bus
USB Device: Composite Device
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 55.3
Thunderbolt Bus: MacBook Pro, Apple Inc., 55.3

_Originally posted by @seamusdemora in https://github.com/pwsafe/pwsafe/pull/676#issuecomment-666270488_

**Comment by ronys** [comment]
Above relates to this artifact:
https://github.com/pwsafe/pwsafe/suites/980969048/artifacts/12545339

**Comment by seamusdemora** [comment]
Would you like me to run this one also - or something else? I'm confused.

**Comment by sauravg** [comment]
The build system for macOS currently does not bundle wxWidgets binaries. User has to install wxWidgets by running `brew install wxwidgets`

**Comment by seamusdemora** [comment]
I wouldn't install `brew` on **your** system - much less mine.

If that's the plan, we're done here, but thanks for the information.

**Comment by seamusdemora** [comment]
I can't edit or delete the OP here (it was copied here by someone else). I'm not keen on leaving it posted as the diagnostics may have information that I wouldn't want posted. My original plan was to post it, then delete it after the developers had gotten what they needed.

Could someone please delete this OP?

**Comment by ronys** [comment]
Sorry. I've redacted the original comment and cleared the revision history.

**Comment by ronys** [comment]
Could you try [this dmg file](https://github.com/pwsafe/pwsafe/suites/1007282570/artifacts/13095556)?
It should be self-contained.

**Comment by seamusdemora** [comment]
Thanks - I will try it at first opportunity.

Going forward, will the dmg for macOS include "all the pieces"?

**Comment by seamusdemora** [comment]
@ronys :

I've tried this, and at first glance, all seems to be well. I'll use it more & let you know if I see anything unusual.

Is this version "safe" to use, or should I continue using the Java version of pwsafe for a while longer??

**Comment by ronys** [comment]
Not sure what you mean by "safe".
It was built by GitHub's CI/CD processes, and not on a machine directly under my control, so theoretically the code could have been manipulated during the build process in a manner that wouldn't show up in the logs, which I reviewed. That would be a non-trivial effort, though.

**Comment by seamusdemora** [comment]
@ronys : By "safe" I meant only do I need to worry about this version mangling my data base? I keep backups of course, but it seems possible that entries in a pwsafe db could be corrupted, and that might not be obvious for a while. I guess I am trying to get a feel for **your** confidence in this early release - I'm wondering if it's "ready to go" - or if this release was just a trial/alpha/beta release.

**Comment by ronys** [comment]
In that sense of "safe" (data integrity), I feel pretty confident:
- The core code that deals with reading, editing and writing the database is pretty stable, and has been ported to multiple platforms. I haven't seen a data corruption bug for a recent version in  quite a while.
- By default, when PasswordSafe saves the database, it first renames the existing file to end with "_nnn.ibak", so you automatically have backups of up to the last change.
- In any case, keeping copies offline is always a good idea.
