### ISSUE TITLE
ubuntu18 v1.11.0 exits on Manage/Options

### ISSUE THREAD

**Issue by ovesh** [pwsafe/pwsafe#687]
When trying to view the Options dialog (either by clicking the menu item or with the keyboard shortcut), pwsafe exits.

If there's any way for me to add logs or any debug info, let me know.

**Comment by rafaelx** [comment]
I guess it was fixed in 8dbe3c42d8a3ab0f8500ada8f81874f0162bcd40.

@ronys If I'm not wrong, the fix didn't make it into release 1.11. As a result, users would be faced with an application crash as this error report may already show.

**Comment by rafaelx** [comment]
Should be fixed in version 1.12.
