### ISSUE TITLE
3.53.0 - app version showing as "V3.53pre"

### ISSUE THREAD

**Issue by tcss-twc** [pwsafe/pwsafe#688]
Hello Rony,

Thanks for releasing 3.53.0!

A small nit ..., but assume you'd prefer to know.  I'm sure all packages are the same, but I tried pwsafe64-3.53.0.exe and pwsafe64-3.53.0.msi and both showed "pre".

![small_nit_splash](https://user-images.githubusercontent.com/61029232/92523901-035ddd80-f1d6-11ea-975b-cb7fe5def079.png)
![small_nit_about](https://user-images.githubusercontent.com/61029232/92523903-03f67400-f1d6-11ea-8453-bfeefce1fdc4.png)

**Comment by tcss-twc** [comment]
Oops, please ignore second image (About Password Safe) that was the "real 3.53.0pre".  Here's the released 3.53.0 "About"

(Didn't want to confuse people).

![small_nit_about_corrected](https://user-images.githubusercontent.com/61029232/92527445-de6c6900-f1db-11ea-860d-5884e3b4f9b7.png)

**Comment by ronys** [comment]
Thanks!
Fixed the packages, updated my release procedure, so hopefully this is the last time this happens...
