### ISSUE TITLE
Version 3.54 reports "this entry has been changed" even when no edits have been made

### ISSUE THREAD

**Issue by keystrike** [pwsafe/pwsafe#695]
If an entry is opened for editing and no changes are made then pwsafe 3.54 still asks for cancel confirmation when closing the  entry.

![image](https://user-images.githubusercontent.com/2402779/95683355-02f89e00-0beb-11eb-8664-061e6db8cbfa.png)

**Comment by ronys** [comment]
Can you create a sample database that allows me to reproduce this problem?

**Comment by keystrike** [comment]
Creating a new database doesn't cause the issue. It happens even when creating a new entry and immediately canceling it. I attempted to export an entry to a new safe but that did not replicate it. Are there any additional tests I can run?

**Comment by ronys** [comment]
Do you by any chance have a default username configured?
That is, when you create a new entry, is the username field filled?

**Comment by keystrike** [comment]
Yes, but turning this off doesn't fix the issue.

**Comment by ronys** [comment]
Can you check the pre-release version at https://sourceforge.net/projects/passwordsafe/files/PreReleases/3.54.01/ ?
If the problem persists, a small sample database where it appears would help *a lot*

**Comment by keystrike** [comment]
Unfortunately it doesn't fix it. I have just managed to create a sample database that has the error. Just in case it has any private information I would rather email it to you. Is that ok?

**Comment by ronys** [comment]
Sure. ronys at pwsafe dot org

Don't forget to include the master password.

**Comment by keystrike** [comment]
Thanks! But I think I figured it out by exporting that entry to XML. The notes field ended with a "»" character.

<notes><![CDATA[test»]]></notes>

If you import this then the issue should occur.

**Comment by ronys** [comment]
Can you check the updated pre-release version at https://sourceforge.net/projects/passwordsafe/files/PreReleases/3.54.01/ ?

**Comment by keystrike** [comment]
That fixed it! What was the issue? Thanks, good work.

**Comment by ronys** [comment]
To make a long story short, I had to add code to ignore different (but equivalent) types of end-of-line conventions while checking the Notes field for modifications.
