### ISSUE TITLE
pwsafe.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by keystrike** [pwsafe/pwsafe#696]
On Windows 8.1 pwsafe64 3.54.0 does not launch. The following error is received:

The procedure entry point GetSystemMetricsForDpi could not be located in the dynamic link library C:\Program Files\Password Safe\pwsafe.exe.

**Comment by robt121** [comment]
This error also occurs on Windows 7 SP1 (64-bit)

**Comment by ronys** [comment]
Yes, this release inadvertently broke support for pre-Windows 10.

Working on a fix.

**Comment by ronys** [comment]
I've created a build that should fix this, and would appreciate testing on Windows 7 and 8 machines.
[https://pwsafe.org/tmp/3.54.1/pwsafe64-3.54.1.exe](https://pwsafe.org/tmp/3.54.1/pwsafe64-3.54.1.exe) (64 bit)
[https://pwsafe.org/tmp/3.54.1/pwsafe-3.54.1.exe](https://pwsafe.org/tmp/3.54.1/pwsafe-3.54.1.exe) (32 bit)

**Comment by robt121** [comment]
Windows 7 still has same error. Tested both 32-bit and 64-bit versions.

**Comment by ronys** [comment]
Not exactly the same error (another function).

Take 2:
https://pwsafe.org/tmp/3.54.1/pwsafe64-3.54.1.exe (64 bit)
https://pwsafe.org/tmp/3.54.1/pwsafe-3.54.1.exe (32 bit)
https://pwsafe.org/tmp/3.54.1/pwsafe64-3.54.1-bin.zip (64 bit)
https://pwsafe.org/tmp/3.54.1/pwsafe-3.54.1-bin.zip

**Comment by woowoo803** [comment]
I tried pwsafe64-3.54.1.exe on Windows 7 .  A similar but different error:

![image](https://user-images.githubusercontent.com/69127430/96182464-5ec46f00-0eea-11eb-8aaf-e7d770c09ed5.png)

**Comment by rafaelx** [comment]
Related to bug report [1526](https://sourceforge.net/p/passwordsafe/bugs/1526/) on SourceForge, for anyone interested who would also like to follow the discussion there.

**Comment by ronys** [comment]
OK, I tink I've nailed it this time (32 bit version tested on a Windows 7 VM). Same links as before:
https://pwsafe.org/tmp/3.54.1/pwsafe64-3.54.1.exe (64 bit)
https://pwsafe.org/tmp/3.54.1/pwsafe-3.54.1.exe (32 bit)
https://pwsafe.org/tmp/3.54.1/pwsafe64-3.54.1-bin.zip (64 bit)
https://pwsafe.org/tmp/3.54.1/pwsafe-3.54.1-bin.zip

 Any feedback welcome.

**Comment by robt121** [comment]
I can confirm that this latest version does run on Windows 7. However, I found a couple of issues:
1. Help->About dialog no longer works
2. Add/Edit Entry dialog is missing "Basic" tab

**Comment by ronys** [comment]
Last issues fixed, 3.54.1 formally released.
