### ISSUE TITLE
Linux binaries not linked on on the main pwsafe.org website

### ISSUE THREAD

**Issue by atleta** [pwsafe/pwsafe#697]
It might be just hard to find, but I wasn't able to do so. There is a download button on the main page that points to fosshub, but the linux binaries seem to be absent from there and the 'alternate mirror' under the button points to the windows binary directly.

You might want to link to the github releases (for both platforms) to make it more discoverable. Especially since the version check in the about dialog links to the pwsafe.org page (in the linux version, at least) from where you just can't find the binary. On a side note, the about dialog or, better yet, the dialog that informs the users of the new version, could come up with the direct download link too.

Also, it would be worth considering adding a link pointing to the github repo to the main page.

Yet another thing - I've just checked again, and the main site has 3 links called "Mirror" 1-3, but they are not mirrors, npt even download mirrors, since their content is different from the site and from each other. The 3rd one does point to sourceforge and SF does take me to the deb download (but the other "mirrors" do not, as they are the above mentioned fosshub.com and direct github links). Also, the SF deb is outdated.

**Comment by ronys** [comment]
website updated - thanks!
