### ISSUE TITLE
Make gtest dependency optional in cmake

### ISSUE THREAD

**Issue by mrueg** [pwsafe/pwsafe#70]
Gtest is not required if you don't want to build and run tests. Could you make this optional in cmake please?

**Comment by kainjow** [comment]
Or just switch to [Catch](https://github.com/philsquared/Catch) which is header only.

**Comment by ronys** [comment]
Hm. Catch looks interesting. Any chance you can create a branch with it instead of gtest? If not, I'll get around to it once I've finished the switch to cmake.

**Comment by ronys** [comment]
NO_GTEST added to cmake configuration.

**Comment by dskrvk** [comment]
One weird thing I saw is that Gtest seems to become part of the .deb package. I ran into a conflict when `dpkg` tried to unpack the header files over what I already had in my global lib directory.

**Comment by ronys** [comment]
Thanks for reporting this!
You can fix this manually by turning off  INSTALL_GTEST running cmake, or you can update to commit 6a9916f8c, which does this for you.
