### ISSUE TITLE
Move entries between two databases under linux (manjaro)

### ISSUE THREAD

**Issue by womonix** [pwsafe/pwsafe#704]
How can i move or copiy entries between databases under linux?
It's  easy on windows, but i don't how to manage it under linux.

Thanks's

**Comment by ronys** [comment]
Until drag&drop is implemented under wxWidgets, the best you can do for Linux is to export the entries you're interested in to an XML file (use Advanced... to limit the entries to those you want to copy), and then import that file to the target database.

**Comment by womonix** [comment]
Hi ronys,
thank, but this doesn't work. Right clicking one entrie, the drop down menu doesn't show the selection "export..."
This is a difference to the window version.

**Comment by rafaelx** [comment]
Have you already tried "File" > "Export To" > "XML format..." ?

**Comment by womonix** [comment]
"File" > "Export To" > "XML format...",  will export the entire(!) database. 
No way to select only one entry.

**Comment by womonix** [comment]
Next try: File" > "Export To" > "XML format.. -> Advanced -> restrict to a subset -> choose "Titel" -> enter the following text 
-> edit: "name of entry" -> select all fields .
Is this  correct??

**Comment by KaiZin2018** [comment]
Why not using compare, synchronize or merge?

**Comment by rafaelx** [comment]
Based on #715 items can be dragged and dropped between different instances of the application using the last tool from the drag bar. - This should have been released with version [1.13](https://github.com/pwsafe/pwsafe/releases/tag/1.13.0).
