### ISSUE TITLE
Build fails on Mac -"Undefined symbols for architecture x86_64:"

### ISSUE THREAD

**Issue by tinker2much** [pwsafe/pwsafe#707]
I haven't tried to build pwsafe since August 15, 2020, at which time it worked fine. I did a pull and tried a build a few days ago and got a similar error. I just did a pull again which brought me only the very latest tiny changes (see "git diff 911ea581e  10a85e269"). 

FYI: this is under Catalina, on a Mac Mini that I can't upgrade to Big Sur. 

`Ld /Users/myname/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Products/Release/pwsafe-cli normal (in target 'pwsafe-cli' from project 'pwsafe-xcode6')
    cd /Users/myname/Documents/pwsafe/Xcode
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-macos10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -L/Users/myname/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Products/Release -F/Users/myname/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Products/Release -filelist /Users/myname/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Intermediates.noindex/pwsafe-xcode6.build/Release/pwsafe-cli.build/Objects-normal/x86_64/pwsafe-cli.LinkFileList -Xlinker -object_path_lto -Xlinker /Users/myname/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Intermediates.noindex/pwsafe-xcode6.build/Release/pwsafe-cli.build/Objects-normal/x86_64/pwsafe-cli_lto.o -stdlib\=libc++ -L/usr/local/lib -L/Users/myname/Documents/wxWidgets-3.0.4/static-release/lib /Users/myname/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_xrc-3.0.a /Users/myname/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_qa-3.0.a /Users/myname/Documents/wxWidgets-3.0.4/static-release/lib/libwx_baseu_net-3.0.a /Users/myname/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_html-3.0.a /Users/myname/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_adv-3.0.a /Users/myname/Documents/wxWidgets-3.0.4/static-release/lib/libwx_osx_cocoau_core-3.0.a /Users/myname/Documents/wxWidgets-3.0.4/static-release/lib/libwx_baseu_xml-3.0.a /Users/myname/Documents/wxWidgets-3.0.4/static-release/lib/libwx_baseu-3.0.a -lpng -ljpeg -ltiff -lexpat -lwxregexu-3.0 -lz -lpthread -liconv -framework Carbon -lcore -framework AppKit -los -framework Foundation -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/myname/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Intermediates.noindex/pwsafe-xcode6.build/Release/pwsafe-cli.build/Objects-normal/x86_64/pwsafe-cli_dependency_info.dat -o /Users/myname/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Products/Release/pwsafe-cli

Undefined symbols for architecture x86_64:
  "_CGLChoosePixelFormat", referenced from:
      _grabViaOpenGL in libwx_osx_cocoau_core-3.0.a(corelib_glgrab.o)
  "_CGLClearDrawable", referenced from:
      _grabViaOpenGL in libwx_osx_cocoau_core-3.0.a(corelib_glgrab.o)
  "_CGLCreateContext", referenced from:
      _grabViaOpenGL in libwx_osx_cocoau_core-3.0.a(corelib_glgrab.o)
  "_CGLDestroyContext", referenced from:
      _grabViaOpenGL in libwx_osx_cocoau_core-3.0.a(corelib_glgrab.o)
  "_CGLDestroyPixelFormat", referenced from:
      _grabViaOpenGL in libwx_osx_cocoau_core-3.0.a(corelib_glgrab.o)
  "_CGLSetCurrentContext", referenced from:
      _grabViaOpenGL in libwx_osx_cocoau_core-3.0.a(corelib_glgrab.o)
  "_CGLSetFullScreen", referenced from:
      _grabViaOpenGL in libwx_osx_cocoau_core-3.0.a(corelib_glgrab.o)
  "_IOCreatePlugInInterfaceForService", referenced from:
      wxHIDDevice::Create(int, int, int) in libwx_osx_cocoau_core-3.0.a(corelib_hid.o)
  "_IOIteratorNext", referenced from:
      wxHIDDevice::Create(int, int, int) in libwx_osx_cocoau_core-3.0.a(corelib_hid.o)
      wxHIDDevice::GetCount(int, int) in libwx_osx_cocoau_core-3.0.a(corelib_hid.o)
  "_IOMasterPort", referenced from:
      wxHIDDevice::Create(int, int, int) in libwx_osx_cocoau_core-3.0.a(corelib_hid.o)
      wxHIDDevice::GetCount(int, int) in libwx_osx_cocoau_core-3.0.a(corelib_hid.o)
  "_IOObjectRelease", referenced from:
      wxHIDDevice::Create(int, int, int) in libwx_osx_cocoau_core-3.0.a(corelib_hid.o)
      wxHIDDevice::GetCount(int, int) in libwx_osx_cocoau_core-3.0.a(corelib_hid.o)
  "_IORegistryEntryCreateCFProperties", referenced from:
      wxHIDDevice::Create(int, int, int) in libwx_osx_cocoau_core-3.0.a(corelib_hid.o)
  "_IOServiceGetMatchingServices", referenced from:
      wxHIDDevice::Create(int, int, int) in libwx_osx_cocoau_core-3.0.a(corelib_hid.o)
      wxHIDDevice::GetCount(int, int) in libwx_osx_cocoau_core-3.0.a(corelib_hid.o)
  "_IOServiceMatching", referenced from:
      wxHIDDevice::Create(int, int, int) in libwx_osx_cocoau_core-3.0.a(corelib_hid.o)
      wxHIDDevice::GetCount(int, int) in libwx_osx_cocoau_core-3.0.a(corelib_hid.o)
  "_glFinish", referenced from:
      _grabViaOpenGL in libwx_osx_cocoau_core-3.0.a(corelib_glgrab.o)
  "_glPixelStorei", referenced from:
      _grabViaOpenGL in libwx_osx_cocoau_core-3.0.a(corelib_glgrab.o)
  "_glReadBuffer", referenced from:
      _grabViaOpenGL in libwx_osx_cocoau_core-3.0.a(corelib_glgrab.o)
  "_glReadPixels", referenced from:
      _grabViaOpenGL in libwx_osx_cocoau_core-3.0.a(corelib_glgrab.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

`

**Comment by ronys** [comment]
@sauravg - looks like backwards compatibility with Catalina is broken. Anything we can do?

**Comment by sauravg** [comment]
I just built it successfully on Catalina. Here's literally all I did

> ~ saurav$ cd /tmp
> tmp saurav$ git clone https://github.com/pwsafe/pwsafe.git
> Cloning into 'pwsafe'...
> remote: Enumerating objects: 922, done.
> remote: Counting objects: 100% (922/922), done.
> remote: Compressing objects: 100% (807/807), done.
> remote: Total 112191 (delta 280), reused 223 (delta 112), pack-reused 111269
> Receiving objects: 100% (112191/112191), 98.96 MiB | 3.80 MiB/s, done.
> Resolving deltas: 100% (77093/77093), done.
> tmp saurav$ cd pwsafe
> pwsafe saurav$ cd Xcode/
> Xcode saurav$ which wx-config
> /usr/local/bin/wx-config
> Xcode saurav$ ./generate-configs -r `which wx-config` > pwsafe-release.xcconfig
> Xcode saurav$ ./generate-configs -r `which wx-config` > pwsafe-debug.xcconfig
> Xcode saurav$ ls
> generate-configs*        pwsafe-i386.plist        pwsafe-release.xcconfig  pwsafe.plist
> pwsafe-debug.xcconfig    pwsafe-llvm.plist        pwsafe-xcode6.xcodeproj/ pwsafe64.plist
> Xcode saurav$ open pwsafe-xcode6.xcodeproj
> 

The only thing different is that I have wx 3.0.5, but the OP seems to have 3.0.4. He should upgrade his wxWidgets install and try building in a new folder.

**Comment by tinker2much** [comment]
I got the later wx (3.05), built that ok for both release and debug. 

I cleaned up the build folder, and tried again, all good until I got this:

Ld /Users/myname/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Products/Release/pwsafe-cli normal (in target 'pwsafe-cli' from project 'pwsafe-xcode6')
    cd /Users/myname/Documents/pwsafe/Xcode
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-macos10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -L/Users/myname/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Products/Release -F/Users/myname/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Products/Release -filelist /Users/myname/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Intermediates.noindex/pwsafe-xcode6.build/Release/pwsafe-cli.build/Objects-normal/x86_64/pwsafe-cli.LinkFileList -Xlinker -object_path_lto -Xlinker /Users/myname/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Intermediates.noindex/pwsafe-xcode6.build/Release/pwsafe-cli.build/Objects-normal/x86_64/pwsafe-cli_lto.o -stdlib\=libc++ -L/Users/myname/Documents/wxWidgets-3.0.5/static-release/lib /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_osx_cocoau_xrc-3.0.a /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_osx_cocoau_qa-3.0.a /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_baseu_net-3.0.a /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_osx_cocoau_html-3.0.a /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_osx_cocoau_adv-3.0.a /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_osx_cocoau_core-3.0.a /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_baseu_xml-3.0.a /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_baseu-3.0.a -ljpeg -ltiff -lexpat -lwxregexu-3.0 -lwxpng-3.0 -lz -lpthread -liconv -framework Carbon -lcore -framework AppKit -los -framework Foundation -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/myname/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Intermediates.noindex/pwsafe-xcode6.build/Release/pwsafe-cli.build/Objects-normal/x86_64/pwsafe-cli_dependency_info.dat -o /Users/myname/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Products/Release/pwsafe-cli

ld: library not found for -ljpeg
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sauravg** [comment]
How did you run the configure script for building wxWidgets?

Di you regenerate pwsafe-debug.xcconfig  & pwsafe-release.xcconfig after rebuilding wxWidgets?

It is possible that you chose to use an external version of libjpeg while building wxWidgets. In which case, you may need to specify the path to the external iibjpeg while building pwsafe.

Please post the outputs of 

wx-config --cxxflags
wx-config --libs

**Comment by sauravg** [comment]
Also, FWIW, I just use homebrew to install wxWidgets for me. It's much simpler that way.

**Comment by tinker2much** [comment]
> What params did you pass to the configure script for building wxWidgets?
> 
> Did you regenerate pwsafe-debug.xcconfig & pwsafe-release.xcconfig after rebuilding wxWidgets?
> 
> It is possible that you chose to use an external version of libjpeg while building wxWidgets. In which case, you may need to specify the path to the external iibjpeg while building pwsafe.
> 
> Please post the outputs of
> 
> wx-config --cxxflags
> wx-config --libs

I tried to follow your email example and the Mac developer document. These are my notes at the time:
20200107 try to build again after reply from pwsafe
	say to try wxwidgets 3.05 instead of 3.04
	download source for 3.05 for linux/mac
	read pwsafe build instructions for wxwidgets in README.MAC.DEVELOPERS.md
		cd ~/Documents
		tar -xzf %D/%F (the downloaded wxwidgets tarball)
		mkdir static-debug
		cd static-debug
		~/Documents/pwsafe/misc/osx-build-wx -d
		make (half an hour?) 
		mkdir static-release
		cd static-release
		~/Documents/pwsafe/misc/osx-build-wx
		make -j4  (9 minutes) 
		Go to the Xcode directory in pwsafe sources, and do these
			./generate-configs -d [full-path-to-your-static-debug/wx-config] > pwsafe-debug.xcconfig
				./generate-configs -d /Users/myname/Documents/wxWidgets-3.0.5/static-debug/wx-config  > pwsafe-debug.xcconfig
			./generate-configs -r [full-path-to-your-static-release/wx-config] > pwsafe-release.xcconfig
				./generate-configs -r /Users/myname/Documents/wxWidgets-3.0.5/static-release/wx-config > pwsafe-release.xcconfig
		open pwsafe-xcode6.xcodeproj 
		clean the build
		hit 'Cmd-B'. 

As requested (for release):
myname@Mynames-Mac-mini wxWidgets-3.0.5 % /Users/myname/Documents/wxWidgets-3.0.5/static-release/wx-config --cxxflags
-I/Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/wx/include/osx_cocoa-unicode-static-3.0 -I/Users/myname/Documents/wxWidgets-3.0.5/include -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__ 

myname@Mynames-Mac-mini wxWidgets-3.0.5 % /Users/myname/Documents/wxWidgets-3.0.5/static-release/wx-config --libs
-L/Users/myname/Documents/wxWidgets-3.0.5/static-release/lib   -framework IOKit -framework Carbon -framework Cocoa -framework AudioToolbox -framework System -framework OpenGL /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_osx_cocoau_xrc-3.0.a /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_osx_cocoau_qa-3.0.a /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_baseu_net-3.0.a /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_osx_cocoau_html-3.0.a /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_osx_cocoau_adv-3.0.a /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_osx_cocoau_core-3.0.a /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_baseu_xml-3.0.a /Users/myname/Documents/wxWidgets-3.0.5/static-release/lib/libwx_baseu-3.0.a -ljpeg -ltiff -lexpat -lwxregexu-3.0 -lwxpng-3.0 -lz -lpthread -liconv

**Comment by tinker2much** [comment]
> Also, FWIW, I just use homebrew to install wxWidgets for me. It's much simpler that way.

I use home-brew for other things, but I never thought of using it for this. I probably would have thought that it wouldn't have been built the particular way that you require?

**Comment by sauravg** [comment]
I think because of the way `osx-build-wx` script builds wxWigets as a static libraries (archives), the dependent libraries need to be set up manually in Xcode for pwsafe.  An update is long overdue for that script.

In the meantime, you have these options, as far as I can tell:

# use homebrew to install wxWidgets and then run 'generate-configs' using /usr/local/bin/wx-config. This is the easiest
# Install the missing libraries using homebrew itself. 'brew install jpeg' should install libjpeg for you in /usr/local/lib
# Add libjpeg.a (and other libraries as requried) to Xcode(under Frameworks, libraries & embedded content in pwsafe target, General tab)

**Comment by tinker2much** [comment]
> I think because of the way `osx-build-wx` script builds wxWigets as a static libraries (archives), the dependent libraries need to be set up manually in Xcode for pwsafe. An update is long overdue for that script.
> 
> In the meantime, you have these options, as far as I can tell:
> 
> 1. use homebrew to install wxWidgets and then run 'generate-configs' using /usr/local/bin/wx-config. This is the easiest
> 2. Install the missing libraries using homebrew itself. 'brew install jpeg' should install libjpeg for you in /usr/local/lib
> 3. Add libjpeg.a (and other libraries as requried) to Xcode(under Frameworks, libraries & embedded content in pwsafe target, General tab)

I chose the easiest option, #1. Build succeeded. Thank you!
