### ISSUE TITLE
Windows version does not respect the .plk file from Linux version

### ISSUE THREAD

**Issue by WayneSherman** [pwsafe/pwsafe#716]
**Versions Tested**
Windows version "pwsafe-3.55.0-bin"
Linux version "passwordsafe-ubuntu16-1.12-amd64.deb"

Note:  The file test_file.psafe3 is stored on a Linux file server and accessed via smb/cifs protocol

**Test 1: Open file on Linux first, then on Windows (BAD)**

1. Open test_file.psafe3 file on Ubuntu (v16.04)
2. test_file.plk file gets created
3. Open same test_file.psafe3 on Windows 10

**Current Behavior:**  Even though a valid .plk file exists, the DB is opened on Windows for Read-Write and the existing test_file.plk file gets overwritten by a new one.

**Expected Behavior:**  The Windows version should detect the .plk file and warn the user offering to open in read-only mode.  It should not overwrite the valid .plk file which was created by the Linux version.

**Test 2: Open file on Windows first, then on Linux (OK)**

1. Open test_file.psafe3 file on Windows 10
2. test_file.plk file gets created
3. Open the same test_file.psafe3 using Ubuntu

This behaves as expected with a warning message and opens the DB read-only.

**Comment by KaiZin2018** [comment]
Locking between Windows and Non-Windows looks not compatible. While Non-Windows locking is depending from existing of the plk-file the Windows implementation is using file locking based on file left open.

**Comment by ronys** [comment]
Looks like a Samba issue, not PasswordSafe specific.

**Comment by WayneSherman** [comment]
**Test 3:**  On Linux, open the .psafe3 file located on the file server for Read/Write.  On Linux, from a second instance of pwsafe, try to open the same file again as Read/Write.  The Linux version properly warns "File in Use" and opens the file Read-Only.

**Test 4:**  In Windows, open the .psafe3 file located on the file server for Read/Write.  On Windows, from a second instance of pwsafe, try to open the same file again as Read/Write.  The Windows version properly warns "File in Use" and asks to open as Read-Only.

> Looks like a Samba issue, not PasswordSafe specific.

Tests 2, 3, and 4, show that there is not a problem with Samba because from the same file server, the Linux version behaves correctly whether the file is already open on Windows or Linux.  And from the same file server, the Windows version behaves correctly when the file is already open on Windows.

The issue is the Windows version does not detect the .plk file from Linux correctly.  All other cases work.
