### ISSUE TITLE
Probably Security Issue: Yubikey OTP secret still accessible after deleting Yubikey method & slot compromising previous database files 

### ISSUE THREAD

**Issue by bentolor** [pwsafe/pwsafe#718]
I'm currently evaluating if I want to migrate from _„annoyingly-hard-to-type-password“_-mode to _„quickly-typable-password-with-yubikey“_-mode for pwsafe. Therefore I did some experiment. Mostly I was trying to figure out recovery options with lost yubikeys (but known secrets). 

I was also looking for design documentation about how this feature is technically implemented to assess it security, but failed. 
I also tried to quickly "dump" the raw `.pwsafe3` file content using `Crypt::Pwsafe.pm` to better understand the internals, but failed there too. 

Nevertheless – here is my issue:

## Problem description / How to reproduce
1. You are Alice. Create a new `mypw.psafe3` database with a password `123456` using _PasswordSafe Linux v1.12_. Open it. Create one dummy entry.
2. Generate & write a Yubikey secret to a new Yubikey. _(Note it down for debugging reference only here)_
3. Enhance security by changing  to master passphrase `123456` + Yubikey
4. Close & Reopen to validate. **Enter some super-secret** secret. Save. Bob creates a database backup file: `nsa-backup.psafe3`
5. **Delete the *super-secret* secret.**
5. Change master password back to password-only: `123456`
6. Close & exit
7. Delete the Yubikey secret on key: `ykman otp delete 2`
8. **At this point I'd expect to be no longer able to access my _super-secret secret_ without the noted-down copy of the OTP secret!**
8. Reopen database with password only. Bob creates second backup: `nsa-backup-2.psafe3`.
9. Open "Yubikey" dialog: Still be able to see & access the previous yubikey secret. 
10. Using the method below: Bob can program a fresh, new Yubikey, open `nsa-backup.psafe3` with your (compromised) password `123456` and **reveal the deleted super-secret entry** by **only** having access to both  `nsa-*.pwsafe` backups and the typed password and **without the need to ever had access to Alice's hardware key!**.

IMHO this behavior renders the added-value/security of a hardware key like yubikey to void. 

Also note: It's not essential that Alice sticks to the same master password `123456`: I only chose it to reduce the attack complexity for Bob: He must only get hold to one password (plus the two backups).

## Expected behavior (failing)
As noted at step 9, I'd expect **nobody** to be able to to retrieve the _super-secret secret_ without any (paper-written) copy of the original OTP Yubikey secret.

This means that on opening a database with master password-only, I'd **not** expect **to be able to retrieve previous OTP secrets**!

## Expected behavior (working)
What I would expect is, that with a fresh Yubikey and PwSafe and **a known (noted-down) OTP secret string** I can re-program a empty Yubikey  to re-access Yubikey-protected databases like `nsa-backup.psafe3`. This is working.

Did I get something wrong here?

**Comment by ronys** [comment]
Thanks for the detailed writeup. I was sure the design of Yubikey support was written somewhere - I'll have to dig it up and update the published documents.
In any case:
1.  Yubikey's used in HMAC-SHA1 mode with the HMAC key being set in the yubikey at initialization time. The effective password of a Yubikey-protected database is HMAC(SHA1, ykey, passphrase) where ykey is the key stored on Yubikey, and passphrase is the user-entered passphrase.
2. The ykey value is also stored in the PasswordSafe file in order to support programming a backup Yubikey. As long as Yubikey is used to access the database, this is secure.
3. As soon as the Yubikey protection is removed from the database, the stored Yubikey secret is indeed exposed. We can erase it when removing the Yubikey protection. This should close the loophole you've detected. Or am I missing something?

**Comment by bentolor** [comment]
Hello @ronys ! Thanks for you feedback and explanation.

1. So do I get it right? In "typical" OTP usage scenario, the message is changing every time. Pwsafe keeps using the same message (read: user password)?
Hence the result of _HMAC(SHA1, ykey, passphrase)_  is always the same, final "effective password".
I wonder: Given I noted down the secure key: Is there a simple way (i.e. CLI tool) to replicate this process without a Yubikey? Is the HMAC result printable? So would I be able to manually input the result into pwsafe?
2. I assumed this background. 
As this stores the key in software, personally I'd not call it "as" secure in comparison to exclusively storing the secret only inside the Yubikey hardware enclave. I understand that _not persistently storing_ the secret would require to change all yubikeys in one session, to create backup yubikeys.
3. IMHO erasing the secret on removing the yubikey mostly tackles my issue. 
As describe in 2) I still have mixed feelings with the approach to store the secret also inside the software safe. As expert user I'd love an option to not store the secret inside pwsafe. But I think the overall UX is already cumbersome enough, so complicating it even more might not helpful.

**Comment by ronys** [comment]
OTP is fine when you need it only for authentication, such as when authenticating against a remote server. If PasswordSafe were to use an OTP from Yubikey (or any other OTP system), it would be trivial for an attacker to build a version that bypasses the authentication check.
Therefore we're using the HMAC key that's securely stored in the device as a component in the encryption key derivation, along with the passphrase, via HMAC-SHA1. The added strength of this system (as opposed to passphrase-only) relies on the inaccessibility of the secret stored in the Yubikey device.
As to storing the secret in the PasswordSafe file, well, if the attacker can get that, then it's already game-over as far as the data protected in that file, and of course as an expert you wouldn't use the same Yubikey to protect multiple files, right?

**Comment by bentolor** [comment]
Yes: Maybe I missunderstood things. I assumed, that the HMAC-Schema is also used for OTP purposes by other application.
Nevertheless: I get the overall pwsafe design and agree with that.

I had the same thought: If an attacker can get old of the stored secret he probably also got access to the stored passwords. That's for sure.
*But*: The **main value proposition** of an **hardware token** is, that your secrets are **bound to that hardware**. Meaning: your secrets are no more accessible and can no longer be retrieved.

The pwsafe approach breaks with this as soon as it starts to keep storing a copy of that hardware-bound secret in software.

> As an expert you wouldn't use the same Yubikey to protect multiple files, right?

I wouldn't agree with that for pwsafe. Especially if pwsafe would not copy the secret. 
In the current case it's at least less troublesome, because the passwords would be different.. 

As the hardware enclave property of slot 2 is compromised, you definitely should _not reuse_ the secret for _other applications_. Sure.

#### To wrap up my point-of-view

* I think the secret **must** be deleted from pwsafe after yubikey removal and
* I think the secret **should** not be permanently stored outside the yubikey, **but** I'd think that **it's acceptable** as UX tradeoff and given the much larger overall impact of a compromised pwsafe database

**Comment by ronys** [comment]
Fixed in commit 955e1bbe0
