### ISSUE TITLE
some info on removing ubuntu apt installed package and installing latest .deb?

### ISSUE THREAD

**Issue by knormoyle** [pwsafe/pwsafe#719]
Hi, 
This is just some minor info that might useful for anyone doing a ubuntu install.
I had done an apt install of the passwordsafe package, and got an old beta release. (ubuntu 20.04.02 focal fossa)
I had to uninstall that and install the latest deb package.

There are some other packages that aren't installed by the deb, nor removed cleanly by the apt remove of passwordsafe.
Not a big deal, just thought I'd document it.

here's what I did. Seems to work. I have release v1.12 installed now (Build date Oct 31, 2020)
Nice!
```
# to remove any package installed via apt
sudo apt-get remove passwordsafe passwordsafe-common

# these will show up recommended to be auto removed by above remove
# remove them directly
sudo apt remove libykpers-1-1 libqrencode4 libyubikey-udev libyubikey0

# there shouldn't be any autoremoves left?
sudo apt autoremove

# install them back. Just wanted to do it all cleanly.
sudo apt reinstall libykpers-1-1  libqrencode4 libyubikey-udev libyubikey0

# this release will be what we use
# https://github.com/pwsafe/pwsafe/releases/tag/1.12.0

# I'm assuming the ubuntu20 is for all ubuntu 20.x releases?
rm -f ./passwordsafe-ubuntu20-1.12-amd64.deb
wget --no-check-certificate https://github.com/pwsafe/pwsafe/releases/download/1.12.0/passwordsafe-ubuntu20-1.12-amd64.deb
sudo dpkg -i ./passwordsafe-ubuntu20-1.12-amd64.deb

```

**Comment by ronys** [comment]
Thanks,

Note that the passwordsafe deb that's on the "official" Debian repos is packaged by someone else - the debs on GitHub don't break things out into passwordsafe and passwordsafe-common.
