### ISSUE TITLE
[wx] Drag&Drop of an already existing item blocks the application

### ISSUE THREAD

**Issue by rafaelx** [pwsafe/pwsafe#725]
Drag and drop an item onto another instance and then drag and drop the newly created item back to the original instance.
Now the user interface of the drop target shows no response to user input.

**Comment by KaiZin2018** [comment]
Sorry, I cannot reproduce with wxWidgets in macOS environment. Please use version compiled with DEBUG and log syslog of pwSafe process.
Something like

> 2021-03-07 19:54:54.900156+0100  localhost pwsafe[1181]: TreeCtrl::OnDrag Start
> 2021-03-07 19:54:56.824166+0100  localhost pwsafe[1190]: TreeCtrl::OnDrop to path ''
> 2021-03-07 19:54:56.826863+0100  localhost pwsafe[1190]: TreeCtrl::OnDrop return 'wxDragMove'
> 2021-03-07 19:54:56.835904+0100  localhost pwsafe[1181]: TreeCtrl::OnDrag Move
> 2021-03-07 19:54:59.546401+0100  localhost pwsafe[1190]: TreeCtrl::OnDrag Start
> 2021-03-07 19:55:02.394452+0100  localhost pwsafe[1181]: TreeCtrl::OnDrop to path ''
> 2021-03-07 19:55:02.397267+0100  localhost pwsafe[1181]: TreeCtrl::OnDrop return 'wxDragMove'
> 2021-03-07 19:55:02.402635+0100  localhost pwsafe[1190]: TreeCtrl::OnDrag Move

should be visible.
