### ISSUE TITLE
Build fails against wxWidgets-3.1.4

### ISSUE THREAD

**Issue by tinker2much** [pwsafe/pwsafe#729]
Because I saw that the latest git and at least 3.14 wxWidgets fixed the 605 issue on my Mac, I wanted to try the same combination on my Pi too, to keep features in sync. But it doesn't build. 

NOTE: Raspberry Pi OS is basically a modified Debian Buster. pi8 is a Pi Model 4 with 8GB memory running off a 480GB SSD.

uname -a: Linux pi8 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux

NOTE: pwsafe commit 4801cbff1

        downloaded 3.14 source for building from scratch
                wxWidgets-3.1.4.tar.bz2
        followed build instructions at /home/pi/Documents/wxWidgets-3.1.4/docs/gtk/install.md
        mkdir buildgtk
        cd buildgtk
        ../configure --with-gtk
            Got: "Configured wxWidgets 3.1.4 for `armv7l-unknown-linux-gnueabihf'"
        make -j 4
        ran forever, but apparently successfully
    back to pwsafe and try their cmake instructions
        mkdir build
        cd build
        cmake -D CMAKE_BUILD_TYPE=Release -D NO_QR=ON -D NO_YUBI=ON -D NO_GTEST=ON -D wxWidgets_CONFIG_EXECUTABLE=~/Documents/wxWidgets-3.1.4/buildgtk/wx-config ..
        make -j4
        that FAILS

    [ 67%] Linking CXX executable pwsafe-cli
    [ 67%] Building CXX object CMakeFiles/pwsafe.dir/src/ui/wxWidgets/PasswordSafeSearch.cpp.o
    [ 68%] Building CXX object CMakeFiles/pwsafe.dir/src/ui/wxWidgets/SystemTray.cpp.o
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp: In member function \u2018void PasswordSafeSearch::OnSearchTextChanged(wxCommandEvent&)\u2019:
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp:96:13: error: \u2018class wxSearchCtrl\u2019 has no member named \u2018SetModified\u2019; did you mean \u2018SetPosition\u2019?
       srchCtrl->SetModified(true);
                 ^~~~~~~~~~~
                 SetPosition
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp: In member function \u2018void PasswordSafeSearch::OnDoSearchT(Iter, Iter, Accessor)\u2019:
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp:125:40: error: \u2018class wxSearchCtrl\u2019 has no member named \u2018GetLineText\u2019; did you mean \u2018GetLabelText\u2019?
       const wxString searchText = txtCtrl->GetLineText(0);
                                            ^~~~~~~~~~~
                                            GetLabelText
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp:131:41: error: \u2018class wxSearchCtrl\u2019 has no member named \u2018IsModified\u2019; did you mean \u2018IsUnlinked\u2019?
       if (m_criteria->IsDirty() || txtCtrl->IsModified() || m_searchPointer.IsEmpty()) {
                                             ^~~~~~~~~~
                                             IsUnlinked
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp:154:14: error: \u2018class wxSearchCtrl\u2019 has no member named \u2018SetModified\u2019; did you mean \u2018SetPosition\u2019?
         txtCtrl->SetModified(false);
                  ^~~~~~~~~~~
                  SetPosition
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp: In member function \u2018void PasswordSafeSearch::OnToolBarFindReport(wxCommandEvent&)\u2019:
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp:417:40: error: \u2018class wxSearchCtrl\u2019 has no member named \u2018GetLineText\u2019; did you mean \u2018GetLabelText\u2019?
       const wxString searchText = txtCtrl->GetLineText(0);
                                            ^~~~~~~~~~~
                                            GetLabelText
    make[2]: *** [CMakeFiles/pwsafe.dir/build.make:115: CMakeFiles/pwsafe.dir/src/ui/wxWidgets/PasswordSafeSearch.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/pwsafe.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 68%] Built target pwsafe-cli
    make: *** [Makefile:163: all] Error 2

**Comment by ronys** [comment]
I'd be surprised if the error are due to the different architecture - more likely an incompatible change in the wx switching from 3.0.x to 3.1.x
Can you build the same wx 3.1.4 + pwsafe on an x64 Debian distro?

**Comment by KaiZin2018** [comment]
There is a conditional compilation/class dependency tree of wxSearchCtrl derived classes.
Proposal:
- SetModified()/IsModified() handled in PasswordSafeSearch class locally by own boolean variable
- Usage of GetValue() instead of GetLineText(0) - we do have only one line. On enter a new search is activated.

**Comment by tinker2much** [comment]
Does this help? 

    20210315    I tried to build the latest pwsafe and the recent 3.14 wxWidgets on x86
    That latest pwsafe from git and at least 3.14 wxWidgets fixes the issue on Mac, so I wanted to try here too
    NOTE: also that same pwsafe plus 3.05 wxWidgets doesn't work here... 

    This is an ex-Chromebook, Acer Chromebook 11 CB3-111, x86, 2GB memory, 16GB storage
        running a Debian Buster variant (Raspberry Pi Desktop for PC and Mac)
    uname -a: Linux piacer 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

    downloaded the wxWidgets 3.14 source for building from scratch
        wxWidgets-3.1.4.tar.bz2
    followed build instructions at /home/pi/Documents/wxWidgets-3.1.4/docs/gtk/install.md
        mkdir buildgtk
        cd buildgtk
        ../configure --with-gtk
        make -j 2
        ran forever (approx 1/2 hour), but apparently successfully
    back to pwsafe and try their cmake instructions
        mkdir build
        cd build
        cmake -D CMAKE_BUILD_TYPE=Release -D NO_QR=ON -D NO_YUBI=ON -D NO_GTEST=ON -D wxWidgets_CONFIG_EXECUTABLE=~/Documents/wxWidgets-3.1.4/buildgtk/wx-config ..
        make -j2
        that FAILS

    [ 66%] Building CXX object CMakeFiles/pwsafe.dir/src/ui/wxWidgets/AddEditPropSheetDlg.cpp.o
    [ 67%] Linking CXX executable pwsafe-cli
    [ 67%] Building CXX object CMakeFiles/pwsafe.dir/src/ui/wxWidgets/PasswordSafeSearch.cpp.o
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp: In member function ‘void PasswordSafeSearch::OnSearchTextChanged(wxCommandEvent&)’:
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp:96:13: error: ‘class wxSearchCtrl’ has no member named ‘SetModified’; did you mean ‘SetPosition’?
       srchCtrl->SetModified(true);
                 ^~~~~~~~~~~
                 SetPosition
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp: In member function ‘void PasswordSafeSearch::OnDoSearchT(Iter, Iter, Accessor)’:
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp:125:40: error: ‘class wxSearchCtrl’ has no member named ‘GetLineText’; did you mean ‘GetLabelText’?
       const wxString searchText = txtCtrl->GetLineText(0);
                                            ^~~~~~~~~~~
                                            GetLabelText
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp:131:41: error: ‘class wxSearchCtrl’ has no member named ‘IsModified’; did you mean ‘IsUnlinked’?
       if (m_criteria->IsDirty() || txtCtrl->IsModified() || m_searchPointer.IsEmpty()) {
                                             ^~~~~~~~~~
                                             IsUnlinked
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp:154:14: error: ‘class wxSearchCtrl’ has no member named ‘SetModified’; did you mean ‘SetPosition’?
         txtCtrl->SetModified(false);
                  ^~~~~~~~~~~
                  SetPosition
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp: In member function ‘void PasswordSafeSearch::OnToolBarFindReport(wxCommandEvent&)’:
    /home/pi/Documents/pwsafe/src/ui/wxWidgets/PasswordSafeSearch.cpp:417:40: error: ‘class wxSearchCtrl’ has no member named ‘GetLineText’; did you mean ‘GetLabelText’?
       const wxString searchText = txtCtrl->GetLineText(0);
                                            ^~~~~~~~~~~
                                            GetLabelText
    make[2]: *** [CMakeFiles/pwsafe.dir/build.make:115: CMakeFiles/pwsafe.dir/src/ui/wxWidgets/PasswordSafeSearch.cpp.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:236: CMakeFiles/pwsafe.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 67%] Built target pwsafe-cli
    make: *** [Makefile:163: all] Error 2
    
    real    3m7.635s
    user    5m46.160s
    sys    0m17.263s

**Comment by KaiZin2018** [comment]
For continue port to PI you might try following patch
```
diff --git a/src/ui/wxWidgets/PasswordSafeSearch.h b/src/ui/wxWidgets/PasswordSafeSearch.h
index a464da837..2de80d9a5 100644
--- a/src/ui/wxWidgets/PasswordSafeSearch.h
+++ b/src/ui/wxWidgets/PasswordSafeSearch.h
@@ -137,6 +137,12 @@ private:
   SelectionCriteria*   m_criteria;
   SearchPointer        m_searchPointer;
   size_t               m_ToolsWidth;
+#if defined(__WXGTK20__)
+  bool                 m_modified;
+  
+  void SetModified(bool modified) { m_modified = modified; }
+  bool IsModified() { return m_modified; }
+#endif
 };
 
 #endif // _PASSWORDSAFESEARCH_H_
```
and
```
diff --git a/src/ui/wxWidgets/PasswordSafeSearch.cpp b/src/ui/wxWidgets/PasswordSafeSearch.cpp
index e663cdf68..2970751d9 100644
--- a/src/ui/wxWidgets/PasswordSafeSearch.cpp
+++ b/src/ui/wxWidgets/PasswordSafeSearch.cpp
@@ -78,6 +78,9 @@ PasswordSafeSearch::PasswordSafeSearch(PasswordSafeFrame* parent) : m_toolbar(nu
                                                                     m_parentFrame(parent),
                                                                     m_criteria(new SelectionCriteria)
 {
+#if defined(__WXGTK20__)
+  m_modified = false;
+#endif
 }
 
 PasswordSafeSearch::~PasswordSafeSearch()
@@ -91,9 +94,14 @@ PasswordSafeSearch::~PasswordSafeSearch()
 
 void PasswordSafeSearch::OnSearchTextChanged(wxCommandEvent& event)
 {
+#if !defined(__WXGTK20__)
   wxSearchCtrl *srchCtrl = wxDynamicCast(event.GetEventObject(), wxSearchCtrl);
   wxCHECK_RET(srchCtrl, wxT("Could not get search control of toolbar"));
   srchCtrl->SetModified(true);
+#else
+  WXUNUSED(event);
+  SetModified(true);
+#endif
 }
 
 /*!
@@ -122,13 +130,23 @@ void PasswordSafeSearch::OnDoSearchT(Iter begin, Iter end, Accessor afn)
   wxSearchCtrl* txtCtrl = wxDynamicCast(m_toolbar->FindControl(ID_FIND_EDITBOX), wxSearchCtrl);
   wxCHECK_RET(txtCtrl, wxT("Could not get search control of toolbar"));
 
+#if !defined(__WXGTK20__)
   const wxString searchText = txtCtrl->GetLineText(0);
+#else
+  const wxString searchText = txtCtrl->GetValue();
+#endif
 
   if (searchText.IsEmpty()) {
     return;
   }
 
-  if (m_criteria->IsDirty() || txtCtrl->IsModified() || m_searchPointer.IsEmpty()) {
+  if (m_criteria->IsDirty() ||
+#if !defined(__WXGTK20__)
+      txtCtrl->IsModified() ||
+#else
+      IsModified() ||
+#endif
+      m_searchPointer.IsEmpty()) {
     m_searchPointer.Clear();
 
     if (!m_toolbar->GetToolState(ID_FIND_ADVANCED_OPTIONS)) {
@@ -151,7 +169,11 @@ void PasswordSafeSearch::OnDoSearchT(Iter begin, Iter end, Accessor afn)
     }
 
     m_criteria->Clean();
+#if !defined(__WXGTK20__)
     txtCtrl->SetModified(false);
+#else
+    SetModified(false);
+#endif
     m_searchPointer.InitIndex();
 
     // Set last find filter
@@ -414,7 +436,11 @@ void PasswordSafeSearch::OnToolBarFindReport(wxCommandEvent& event)
   wxSearchCtrl* txtCtrl = wxDynamicCast(m_toolbar->FindControl(ID_FIND_EDITBOX), wxSearchCtrl);
   wxCHECK_RET(txtCtrl, wxT("Could not get search control of toolbar"));
 
+#if !defined(__WXGTK20__)
   const wxString searchText = txtCtrl->GetLineText(0);
+#else
+  const wxString searchText = txtCtrl->GetValue();
+#endif
 
   if (searchText.IsEmpty()) {
     return;
```
I assume the compilation is done with __WXGTK20__, if not you might use this kind of definition as general code, as MacOS is able to handle the function with the same code. I have not the chance to check on other systems, but for your porting it might be ok.

**Comment by KaiZin2018** [comment]
Please double check pull request #733.

Please note that README.LINUX.DEVELOPERS.md is proposing for wxWidgets configuration the following:
../configure --disable-shared --enable-stl --enable-utf8only --enable-intl --enable-xlocale --enable-debug_gdb

In pwsafe cmake preparation had been done as follows:
cmake -D CMAKE_BUILD_TYPE=Debug -D NO_QR=ON -D NO_YUBI=ON -D NO_GTEST=ON -D wxWidgets_CONFIG_EXECUTABLE=/home/pi/Source/wxWidgets/wxWidgets-3.1.4/buildgtk/wx-config ..

**Comment by KaiZin2018** [comment]
Analysis  has shown that GetValue() is present in all alternatives provided for wxSearchCtrlBaseBaseClass (see srchctrl.h). Conditional compiling looks not necessarily.

**Comment by KaiZin2018** [comment]
From my perspective this issue can be closed.

**Comment by tinker2much** [comment]
I tried the above changes to the PasswordSafeSearch code, WITHOUT the conditionality (as shown in my diff below) and everything built and ran for me. Thank you!

    diff --git a/src/ui/wxWidgets/PasswordSafeSearch.cpp b/src/ui/wxWidgets/PasswordSafeSearch.cpp
    index e663cdf68..ff95097c3 100644
    --- a/src/ui/wxWidgets/PasswordSafeSearch.cpp
    +++ b/src/ui/wxWidgets/PasswordSafeSearch.cpp
    @@ -78,6 +78,7 @@ PasswordSafeSearch::PasswordSafeSearch(PasswordSafeFrame* parent) : m_toolbar(nu
                                                                         m_parentFrame(parent),
                                                                         m_criteria(new SelectionCriteria)
     {
    +  m_modified = false;
     }
     
     PasswordSafeSearch::~PasswordSafeSearch()
    @@ -91,9 +92,11 @@ PasswordSafeSearch::~PasswordSafeSearch()
     
     void PasswordSafeSearch::OnSearchTextChanged(wxCommandEvent& event)
     {
    -  wxSearchCtrl *srchCtrl = wxDynamicCast(event.GetEventObject(), wxSearchCtrl);
    -  wxCHECK_RET(srchCtrl, wxT("Could not get search control of toolbar"));
    -  srchCtrl->SetModified(true);
    +  //wxSearchCtrl *srchCtrl = wxDynamicCast(event.GetEventObject(), wxSearchCtrl);
    +  //wxCHECK_RET(srchCtrl, wxT("Could not get search control of toolbar"));
    +  //srchCtrl->SetModified(true);
    +  WXUNUSED(event);
    +  SetModified(true);
     }
     
     /*!
    @@ -122,13 +125,15 @@ void PasswordSafeSearch::OnDoSearchT(Iter begin, Iter end, Accessor afn)
       wxSearchCtrl* txtCtrl = wxDynamicCast(m_toolbar->FindControl(ID_FIND_EDITBOX), wxSearchCtrl);
       wxCHECK_RET(txtCtrl, wxT("Could not get search control of toolbar"));
     
    -  const wxString searchText = txtCtrl->GetLineText(0);
    +  const wxString searchText = txtCtrl->GetValue();
     
       if (searchText.IsEmpty()) {
         return;
       }
     
    -  if (m_criteria->IsDirty() || txtCtrl->IsModified() || m_searchPointer.IsEmpty()) {
    +  if (m_criteria->IsDirty() || 
    +      IsModified() || 
    +      m_searchPointer.IsEmpty()) {
         m_searchPointer.Clear();
     
         if (!m_toolbar->GetToolState(ID_FIND_ADVANCED_OPTIONS)) {
    @@ -151,7 +156,7 @@ void PasswordSafeSearch::OnDoSearchT(Iter begin, Iter end, Accessor afn)
         }
     
         m_criteria->Clean();
    -    txtCtrl->SetModified(false);
    +    SetModified(false);
         m_searchPointer.InitIndex();
     
         // Set last find filter
    @@ -414,7 +419,7 @@ void PasswordSafeSearch::OnToolBarFindReport(wxCommandEvent& event)
       wxSearchCtrl* txtCtrl = wxDynamicCast(m_toolbar->FindControl(ID_FIND_EDITBOX), wxSearchCtrl);
       wxCHECK_RET(txtCtrl, wxT("Could not get search control of toolbar"));
     
    -  const wxString searchText = txtCtrl->GetLineText(0);
    +  const wxString searchText = txtCtrl->GetValue();
     
       if (searchText.IsEmpty()) {
         return;
    diff --git a/src/ui/wxWidgets/PasswordSafeSearch.h b/src/ui/wxWidgets/PasswordSafeSearch.h
    index a464da837..402313964 100644
    --- a/src/ui/wxWidgets/PasswordSafeSearch.h
    +++ b/src/ui/wxWidgets/PasswordSafeSearch.h
    @@ -137,6 +137,10 @@ private:
       SelectionCriteria*   m_criteria;
       SearchPointer        m_searchPointer;
       size_t               m_ToolsWidth;
    +  bool                 m_modified;
    +
    +  void SetModified(bool modified) { m_modified = modified; }
    +  bool IsModified() { return m_modified; }
     };
     
     #endif // _PASSWORDSAFESEARCH_H_

**Comment by ykne** [comment]
Errors on Fedora 34 if latest wxGTK and wxBase-3.1.4 are used:

```
[ 74%] Linking CXX executable pwsafe
/usr/bin/ld: /tmp/cce7avbc.ltrans35.ltrans.o: in function `pwFiltersLCChoiceEditor::BeginEdit(int, int, wxGrid*)':
<artificial>:(.text+0x4e1): undefined reference to `wxGridCellEditorEvtHandler::ms_classInfo'
/usr/bin/ld: /tmp/cce7avbc.ltrans35.ltrans.o: in function `pwFiltersFTChoiceEditor::BeginEdit(int, int, wxGrid*)':
<artificial>:(.text+0x358e): undefined reference to `wxGridCellEditorEvtHandler::ms_classInfo'
collect2: error: ld returned 1 exit status

```
