### ISSUE TITLE
Spurious filter warning

### ISSUE THREAD

**Issue by ronys** [pwsafe/pwsafe#748]
(From David Benini via email)

hi.
I created 2 filters a couple of years ago, which always gave me A "mismatch2 warning for both of them. They never worked well anyway, so I deleted them, but the warning dialogs pop up everytime I open Password Safe, even though there are no filters. I just click OK twice, but it's getting annoying.
I'd hoped someone else would notice the bug (?) but after several new versions, nothing's changed.

**Comment by KaiZin2018** [comment]
Hello, please double check the existing of a file default_filters.xml (could be at the same location as pwsafe.cfg, but location might be also configured differently), which is read each time password safe is started. In addition filter can be stored in the database. For removal open for read/write and delete again.

I hope you can locate the file. Good luck

**Comment by ronys** [comment]
Closing due to lack of feedback from submitter
