### ISSUE TITLE
git pull failure and build problems

### ISSUE THREAD

**Issue by Ben-Voris** [pwsafe/pwsafe#754]
After cloning and building (see <https://github.com/pwsafe/pwsafe/issues/741>), I wanted to check for updates, so I did a simple "git pull", which failed with:

```
: git pull
remote: Enumerating objects: 449, done.
remote: Counting objects: 100% (449/449), done.
remote: Compressing objects: 100% (161/161), done.
remote: Total 449 (delta 338), reused 375 (delta 286), pack-reused 0
Receiving objects: 100% (449/449), 911.38 KiB | 10.60 MiB/s, done.
Resolving deltas: 100% (338/338), completed with 102 local objects.
From https://github.com/pwsafe/pwsafe
   e8856f237..7acb3381d  master      -> origin/master
 + 9aa988113...8c579e907 i18n-arabic -> origin/i18n-arabic  (forced update)
 * [new branch]          pr749       -> origin/pr749
 * [new tag]             3.56.0pre   -> 3.56.0pre
Updating e8856f237..7acb3381d
error: Your local changes to the following files would be overwritten by merge:
	src/ui/wxWidgets/I18N/pos/pwsafe_da.po
	src/ui/wxWidgets/I18N/pos/pwsafe_de.po
	src/ui/wxWidgets/I18N/pos/pwsafe_es.po
	src/ui/wxWidgets/I18N/pos/pwsafe_fr.po
	src/ui/wxWidgets/I18N/pos/pwsafe_hu.po
	src/ui/wxWidgets/I18N/pos/pwsafe_it.po
	src/ui/wxWidgets/I18N/pos/pwsafe_ko.po
	src/ui/wxWidgets/I18N/pos/pwsafe_nl.po
	src/ui/wxWidgets/I18N/pos/pwsafe_pl.po
	src/ui/wxWidgets/I18N/pos/pwsafe_ru.po
	src/ui/wxWidgets/I18N/pos/pwsafe_sv.po
	src/ui/wxWidgets/I18N/pos/pwsafe_zh.po
Please commit your changes or stash them before you merge.
Aborting
```

I clone this repo, followed the build instructions given in <https://github.com/pwsafe/pwsafe/issues/741#issuecomment-857988876>, and have modified no files. I "fixed" this with `git checkout -- src/ui/wxWidgets/I18N/pos/pwsafe_*.po` So, I suspect the cmake modified them. Can you  say why these files were changed?

The above files do not exist after a fresh `rm -rf build/ && mkdir build; cd build && cmake -D CMAKE_BUILD_TYPE=Debug ../ && make` so this issue may be moot.

I note that [README.CMAKE.md](https://github.com/pwsafe/pwsafe/blob/master/README.CMAKE.md) add running `cmake-gui` to the instructions in <https://github.com/pwsafe/pwsafe/issues/741#issuecomment-857988876>. I'm unfamiliar with this tool and would appreciate it if the instructions said what one input one must provide. (Naively, it appears that running this program is not necessary.)

**Comment by ronys** [comment]
The toplevel make updates the .po files in the source tree by default, and that's what you're seeing.
If you stick to the cmake build process (*), the source tree should be unaffected.

$ cd cloned-pwsafe-directory
$ mkdir build; cd build; cmake ..
$ make
$ make test
$ ./pwsafe
Source tree should still be clean.

cmake-gui is just an easy way to see and set the various build options, e.g., CMAKE_BUILD_TYPE. Nothing there that can't be done via arguments to cmake.

**Comment by Ben-Voris** [comment]
So these files might've been secondary to the failed make I did before￼ I knew to use cmake?

**Comment by ronys** [comment]
Looks like it
