### ISSUE TITLE
Linux: Losing all edits if information is missing when creating new entry

### ISSUE THREAD

**Issue by linuscorin** [pwsafe/pwsafe#759]
This seems to be a new issue, and doesn't affect the Windows version.

If you create a new entry, but forget to add title or username, or if the passwords don't match, then you don't get a second chance. 

The "Add entry" window is just closed, and any input made in other fields is discarded. This is especially annoying if you've just typed some long text in the "Notes" field ;-)

I'm pretty sure that the Linux version used to work the same as on Windows. It displays a warning, refuses to save the entry, but lets you keep editing to fix it.

**Comment by ronys** [comment]
Thanks for reporting this regression. Fixed in commit ab98b1781, will be in next release.
