### ISSUE TITLE
pwsafe completely crashes LinuxMint 20.2

### ISSUE THREAD

**Issue by thomas-haslwanter** [pwsafe/pwsafe#766]
I have not been able to get pwsafe to run on my Linux Mint installation, since I have upgraded to Mint 20.2. Whenever I get it to start the GUI, it often (but not always) completely locks up Linux, with the exception of the cursor movement with the mouse (i.e. I have to turn Linux off through the power switch - which I have never experienced before!)

I don't have much experience on Linux, so I really would appreciate suggestions on how / which version of pwsafe I should try, how to install it - and maybe let me know if I have to compile it from the source.
Have tried miscellaneous ways of installation. For example, when I install from the command line (as suggested by the help), I get the terminal output:
>>>

> base) thomas@AORUS:~$ sudo apt install passwordsafe
> [sudo] password for thomas:       
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following packages were automatically installed and are no longer required:
>   libllvm11 linux-headers-5.4.0-70 linux-headers-5.4.0-70-generic
>   linux-image-5.4.0-70-generic linux-modules-5.4.0-70-generic
>   linux-modules-extra-5.4.0-70-generic mint-backgrounds-ulyssa
> Use 'sudo apt autoremove' to remove them.
> The following additional packages will be installed:
>   passwordsafe-common
> The following NEW packages will be installed:
>   passwordsafe passwordsafe-common
> 0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
> Need to get 8.448 kB/9.560 kB of archives.
> After this operation, 14,3 MB of additional disk space will be used.
> Do you want to continue? [Y/n] y
> Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 passwordsafe-common all 1.08.2+dfsg-1 [8.448 kB]
> Fetched 8.448 kB in 2s (3.928 kB/s)              
> Selecting previously unselected package passwordsafe-common.
> (Reading database ... 418684 files and directories currently installed.)
> Preparing to unpack .../passwordsafe-common_1.08.2+dfsg-1_all.deb ...
> Unpacking passwordsafe-common (1.08.2+dfsg-1) ...
> Selecting previously unselected package passwordsafe.
> Preparing to unpack .../passwordsafe_1.08.2+dfsg-1_amd64.deb ...
> Unpacking passwordsafe (1.08.2+dfsg-1) ...
> Setting up passwordsafe-common (1.08.2+dfsg-1) ...
> Setting up passwordsafe (1.08.2+dfsg-1) ...
> Processing triggers for mime-support (3.64ubuntu1) ...
> Processing triggers for hicolor-icon-theme (0.17-2) ...
> Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
> Processing triggers for man-db (2.9.1-1) ...
> Processing triggers for desktop-file-utils (0.24+linuxmint1) ...

>>>
And when I try to run it from the terminal, again, everything freezes - apart from the mouse

**Comment by cmbr** [comment]
For what it's worth, I'm running an old version 1.8.02 BETA of PasswordSafe on Linux Mint 20.2 Cinnamon. The computer is a Lenovo T430. PasswordSafe is working as expected.

**Comment by ronys** [comment]
Odd. Whatever the problem, it shouldn't result in the GUI locking up like that.
I've created a dedicated package for Linux Mint 20. To install it you need to first uninstall the package you've install via 'sudo apt remove passwordsafe'. Then download the package from https://pwsafe.org/1.14pre/passwordsafe-linuxmint20-1.14-amd64.deb and install it using 'sudo dpkg -i passwordsafe-linuxmint20-1.14-amd64.deb'
You can verify the authenticity of the package via https://pwsafe.org/1.14pre/passwordsafe-linuxmint20-1.14-amd64.deb.sig if you wish.
Let me know how it goes.

**Comment by ronys** [comment]
Closing due to lack of response - no way to move forward.
