### ISSUE TITLE
Move language files to Transiflex

### ISSUE THREAD

**Issue by bovirus** [pwsafe/pwsafe#768]
@ronys 

Please consider to move .po language files

https://github.com/pwsafe/pwsafe/tree/master/src/ui/Windows/I18N/pos

to Transiflex.
It's free of charge.
And also the tramnslator can be notify about any changes on language files

Thanks.

**Comment by ronys** [comment]
Looks interesting. I've added transifex integration to the project. Care to set it up and submit a pull request?

**Comment by bovirus** [comment]
@ronys 

I'm so sorry but I  don't know how to do that.

For me you can ask to Maxstupo that made more or less the same job here

https://github.com/Maxstupo/ydl-ui

**Comment by ronys** [comment]
OK, I think I've set it up correctly. Drop me a note if you'd like to update a translation (Italian?):

ronys at pwsafe dot org

**Comment by bovirus** [comment]
@ronys 

Could you please provide me the link to transiflex page of your project?

**Comment by bovirus** [comment]
@ronsys

The link 

https://www.transifex.com/passwordsafe/passwordsafe/translate/

report 404 page not found.

probably the right link for Passwordsafe Transifelx page is

https://www.transifex.com/passwordsafe/passwordsafe/

I propose you to mention this link in readme file of github repository

https://github.com/pwsafe/pwsafe

You can also add green tag as made Maxstupo in the github repository

https://github.com/Maxstupo/ydl-ui

Thanks. KR.
