### ISSUE TITLE
Does not stay minimised to tray Mint 20.2 & V1.14

### ISSUE THREAD

**Issue by IanBlakeley** [pwsafe/pwsafe#784]
Upgraded to V1.14 from V1.13. After minimising to tray when the time expires and the database locks the app pops back to the task bar requesting password and cannot be cancelled.

Linux Mint 20.2 
`5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by KaiZin2018** [comment]
This behaviour can be explained. The application might have a modal dialog open when minimised. In this case the menu to select restore is disabled, therefore the password dialog is opened to avoid a blocked application. You might change the option "Put icon in System Tray" beneath system settings to not getting this dialog.

**Comment by rafaelx** [comment]
This could be related to #811 and may be solved by #804.

**Comment by IanBlakeley** [comment]
Can confirm with V1.15 I no longer see this issue.
