### ISSUE TITLE
Feature request: Add "Open Password Database" dropdown to "Enter Safe Combination" dialog

### ISSUE THREAD

**Issue by thelem** [pwsafe/pwsafe#785]
I have a few different password safe databases that I regularly switch between, but only tend to have one unlocked at any one time. When I am finished with my safe I will lock it but keep the application running in the system tray.

Next time I want to retrieve a password, I double click the icon in the system tray. This will open the "Enter Safe Combination" dialog, which tells me which safe I am opening and has a field for the safe combination and a couple of checkboxes. If I want to open the same safe this is great, but there is no way of easily opening another safe.

If I start Password Safe from the start menu I get the "Safe Combination Entry". This has the same features as the Enter Safe Combination dialog, but also:
* Password Safe logo and version number
* Dropdown to choose a recently used Password Database
* Button to create a new Password Database

If you just want to unlock your active database, then both dialogs are equally easy to use, but given the additional functionality of the Safe Combination Entry dialog it would be good to use it everywhere.

**Comment by ronys** [comment]
I like the idea of enabling a quick switch from one database to another. What about adding another entry in the system tray icon's popup menu: "Open another safe" that would invoke the "Safe Combination Entry" dialog that allows you to choose another database?
This would keep the simplicity of the existing setup while providing the functionality you're asking for.

**Comment by thelem** [comment]
That would work too.

Personally I think both dialogs are pretty simple so I'd go for the consistency of only having one dialog that is used in both scenarios. But it's not my project - I'd also be a happy user if there was an extra option in the system tray menu.
![image](https://user-images.githubusercontent.com/526619/140821531-72c343ea-cead-40af-979c-45761f6aa192.png)
![image](https://user-images.githubusercontent.com/526619/140821747-44aaa0af-ee06-4847-89c5-82c1207e687d.png)

**Comment by ronys** [comment]
I've added "Open Another" to the system tray popup menu in commit 76758cb63. Will be in next release.
