### ISSUE TITLE
[linux] Version 0.98.1BETA fails to compile: 'double' operand to binary 'operator <<'

### ISSUE THREAD

**Issue by sguazt** [pwsafe/pwsafe#79]
Hi,

On Fedora 23 x86_64 (gcc 5.3.1 20151207 (Red Hat 5.3.1-2)), I've got this error:

```
pwsafeapp.cpp:278:62: error: invalid operands of types 'double' and 'int' to binary 'operator<<'  
                                      DWORD((MINORVERSION << 16) | MAJORVERSION));

```
I've fixed it by adding a cast to `int` in front of `MINORVERSION`:

```
  m_core.SetApplicationNameAndVersion(tostdstring(pwsafeAppName),
                                      DWORD(((int) MINORVERSION << 16) | MAJORVERSION));

```

Best,

Marco

**Comment by ronys** [comment]
Very odd. Building using cmake works fine, but the toplevel make indeed fails as you've described. Need to investigate this further, but meanwhile I've built an Rpm and uploaded it to https://github.com/pwsafe/pwsafe/releases/tag/0.98.1BETA

**Comment by ronys** [comment]
Fixed in commit eea4ef6. Best to run 'make clean' after pulling the commit and before running 'make'.

**Comment by sguazt** [comment]
Thanks!

**Comment by namarrgon** [comment]
Will there be a .1 release with this soon-ish or should we just patch 0.98 with that commit?

**Comment by ronys** [comment]
Actually, this is the .1 release!

**Comment by namarrgon** [comment]
Ah, sorry, i meant .2 of course; forgot that the linux release lagged behind. I'll just apply the commit on top of .1.

**Comment by ronys** [comment]
I don't think this issue justifies bumping the version.
