### ISSUE TITLE
[wx] After reopening a locked DB after idle the previously opened unsaved entry is lost

### ISSUE THREAD

**Issue by Karneades** [pwsafe/pwsafe#803]
Hi Rafael and Rony
Hi @bblough 

_I searched through the issues and also on sourceforge, didn't find any thing new related to idle and opend entries._

On a Debian system, after reopening a DB after idle an unsaved "new entry" dialog is not visible anymore and the values are lost. This affects at least Debian 11 with version 1.12 and newest 1.14.

Unsure if this is "by design" or if it worked in the past.

Expected behavior
* Dialog is still open after idle like it is with already saved opened entries

Steps to reproduce:
1. Open DB with write access
2. Clicking "new entry" and filling some values without saving
3. Drink a tea, translate some missing values or improve a text in https://www.transifex.com/passwordsafe/passwordsafe/ and wait until idle time passes
4. when the DB gets locked after idle, reopen the DB
5. the unsaved new entry dialog is not visible and pwsafe is not responding anymore

**Comment by KaiZin2018** [comment]
Not reproducible in MacOS. Which settings in options are selected, e.g. is the tray icon shown?

**Comment by Karneades** [comment]
@KaiZin2018 ?what happens when you reopen after idle? just to be clear, it only affects UNsaved new entry dialogs.

**Comment by rafaelx** [comment]
Unfortunately, I can not reproduce it on Debian 11 with X11 as display server and pwsafe compiled with Gtk3.
No matter whether the "put icon in system tray" is enabled or not, after unlocking the database, the Add / Edit dialog appears with all previously entered data.

**Comment by Karneades** [comment]
Ok, thanks, Rafael. I click „new entry“ and while unsaved new dialog is still open without ever saving the new entry, I let pwsafe went into idle which locks the db and then unlock the db. then pwsafe is unresponding. but if you do that and it works, then I‘m really not sure what it can be. tested on x11 too.

**Comment by bblough** [comment]
I think this is related to (or maybe duplicate of) #559

I've had this happen before, but not lately.  I just tried to reproduce it with the version I have installed on this system (1.12, Debian 11) and couldn't get it to happen.  So while the idle/timeout may be related, there may be something else that factors in.

**Comment by Karneades** [comment]
@bblough I looked at that issue before opening this one, but was then unsure if it relates. but after reading it again, it seems very similar. I had no issues for years but it started lately. I close this issue now.

**Comment by rafaelx** [comment]
@Karneades If you can always reproduce this behavior, then could you test to see if #804 fixes the problem?
