### ISSUE TITLE
Can't exit a locked, unmodified password safe. Unlock UI disables 'Quit'-Button [Linux, v.1.14]

### ISSUE THREAD

**Issue by bentolor** [pwsafe/pwsafe#811]
I think this behaviour has changed: Under Linux if you open a safe and directly (w/o any modifications) lock the safe, the unlock dialogue no longer allows to click "Quit" to simply close the safe & application. I remember that this worked in earlier versions. I mostly stumble over this issue on auto-locked safes.

The _only way_ to get out of this situation w/o retyping you password is: 
1. Minimized the app and then 
2. Close it via right-click  > close.

Might be very loosely related to #358. Any idea what might have changed?

## How to reproduce

1. Open & Unlock a safe
2. Close & minimize it with Ctrl+J
3. Click on Password Safe Icon: Only `[Ok]`, `[Abort]` and `[Help]` are enabled. `[Quit]` is visible, but disabled.

**Comment by hdfssk** [comment]
This prevents closing a locked safe, which is annoying when the safe combination prompt dialog
- pops up immediately on safe lock,
- reopens itself if it’s closed without unlocking the safe,
- gets buried under other windows if password's not entered, &
- does not raise itself when the safe’s clicked on in the system tray.

I looked into this after 1.14 came out, so here's some context for the change:
- The dialog’s created by the `SafeCombinationPromptDlg` class, in `src/ui/wxWidgets/SafeCombinationEntryDlg.cpp`.
- _In 1.14_, its constructor takes an `allowExit` parameter (line 78), and its `CreateControls` method disables the Quit/Exit button if that’s not true (lines 244-245). `src/ui/wxWidgets/PasswordSafeFrame.cpp` lines 2397-2399, where this dialog is sometimes made with a true `allowExit`, comments “Allow Exit only in case of one modal dialog present - on second one we crash. In most of the cases only one modal dialog is open.” However,
- [The latest master’s version of `src/ui/wxWidgets/SafeCombinationEntryDlg.cpp`](https://github.com/pwsafe/pwsafe/blob/39f9525a/src/ui/wxWidgets/SafeCombinationEntryDlg.cpp) doesn’t contain any references to allowExit or conditionally disable the Quit/Exit button. This version of the constructor matches its signature as declared in [`src/ui/wxWidgets/SafeCombinationEntryDlg.h`](https://github.com/pwsafe/pwsafe/blob/39f9525a/src/ui/wxWidgets/SafeCombinationEntryDlg.h) (lines 79-80). The 1.14 version of the constructor does not - in fact, SafeCombinationEntryDlg.h is unchanged between 1.14 and the current master. Confusingly, [current master’s `src/ui/wxWidgets/PasswordSafeFrame.cpp`](https://github.com/pwsafe/pwsafe/blob/39f9525a/src/ui/wxWidgets/PasswordSafeFrame.cpp) lines 2397-2399 still conditionally initializes `allowExit` with the same explanatory comment, and the other three places where a SafeCombinationEntryDlg variable is created always initialize `allowExit` to false (which shouldn’t work anymore, as that constructor parameter now expects a `wxString&` to set the caption).

So it seems like the Quit/Exit disabling’s been partially removed from the source. As long as the four SafeCombinationEntryDlg variable creations are updated, the next linux release will hopefully fix this issue.

**Comment by rafaelx** [comment]
Pull Request #804 already addresses this issue.

**Comment by bentolor** [comment]
Also thank you very much @hdfssk for you in-depth and timely investigation and extensive explanation. I must confess, though I'm a a Java developer, the details turned out much more complex than I anticipated.

Glad that a fix is already underway. Again - thanks for you work & support, @hdfssk & @rafaelx !

**Comment by rafaelx** [comment]
Is the problem still reproducible with version 1.15?

**Comment by bentolor** [comment]
@rafaelx Thanks for asking! In fact I installed 1.15 right away can can happily confirm, that the issue is fixed & resolved!

Again also many thanks to @hdfssk for deep-diving into the rather surprising complex titbits which cause the issue.
