### ISSUE TITLE
Link fails on raspberry pi, latest pwsafe code, latest wxWidgets

### ISSUE THREAD

**Issue by tinker2much** [pwsafe/pwsafe#825]
Building on a Raspberry Pi 4 with 4GB memory. I have the latest pwsafe code, git cloned today. 

I first installed gtk3 as follows:

sudo apt install libgtk-3-dev

I then downloaded and built wxWidgets 3.1.5 successfully on that box, for gtk3. This is how I built wxWidgets:

# build instructions from the docs/gtk directory
mkdir buildgtk
cd buildgtk
../configure --with-gtk
time make -j 4

This is how I was building pwsafe:

mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=Release -D NO_QR=ON -D NO_YUBI=ON -D NO_GTEST=ON -D wxWidgets_CONFIG_EXECUTABLE=~/Documents/wxWidgets-3.1.5/buildgtk/wx-config ..
make -j4

It got through all of the compiles, and then got the following right at the end:

[100%] Linking CXX executable pwsafe
/usr/bin/ld: /tmp/pwsafe.kLVuMZ.ltrans35.ltrans.o: in function `pwFiltersLCChoiceEditor::BeginEdit(int, int, wxGrid*)':
<artificial>:(.text+0x20a8): undefined reference to `wxGridCellEditorEvtHandler::ms_classInfo'
/usr/bin/ld: /tmp/pwsafe.kLVuMZ.ltrans35.ltrans.o: in function `pwFiltersFTChoiceEditor::BeginEdit(int, int, wxGrid*)':
<artificial>:(.text+0x5808): undefined reference to `wxGridCellEditorEvtHandler::ms_classInfo'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/pwsafe.dir/build.make:1158: pwsafe] Error 1
make[1]: *** [CMakeFiles/Makefile2:309: CMakeFiles/pwsafe.dir/all] Error 2
make: *** [Makefile:182: all] Error 2

Thoughts?

**Comment by tinker2much** [comment]
FYI: I also tried with the 1.14 release code, and it gets the identical pwsafe link error.

**Comment by KaiZin2018** [comment]
I cannot reproduce your problem. Building the wxWidgets library by

```
$ cd wxWidgets-3.1.5
$ mkdir buildgtk
$ cd buildgtk
$ ../configure --disable-shared --enable-stl --enable-utf8only     --enable-intl --enable-xlocale --enable-debug_gdb
```

and afterwards run make of pwsafe as mentioned by you everything runs well.

**Comment by KaiZin2018** [comment]
Es extend, I do not know exact which version of GTK is installed at my environment. May be a library/development package is missing?

**Comment by tinker2much** [comment]
For the record:
pi@pi4bn:~/Desktop $  sudo apt info libgtk-3-dev
Package: libgtk-3-dev
Version: 3.24.24-4+rpt3
Priority: optional
Section: libdevel
Source: gtk+3.0

I should also add, this is on the latest version of Raspberry Pi OS, which is based on Bullseye, and which is up to date. 

But that's moot, bacause I rebuilt wxWidgets with your suite of configure options, and that worked, and the subsequent builds of both the latest pwsafe and the 1.14 code worked too. In the past, I have built wxwidgets with such options as recommended by pwsafe, but I swear that I've also built it without them and had things work too. Perhaps I'm misremembering. Sorry to have wasted your time.

**Comment by rafaelx** [comment]
I faced the same problem building pwsafe with wxGtk 3.1.5.
When starting with a build of the wx lib in a newly created directory, the linker error disappeared.
I remember creating the wx libraries to test some bug fixes in the wxAUI component.
I may not have passed additional build options to the "configure" command for this purpose, but I'm no longer sure.

This issue was already reported on GitHub ([729](https://github.com/pwsafe/pwsafe/issues/729#issuecomment-903309203)) in the past and recently on [SourceForge](https://sourceforge.net/p/passwordsafe/bugs/1552/).
