### ISSUE TITLE
1.14 and 1.13 Installation err after 1.13 freezing post latest Ubuntu updates and removal from system

### ISSUE THREAD

**Issue by MrBonesJones** [pwsafe/pwsafe#836]
Ubuntu update to the most recent 03/07/22 via "software" app and update via CLI.
I am missing some upgrades, maybe where my issue is..?
PWS started freezing. I would close all other open software, password can only be killed in app:"System Monitor tab processes" and restart taking no risk for intrusion. 
I uninstalled PWS 1.3 and upon installing 1.4 see below.
Installation of 1.3 or 1.4:
I get as far as entering password approving install and receive
/Message in popup window
Unable to install passwordsafe:
The following packages have unmet dependencies:
/end
lists no dependencies..
I'm an FNG and use this cross platforms. I'll do what I can to help..

**Comment by ronys** [comment]
Can you try installing from the command line, e.g.,
$ sudo dpkg -i passwordsafe-ubuntu20-1.14-amd64.deb

As to freezing, can you provide a stack trace from a "frozen" process (for example, by attaching gdb to the pid and running the 'where' command)?

**Comment by MrBonesJones** [comment]
Tried install from CLI. This is the message:
$ sudo dpkg -i passwordsafe-ubuntu20-1.14-amd64.deb
dpkg: error: cannot access archive 'passwordsafe-ubuntu20-1.14-amd64.deb': No such file or directory

As to freezing, I removed the pkg in an effort to fix the err and I have not been able to reinstall it.

**Comment by ronys** [comment]
Hi,

The command should be run from the same directory in which the package is located. In more detail:

1. Download the deb file from [here](https://github.com/pwsafe/pwsafe/releases/download/1.14.0/passwordsafe-ubuntu20-1.14-amd64.deb)
2. Assuming the was downloaded via your browser into your Downloads directory:
$ cd ~/Downloads
$ sudo dpkg -i passwordsafe-ubuntu20-1.14-amd64.deb

**Comment by MrBonesJones** [comment]
Thanks! In my circle I say I am more than half nerd. In here I am more than half retard. 
Results:
:~/Downloads$ sudo dpkg -i passwordsafe-ubuntu20-1.14-amd64.deb
Selecting previously unselected package passwordsafe.
(Reading database ... 312485 files and directories currently installed.)
Preparing to unpack passwordsafe-ubuntu20-1.14-amd64.deb ...
Unpacking passwordsafe (1.14) ...
dpkg: dependency problems prevent configuration of passwordsafe:
 passwordsafe depends on libwxgtk3.0-gtk3-0v5 (>= 3.0.4); however:
  Package libwxgtk3.0-gtk3-0v5 is not installed.
 passwordsafe depends on libxerces-c3.2 (>= 3.1.0-1); however:
  Package libxerces-c3.2 is not installed.
 passwordsafe depends on libykpers-1-1 (>= 1.7.0-1); however:
  Package libykpers-1-1 is not installed.
 passwordsafe depends on libqrencode4 (>= 4.0.2-1); however:
  Package libqrencode4 is not installed.

dpkg: error processing package passwordsafe (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.9.1-1) ...
Errors were encountered while processing:
 passwordsafe

**Comment by MrBonesJones** [comment]
Looks like I am missing things or they need to be added to you installer.
Give me commands for what info you want to get the info you want and I'll provide it. At the very least I'll learn something.

**Comment by MrBonesJones** [comment]
With additional repositories added, via built in updater, for updating upon update I get the attached image.
![update](https://user-images.githubusercontent.com/93066982/157971290-7ea2097e-6f8f-4176-ad37-84dac1765229.png)

previously uncheck repositories were: universe and re
![reps](https://user-images.githubusercontent.com/93066982/157972958-a906dce6-0c0e-4e94-a844-f10e5ef3693c.png)
stricted

**Comment by ronys** [comment]
(The term 'retard' isn't appropriate or relevant here.)

To the point:
I'd start by bringing the package system to a consistent state by removing the "broken" passwordsafe package:
$ sudo dpkg --remove passwordsafe
Then I'd add the missing packages:
$ sudo apt install libwxgtk3.0-gtk3-0v5 libxerces-c3.2 libykpers-1-1 libqrencode4 
Finally I'd try reinstalling PasswordSafe
$ sudo dpkg -i passwordsafe-ubuntu20-1.14-amd64.deb

If there's still a problem, please copy the output of the lsb_release -a command.

**Comment by MrBonesJones** [comment]
this fixed it
apt --fix-broken install
If it freeze again I will try to provide the info you've requested previously.
