### ISSUE TITLE
Inconsistent field count in TSV export

### ISSUE THREAD

**Issue by lucasgonze** [pwsafe/pwsafe#841]
1. In pwsafe, do File→Export
2. get field counts using awk:
`$ awk -F "\t" 'OFS="\t" {print NF}' < export.txt | uniq`
3. Results show wide variance:

```
13
14
13
15
13
15
13
4
1
10
13
2
12
13
16
13
30
13
15
13
18
13
4
10
13
2
12
13
4
10
13
19
13
11
0
1
0
1
3
13
1
13
14
13



```

**Comment by lucasgonze** [comment]
It's possible this is caused by escaped tabs inside fields, but that would be rare at the most.

**Comment by lucasgonze** [comment]
I believe the cause is newlines in note fields. The fix would be either dropping such values (which can be done with awk) or concatenating lines with newlines stripped.

**Comment by ronys** [comment]
Closing this as I don't see a bug. Are we losing data?
An example of a test database with a couple of entries would be the best way to show the problem, if there is one.
