### ISSUE TITLE
Relationship between pwsafe.info, pwsafe.org, and github.com/pwsafe/pwsafe

### ISSUE THREAD

**Issue by lucasgonze** [pwsafe/pwsafe#851]
There are multiple entities providing closely related but distinct apps. In particular, an entity called App77 provides a thing at pwsafe.info - downloadable from  [the app store here](https://apps.apple.com/us/app/pwsafe-password-safe-compatible/id520993579?ign-mpt=uo%3D4&mt=12) - which acknowledges source code contributions from this project on Github, created by Rony Shapiro and linking to a site at pwsafe.org.

It is good for security to understand the human side of things. Is it possible to share more information?

<img width="278" alt="Screen Shot 2022-06-02 at 12 45 22 PM" src="https://user-images.githubusercontent.com/111581/171725376-e3120085-ef8b-4bab-8d5d-9e72b626b583.png">

**Comment by ronys** [comment]
The Windows and Linux versions are maintained from this repo.
There as several clones/derivatives that either use the code base or just the file format spec for their own implementations, such as pwsafe.info.

You can see the relation between this GitHub project and pwsafe.org at the top of https://github.com/pwsafe
Related projects are described in https://pwsafe.org/relatedprojects.shtml

Any other questions or suggestions on how to share this info?
