### ISSUE TITLE
No version 1.15 for MINT, latest Ubuntu does not work.

### ISSUE THREAD

**Issue by IanBlakeley** [pwsafe/pwsafe#852]
For a while there has not been a specific Linux Mint version. The ubuntu20 version works since current MINT is based on that. While the 1.15 ubuntu22 version will install it is missing files presumably part of the later Ubuntu version.

```
pwsafe: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by pwsafe)
pwsafe: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by pwsafe)
pwsafe: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by pwsafe)
```

**Comment by ronys** [comment]
Added packaged for Linux Mint 19 and 20.
