### ISSUE TITLE
No ubuntu 20 version for release 1.15

### ISSUE THREAD

**Issue by egaebel** [pwsafe/pwsafe#856]
I tried to use 1.14 on ubuntu 20.04, but encountered the bug detailed in: https://sourceforge.net/p/passwordsafe/bugs/1548/#69ce (verified that expanding the window makes it usable, but still, I'd rather have the version with the fix). So I went to download 1.15, noticed there was only a release for ubuntu22, but gave it a try anyway. After installing I can't open password safe at all.

Would be great to just have an ubuntu 20 release for version 1.15!

**Comment by bentolor** [comment]
Hi @egaebel ! I'm also Using Ubuntu 20.04 and you easily can install [`passwordsafe-linuxmint19-1.15-amd64.deb`](https://github.com/pwsafe/pwsafe/releases/download/1.15.0/passwordsafe-linuxmint19-1.15-amd64.deb): Contrary to the `19` in the title this version works perfectly with Ubuntu 20.04

**Comment by bentolor** [comment]
@egaebel Sorry, you are right: I installed [`passwordsafe-linuxmint20-1.15-amd64.deb`](https://github.com/pwsafe/pwsafe/releases/download/1.15.0/passwordsafe-linuxmint20-1.15-amd64.deb).

Linux Mint 20 is based on  Ubuntu 20.04, so this really should work. Sorry for the mixup!

**Comment by egaebel** [comment]
Right you are! That did the trick, thanks again for your help!

Agreed that it would be nice to have an alias or something for ubuntu 20 as I don't know off-hand which mint-ubuntu versions correspond and I'm likely not the only one.

**Comment by ronys** [comment]
Added Ubuntu 20 deb packages, no need to rely on implicit distro dependencies.
