### ISSUE TITLE
Apple silicon binary or brew and raspberry pi

### ISSUE THREAD

**Issue by anarchy89** [pwsafe/pwsafe#860]
I would like to use this on my macbook with apple silicon and raspberry pi 3, could you release binaries for those?

**Comment by ronys** [comment]
https://github.com/pwsafe/pwsafe/releases/download/1.15.0/PasswordSafe-1.15.dmg
https://github.com/pwsafe/pwsafe/releases/download/1.15.0/passwordsafe-ubuntu20-1.15-arm64.deb
