### ISSUE TITLE
aarch64 manjaro linux pinephone

### ISSUE THREAD

**Issue by magdesign** [pwsafe/pwsafe#863]
Trying to install pwsafe on Manjaro Linux on PinephonePro.

However, when trying to build/install via pamac I get the error; 

`not available for the aarch64 architecture`

Would be lovely to use pwsafe also on a linux phone.. any help on this?

**Comment by ronys** [comment]
I'm not familiar with PinephonePro, but pwsafe has been built successfully for RaspberryPi, which also has aarch64.

**Comment by magdesign** [comment]
this sounds great... I am not able to find a download.. would you mind sharing a link so I could test and report.

**Comment by ronys** [comment]
Try https://github.com/pwsafe/pwsafe/releases/download/1.15.0/passwordsafe-ubuntu20-1.15-arm64.deb

**Comment by magdesign** [comment]
I tried with downloading an arm64 .deb file and converting it:
```
# install yay
###########
sudo git clone https://aur.archlinux.org/yay-git.git
sudo chown -R youruser:youruser ./yay-git
makepkg -si

# install debtap
#############
yay -S debtap
sudo debtap -u

# download arm64 deb package
##########################
https://pkgs.org/download/passwordsafe

# convert with debtap (takes a moment)
################################
sudo debtap passwordsafe_1.12.0+dfsg-1_arm64.deb

```
but here it throws an error:

```

Warning: These dependencies (depend =   fields) could not be translated into Arch Linux packages names:
passwordsafe-common
```

and same error when trying install with:

`sudo pacman -U passwordsafe-1.12.0-1-aarch64.pkg.tar.zst
`

**Comment by magdesign** [comment]
Thanks!
with the file you provided I was able to install following my procedure written above...
It does not fit the screen, but I am able to use the passwords.

**Comment by ronys** [comment]
Is xvkbd installed?
What happens when you click on OK?

**Comment by magdesign** [comment]
Weird thing is that the keyboard popped up on the first launch.
I am on plasma, there we have the maliit keyboard as far as I know....
also asked in manjaro [forum](https://forum.manjaro.org/t/manjaro-arm-beta-11-with-plasma-mobile-pinephone-pinephone-pro/104746/43?u=magdesign)

When I click "OK" there is the error: "The combination can not be blank"

**Comment by magdesign** [comment]
Got a workaround so far:

When launching `pwsafe` from terminal, I get the keyboard

**Comment by magdesign** [comment]
Here is the working solution:

edit `/usr/local/share/applications/pwsafe.desktop`

and change:
`Exec=env GDK_BACKEND=x11 pwsafe %`

to:
`Exec=env GDK_BACKEND=wayland pwsafe %`

**Comment by magdesign** [comment]
Get the packed version [here](https://mega.nz/file/cqhkiR7B#MF9iWU1YSwNBpnOzIOABkakr4zTh-NngrWlYpvhjh6k), install it with:
`sudo pacman -U passwordsafe-1.12.0-1-aarch64.pkg.tar.zst `
and remember to make the changes as mentioned above in the .desktop file
