### ISSUE TITLE
pwsafe does not wait for Yubikey button press in Compare/Merge/Sync dialog 

### ISSUE THREAD

**Issue by HBrendy** [pwsafe/pwsafe#877]
Hey guys,

I am using pwsafe under Win10 and Ubuntu with a Yubikey and my safes became async. When trying to compare two password safes, I am not able to decrypt the second one in either of the Compare/Merge/Sync dialogs.

### Setting:
Ubuntu 20.04.4 LTS with 
PasswordSafe (linux) v1.15.0 from 16 Jun 2022 with 
YubiKey Standard (2014)

### Procedure and Behaviour:
I unlock DB file_A with the standard File Open Dialog via the Yubikey chalenge-response, then point the File|Compare dialog to DB file_B, enter the Safe Combination, plug-in the YubiKey again to have the YubiKey dialog button turn green/clickable; click on the YubiKey dialog button and the pop-up window "Incorrect passkey" is presented after 2-3 secs. The green LED on the YubiKey does not start to blink to signal the physical button press request. Both DBs use the same safe combination.

I guess, pwsafe might not start the challenge-response the same way it does during default DB opening.

Thank you guys for having a thought or two on this.

Best, 
Brendy

**Comment by ronys** [comment]
Works fine on Windows, able to reproduce the problem under Debian 11.
Investigating.

**Comment by HBrendy** [comment]
Yep, that was my second thought  (after posting the issue above ;). Every YubiKey interaction worked smoothly on Windows and I got my syncing done. Anyways, thank you so much for your continuous work on pwsafe!

**Comment by ronys** [comment]
Fixed in commit 66cd0d5e0, will be in next release.
