### ISSUE TITLE
Building issues on Gentoo Linux

### ISSUE THREAD

**Issue by LTerik** [pwsafe/pwsafe#88]
Trying to build pwsafe 0.98.1 on Gentoo Linux but having some problems. The last working version I have is 0.95.1. I have not tried to build the intermediate versions.

uname -a: `Linux kiwis 4.1.15-gentoo-r1 #1 SMP Sun Jan 24 12:16:32 PST 2016 x86_64 AMD Phenom(tm) II X2 555 Processor AuthenticAMD GNU/Linux`
gcc --version:  `gcc (Gentoo 4.9.3 p1.2, pie-0.6.3) 4.9.3`

With MINORVERSION now being defined to 98.1 i.e a floating point number, I get the following error:
```
g++ -c -o GCCUnicodeRelease/pwsafeapp.o  `/usr/bin/wx-config-3.0 --debug=no --unicode=yes --inplace --cxxflags` -DUNICODE -DNDEBUG -I../.. -fPIC  -O -Wall -DUSE_XML_LIBRARY=XERCES -DWCHAR_INCOMPATIBLE_XMLCH -DNO_YUBI -std=c++11 -std=c++11 pwsafeapp.cpp
pwsafeapp.cpp: In member function ‘virtual bool PwsafeApp::OnInit()’:
pwsafeapp.cpp:278:62: error: invalid operands of types ‘double’ and ‘int’ to binary ‘operator<<’
                                       DWORD((MINORVERSION << 16) | MAJORVERSION));
                                                              ^
```
I changed the line to `DWORD((DWORD(MINORVERSION) << 16) | MAJORVERSION));
` and the compilation went through with minor warnings about some unused variables and unused results. Thought I was home free at this point. But running the executable I get a segmentation fault.
```
~/Build/pwsafe-0.98.1BETA $ src/ui/wxWidgets/GCCUnicodeRelease/pwsafe
/usr/include/wx-3.0/wx/strvararg.h(456): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type
Segmentation fault
```

-Thomas

**Comment by LTerik** [comment]
Sorry, my bad about the "MINORVERSION" issue, I didn't read the already closed reports.
Would still appreciate any comments on the the Segmentation Fault issue. 

-Thomas

**Comment by mrueg** [comment]
@LTerik  have you tried to install app-admin/passwordsafe ?

**Comment by LTerik** [comment]
What a pleasant surprise, passwordsafe has been added as an ebuild!
Very recently as well. I gather from the similarities in the user name that you are the maintainer.

Thank you very much for the effort! It builds and works just fine. 

Now, I only have to figure out why my manual build didn't work, oh well...
