### ISSUE TITLE
FormatV3 documentation refers to changed link

### ISSUE THREAD

**Issue by Komplementariteten** [pwsafe/pwsafe#881]
[https://github.com/pwsafe/pwsafe/blob/master/docs/formatV3.txt](https://github.com/pwsafe/pwsafe/blob/master/docs/formatV3.txt) refers in 5. References to [KEYSTRETCH] http://www.schneier.com/paper-low-entropy.pdf which seem to change.
An up to date link is: [https://www.schneier.com/wp-content/uploads/2016/02/paper-low-entropy.pdf](https://www.schneier.com/wp-content/uploads/2016/02/paper-low-entropy.pdf)

**Comment by ronys** [comment]
Thanks! Fixed in c5f72d9cd
