### ISSUE TITLE
mkversion.pl can't find my git

### ISSUE THREAD

**Issue by nobugshere** [pwsafe/pwsafe#890]
On a "darwin" (MacOS) system, mkversion.pl only looks for a git executable in /usr/local/git/bin/git .  I don't know if there is a historic reason for that path but, on a new MacOS 12 / Xcode 14 system, my git is in /usr/bin/git, same place where it expects to find it on Linux.  Instead of only allowing one location per architecture, this proposed patch will search multiple places and use the first one found, which should cover all the cases of the original code, plus mine :-)

Test Environment:
M1 Mac Studio macOS 12.6 Monterey
Xcode 14.0.1
PasswordSafe 1.15 pulled from git master on 2022-10-12
wxWidgets 3.2.1 (installed via homebrew)

```
diff --git a/Misc/mkversion.pl b/Misc/mkversion.pl
index fd89079bd..b5cc2d9b4 100755
--- a/Misc/mkversion.pl
+++ b/Misc/mkversion.pl
@@ -25,9 +25,12 @@ sub usage {
     exit 1;
 }

-my %git_loc  = (
-       darwin => '/usr/local/git/bin/git',
-       linux  => '/usr/bin/git',
+# List of places to look for a git executable
+# We will use the first one found...
+my @git_loc = (
+    '/usr/local/git/bin/git',
+    '/usr/local/bin/git',
+    '/usr/bin/git',
 );

 &usage unless ($#ARGV >= 3 && $#ARGV <= 5);
@@ -48,10 +51,14 @@ foreach (@myargs) {
 }
 my ($TEMPLATE, $OUTFILE) = ($ARGV[0], $ARGV[1]);

-my $GIT = defined $git_loc{$^O}? $git_loc{$^O}: "/usr/local/bin/git";
-my $VERSTRING;
+# Find my git...
+my $GIT = undef;
+foreach (@git_loc) {
+    if (-x $_) { $GIT = $_; last; }
+}

-if (-x $GIT && (-d ".git" || -d "../../../.git")) {
+my $VERSTRING;
+if (defined $GIT && -x $GIT && (-d ".git" || -d "../../../.git")) {
     $VERSTRING = `$GIT describe --all --always --dirty=+  --long`;
     chomp $VERSTRING;
     # If string is of the form heads/master-0-g5f69087, drop everything
```

**Comment by ronys** [comment]
Thanks. Merged in commit df9cf1438
