### ISSUE TITLE
Unclear how to verify signature of downloaded files

### ISSUE THREAD

**Issue by veita** [pwsafe/pwsafe#891]
The GitHub download pages (e.g. https://github.com/pwsafe/pwsafe/releases?q=non-windows&expanded=true) provide signature files for verification.

However, it seems not to be documented how to actually verify the downloads.  Especially, for me it is unclear where to get the necessary public key from.

**Comment by ronys** [comment]
The public key file is referenced on the PasswordSafe site's [contact page](https://www.pwsafe.org/contact.php).
Here's the link: https://keyserver1.pgp.com/vkd/DownloadKey.event?keyid=0xB131423D7F2F1BB9
