### ISSUE TITLE
Port for suse tumbleweed

### ISSUE THREAD

**Issue by Dieter-23** [pwsafe/pwsafe#904]
Hi, i'm using suse tumbleweed. Is a port available for this os?

**Comment by ronys** [comment]
There is now.
https://github.com/pwsafe/pwsafe/releases/download/1.16.0/passwordsafe-opensuse-tumbleweed-1.16-x86_64.rpm

**Comment by RDKRACZ** [comment]
Hello, could you update the OpenSUSE version to v1.18? Also, it may be possible to create one rpm compatible with both Fedora and SUSE by specifying fedora or opensuse dependencies (using `Requires: (pkgA or pkgB)`) together.

**Comment by ronys** [comment]
https://github.com/pwsafe/pwsafe/releases/download/1.18.0/passwordsafe-opensuse-leap-1.18.rpm
