### ISSUE TITLE
Ubuntu debs for 0.98.1BETA are uninstallable on 15.10

### ISSUE THREAD

**Issue by bblough** [pwsafe/pwsafe#92]
Per the recent conversation on the passwordsafe-linux mailing list, the released debs are uninstallable on ubuntu 15.10.

Investigation shows that while the current control files in install/deb are correct, it appears that the debs recently built for ubuntu were built with an older or incorrect(Debian?) version of the control file.

The control file used specifies a dependency on  libwxgtk3.0-0, which is not installable in 15.10.  The most recent version of the control files allow for either libwxgtk3.0-0 or libwxgtk3.0-0v5 to satisfy the dependency.

A rebuild/rerelease of the ubuntu debs with the correct control file should fix the issue.

**Comment by ronys** [comment]
The problem isn't in the control file, so much as in the fact that the binary interface (ABI) has changed between Ubuntu 14 and 15, making it necessary to actually build PasswordSafe on Ubuntu 15.
I've finally gotten around to doing this, and the result may be downloaded from
[here](https://github.com/pwsafe/pwsafe/releases/download/0.98.1BETA/passwordsafe-ubuntu15-0.98.1BETA.i686.deb).
