### ISSUE TITLE
[Linux] Notes remain visible when database is auto-locked

### ISSUE THREAD

**Issue by shaicoleman** [pwsafe/pwsafe#924]
When editing an entry, the edit window continues to remain visible after the database is auto-locked.

If the notes contain any secrets, they'll be visible to anyone with access to the computer

Password Safe v1.16 on Linux Mint 21.1

Steps to reproduce:
1. Options: Security > [v] Lock password database after 1 mintue idle
2. Edit an entry
3. Wait for the database to auto-lock
4. Alt-Tab to Password Safe

Expected behavior:
The expected behaviour is the window should be hidden, and when entering the password is should be shown again.

Ideally when auto-locked, the state including unsaved changes should be serialized and encrypted in memory, clearing any plain-text notes in memory. When restored, it should restore and window, and any unsaved changes

**Comment by ronys** [comment]
Fixed in commit #779a64bc9, will be in next release.
