### ISSUE TITLE
An Arch Linux version

### ISSUE THREAD

**Issue by derbaltasar** [pwsafe/pwsafe#930]
Would be great, if you want, you can tell me how to compile, or better which compiler version is minimum need?

**Comment by computerquip-work** [comment]
Already exists: https://aur.archlinux.org/packages/passwordsafe

**Comment by rafaelx** [comment]
Instructions on how to build the application on Linux can be found here.

- https://github.com/pwsafe/pwsafe/blob/master/README.LINUX.DEVELOPERS.md
