### ISSUE TITLE
request linux 1.16 ubuntu20

### ISSUE THREAD

**Issue by samarium** [pwsafe/pwsafe#934]
@ronys per your request on the releases page for an issue to track requests :-)

I tried the ubuntu22 version, it broke like I suspected it would:

```
pwsafe: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by pwsafe)
pwsafe: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by pwsafe)
pwsafe: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by pwsafe)
```

I removed 1.16 and reverted to 1.15 ubuntu20 version.

It seems like the package should abort install without correct prereqs, but that requires understanding how the prereqs work, possibly on many linux variants, sounds like lots of work.

Another nice to have would be a deb repository of the packages hosted on github, maybe like [https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html](url), although again something similar for many linux variants would be lots of work.

Thanks

**Comment by anfokaboom** [comment]
Concur with @samarium 
Reverted to 1.15 as 1.16 ubuntu22 does not launch. Not sure of the technical cause yet. I installed via its APM so didn't see errors like samarium

I use Zorin 16.2 which is based on Ubuntu 22.04

**Comment by samarium** [comment]
@anfokaboom I didn't do anything special.  I noticed it didn't start from the desktop, so I opened a shell/terminal window, and manually started pwsafe.  The shared library loader showed the errors I reported.  Useful technique when the desktop gives you no error message.

**Comment by ronys** [comment]
Added https://github.com/pwsafe/pwsafe/releases/download/1.16.0/passwordsafe-ubuntu20-1.16-amd64.deb

**Comment by anfokaboom** [comment]
Fixed. Thanks @ronys !

**Comment by samarium** [comment]
Thanks @ronys.  Now starts OK. I also poked around the build instructions, thanks for that too.
