### ISSUE TITLE
Recurring checkbox default is updating existing entries

### ISSUE THREAD

**Issue by nobugshere** [pwsafe/pwsafe#935]
I'm using a local build pulled on 2/9/2023.  Now, whenever I view an existing entry and then click cancel, without making any changes, I get the pop-up that says something has changed.  I think it's related to this commit from 1/15:
[[FR890] "Recurring" checkbox is now set by default](https://github.com/pwsafe/pwsafe/commit/3e4c685bbc2f0bb0d19bb9a81df2588a8bca7484)

It's not only setting the default for a new entry, it's trying to modify the existing entries just because I look at them.  One way I confirmed this:
- Open an old existing entry that is set to Never expire
- Go to the date time tab and confirm the Recurring check box is now checked (it was not on by default when the entry was created)
- Click cancel, when I get the "are you sure" prompt click yes
- Open the same entry again and clear the Recurring check box
- click cancel - observe no confirmation pop-up

Environment:
Mac Studio M1 Max
MacOS 13.2 Ventura
Xcode 14.2
wxWidgets 3.2.2 (installed via homebrew)
PasswordSafe 1.16 pulled from git master on 2023-02-09

**Comment by n8w8** [comment]
I encounter the same issue, using stock Debian Bookworm (for the OS, as well as for the pwsafe package).
It seems they use the regular 1.16 release as source.
If I use the 1.15 package from Debian, it fixes the problem.

**Comment by nobugshere** [comment]
Just to work on this a little more, I made a branch and reverted commit 3e4c685 (FR980) and that resolved the issue of updating existing entries.  However, in the process of working on this, I realized the code isn't properly detecting or saving changes to the radio buttons, unless I change the date or days boxes as well.  The whole feature seems to need a little work. :-)

**Comment by aelinden** [comment]
Popup issue is fixed in commit 9533136.
