### ISSUE TITLE
Commit Passphrase (for Safe) via CLI

### ISSUE THREAD

**Issue by ColeBantam** [pwsafe/pwsafe#945]
Hello There,

I was checking out the CLI Options of pwsafe-cli.exe for a possible Project that pwsafe would be an central part of. Sadly it seems that there is no commandline parameter to pass the Safe-Combination (Passphrase for the Safe itself) via command-line. I found some hints that this feature was discussed a while ago. I'd like to ask, what the current state of this is?
Because without the possibility to pass the passphrase via script, the whole scripting-functions seems a bit useless. I mean how can I automate anything, if I have to sit in front of the screen and type in the passphrase every 2 seconds?

I understand that one might see this as a security issue to have Passphrases commited in cleartext, but the user that could possible see those is the one that already knows the safe combination, so I'd say the developer of the script should decide if this is acceptable or not in the given case. So I'd love to see such a function, because otherwise I'd need an other software who could import/export/"sync" several password-safes automatically.

Regards, Cole

**Comment by ronys** [comment]
Hi Cole,
Thanks for raising this issue. As much as I'd like to keep the master passphrase secure, I see your point.I think I'll implement something along the lines of openssl and gpg, allowing a file, env var, file descriptor and text for passing the master passphrase.
Another option would be something like ssh-agent, but that's a bit of an overkill, I think.

**Comment by ronys** [comment]
'-P <passphrase>'
'-Q <2nd passphrase>'

Currently undocumented.

**Comment by ronys** [comment]
Fixed in commit 8f526da3f

**Comment by ColeBantam** [comment]
Hi "ronys" :)
Wow, that was fast :) Thanks for implementing that so fast. Is there a Windows-Binary already available, that includes that commit?

**Comment by ronys** [comment]
This is already implement in the current Windows version (3.62). The commit fixed the "usage" message to document these options. Sorry about the confusion.

**Comment by ColeBantam** [comment]
Ahh, good to know :) Thanks for the Update :)
