### ISSUE TITLE
Powershell PSCredential intergration

### ISSUE THREAD

**Issue by tlourey** [pwsafe/pwsafe#947]
It would be great if there was some way to get Password Safe to create PSCredential objects for  Powershell. There could be a bunch of use cases but one is being able to use a Powershell cmdlet works with Passwordsafe to return a PSCredential Object that could be used in Powershell providing it still prompted for the masterpassword and get user confirmation to release the password to the PSCredential Object

eg: `$mycredobject = get-pwsafecredental -object username,password -title "servernamecred" -databasefile "c:\passwordsafe\mysafe.psafe3"`
this would 

- open password safe and the specified database
- ask for master password
- find the entry with the title "servernamecred"
- prompt user to confirm they are want to release the username and password from "servernamecred" entry
- return a PSCredential object to the variable $mycredobject

Another optional argument would be to use a background running instance locked database. Something like: 
`get-pwsafecredental -object username,password -title "servernamecred" -runningdatabase"` which would do the same as above but not use the file specififed but the already running instance. 

While this request implies the creation of powershell module, I think Password safe would need a way to programatticaly return a PSCredential object (or something similar). The module would most likley be seperate anyway but that first hurdle would need to be addressed.

**Comment by ronys** [comment]
Have you looked into using pwsafe-cli to do this?

**Comment by tlourey** [comment]
No but would it be able to pass the cred itself back to something after confirmation? Can you point me to some information about pwsafe-cli?

**Comment by ronys** [comment]
pwsafe-cli is part of the project deliverable. Here's the usage text:

Usage: pwsafe-cli safe --imp[=file] --text|--xml

       pwsafe-cli safe --exp[=file] --text|--xml

       pwsafe-cli safe --create

       pwsafe-cli safe --add=field1=value1,field2=value2,...

       pwsafe-cli safe --search=<text> [--ignore-case]
                      [--subset=<Field><OP><string>[/iI] [--fields=f1,f2,..]
                      [--delete | --update=Field1=Value1,Field2=Value2,.. | --print[=field1,field2...] ] [--yes]

       pwsafe-cli safe --diff=<other-safe>  [ --subset=<Field><OP><Value>[/iI] ]
                      [--fields=f1,f2,..] [--unified | --context | --sidebyside]
                      [--colwidth=column-size]

       pwsafe-cli safe --sync=<other-safe>  [ --subset=<Field><OP><string>[/iI] ] [ --fields=f1,f2,.. ] [--yes]

       pwsafe-cli safe --merge=<other-safe> [ --subset=<Field><OP><Value>[/iI] ] [--yes]

                        where OP is one of ==, !==, ^= !^=, $=, !$=, ~=, !~=
                         = => exactly similar
                         ^ => begins with
                         $ => ends with
                         ~ => contains
                         ! => negation
                        a trailing /i => case insensitive, /I => case sensitive

       Note that --passphrase <passphrase> and --passphrase2 <2nd passphrase> may be used to skip the prompt
       for the master passphrase(s). However, this should be avoided if possible for security reasons.

       Valid field names are:

                Group/Title, Username, Password, URL, AutoType,
                Created Time, Password Modified Time, Last Access Time, Password Expiry Date, Record Modified Time,
                History, Notes, Group, Title, Password Policy,
                Password Expiry Interval, Run Command, DCA, e-mail, Protected,
                UUID, Symbols, Shift+DCA, Password Policy Name, Keyboard Shortcut,

**Comment by tlourey** [comment]
I tried pwsafe-cli and it doesn't work well if I already have password safe open in the system tray. I get `"Couldn't lock file"`
Also (and this might be when executing in powershell) the master password was visible while typing, not masked ***

**Comment by ronys** [comment]
Fixed both in commit a5b36ab5d. Will be in next release.
