### ISSUE TITLE
Linux crash (gtk_box_gadget_distribute, GtkSpinButton)

### ISSUE THREAD

**Issue by zorbathut** [pwsafe/pwsafe#957]
Running this on Manjaro. I have an occasional crash when unlocking the database, with the following console message:

```
(pwsafe:673493): Gtk-CRITICAL **: 20:31:52.627: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(pwsafe:673493): Gtk-CRITICAL **: 20:31:52.628: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(pwsafe:673493): Gtk-CRITICAL **: 20:31:52.628: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(pwsafe:673493): Gtk-CRITICAL **: 20:31:52.628: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(pwsafe:673493): Gtk-CRITICAL **: 20:31:52.628: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(pwsafe:673493): Gtk-CRITICAL **: 20:31:52.645: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton
```

at which point it exits.

I have not been able to figure out how to reproduce this. Generally I just restart it and it works again, but it's kind of annoying.

I'll keep seeing if I can figure out what causes it; let me know if there's anything you'd like me to try.

**Comment by rafaelx** [comment]
I tried to reproduce the problem with the latest version built from the sources on Manjaro Ruah with the KDE environment.
I didn't see a crash or the mentioned console output.

Could you please provide some more information?

1. Which version of Manjaro with which desktop environment shows this problem?
2. How was the database locked? Via a timeout or manually by the user?
3. Was a dialog previously open when the database was locked? (Are there any other steps to consider?)
4. Could you please provide the information here that appears on the console when the About dialog is invoked from the menu (Help > About)?

**Comment by rafaelx** [comment]
Thank you for providing the information.

In addition to point 4)
If the application is started in the console and the About dialog is opened, then additional version information about the libraries used is output on the console. Could you please provide that information as well?

**Comment by zorbathut** [comment]
I'm afraid I actually don't see anything added.

![image](https://github.com/pwsafe/pwsafe/assets/160754/9b031ff6-2b1f-4df3-a7c6-33433761225c)

(The warnings show up on startup; I should've mentioned that earlier, although I don't think it's related.)

**Comment by rafaelx** [comment]
What I actually had in mind is the output on the console regarding the version of libraries used.

> Wx Version:
> wxWidgets Library (wxGTK port)
> Version 3.2.0 (Unicode: wchar_t, debug level: 1), compiled at Jul 18 2022 18:18:15
> 
> Runtime version of toolkit used is 3.24.
> Compile-time GTK+ version is 3.24.34.
> 
> pwsafe:[1045]: [libcurl] Curl Version: 7.84.0
> [libcurl] SSL Version: OpenSSL/1.1.1q

I forgot that these outputs are only given on a debug build. - Sorry if I caused any confusion.

**Comment by zorbathut** [comment]
I tried doing a local build, but it isn't displaying those either. What's the magic incantation to get a debug build on Linux?

**Comment by ronys** [comment]
Something like:
$ cd cloned-pwsafe-source-repo
$ mkdir build-dbg
$ cd build-dbg
$ cmake -DCMAKE_BUILD_TYPE=Debug ..
$ make

**Comment by zorbathut** [comment]
Hey, that did it. Thanks, `-DCMAKE_BUILD_TYPE=Debug` was the secret sauce :)

I went to the 1.16.0 tag and built from there. This is obviously not the same binary I had before, so this isn't immediately useful, but it *was* built on the same platform because I was "downloading" it through AUR, which does builds locally. So it might be the same as the other one would have printed if it had been debug-output.

```
(pwsafe:1583764): Gtk-WARNING **: 16:13:16.188: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(pwsafe:1583764): Gtk-WARNING **: 16:13:16.188: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
pwsafe:[1583764]: PWSprefs - using existing config file: /home/zorba/.pwsafe/pwsafe.cfg [R/W]
pwsafe:[1583764]: User-preferred language can't be activated: id= 276, name= 
pwsafe:[1583764]: User-preferred language can't be activated: id= 276, name= 
pwsafe:[1583764]: Couldn't load default language catalog for Chinese
pwsafe:[1583764]: Couldn't load default language catalog for Korean
pwsafe:[1583764]: Selected language: menu id= 10248
pwsafe:[1583764]: [wx] Wx Version:
wxWidgets Library (wxGTK port)
Version 3.2.2 (Unicode: wchar_t, debug level: 1),
compiled at Feb 13 2023 15:34:44

Runtime version of toolkit used is 3.24.
Compile-time GTK+ version is 3.24.36.

pwsafe:[1583764]: [libcurl] Curl Version: 8.0.1
[libcurl] SSL Version: OpenSSL/3.0.8
[libcurl] Supported Protocols: dict, file, ftp, ftps, gopher, gophers, http, https, imap, imaps, mqtt, pop3, pop3s, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
```

I'll keep running this built version for a while, I'll let you know if I get a crash out of it or if it's been long enough that it feels like it won't crash ever.

**Comment by zorbathut** [comment]
Well, that was fast.

```
pwsafe:[1583764]: [libcurl] Curl Version: 8.0.1
[libcurl] SSL Version: OpenSSL/3.0.8
[libcurl] Supported Protocols: dict, file, ftp, ftps, gopher, gophers, http, https, imap, imaps, mqtt, pop3, pop3s, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
pwsafe:[1583764]: Hide window <About Password Safe> (dialog)
pwsafe:[1583764]: Hide window <PasswordSafe - pwsafe.psafe3> (frame)
pwsafe:[1583764]: Skipped parallel attempt to unlock DB
pwsafe:[1583764]: Show window <PasswordSafe - pwsafe.psafe3>
```

Weird that it doesn't show the stuff the previous build did, though.

Gonna try running it in gdb, I guess.

**Comment by rafaelx** [comment]
According to the provided outputs, the About dialog was open before the timeout occurred. In this case I could also observe a crash after unlocking the database with version 1.16.0. With the latest version of the source code files from the repository, I could no longer reproduce the crash with the About dialog scenario. It's possible that commit [6a7e802](https://github.com/pwsafe/pwsafe/commit/6a7e802401d3adee7c6040cf884b966ba9ddd1c1) fixed the problem. See also Issue #988.
