### ISSUE TITLE
Windows 11: double-click pwsafe systray icon does not give input focus to password entry modal dialog.

### ISSUE THREAD

**Issue by AshleyT3** [pwsafe/pwsafe#959]
On Windows 11, double-clicking the pwsafe system tray icon (when pwsafe is locked) does not always give input focus to the password entry dialog. The behavior is inconsistent, where sometimes the pwsafe password entry dialog has input focus, other times it does not.

Prior to Windows 11, double-clicking on the green "locked safe" pwsafe system tray icon is certain to give input focus to the password entry dialog. 

Steps to reproduce the issue:
1. Safe is open and unlocked.
2. Choose File/Lock to lock the safe.
3. The pwsafe system tray icon is now green. Double-click the green pwsafe system tray icon, the password entry dialog appears (do not click anything).
4. Type keystrokes and notice they populate the password field. The password field regains input focus without the need to click any additional windows after the prior step 3. After typing some keystrokes, do not log into the safe, just click Cancel to dismiss the password entry dialog box. 
5. Double-click the green pwsafe systray icon, the password entry dialog appears. This time, however, if you type keystrokes, they do not go to the password input field. You must click the password entry dialog window to give it input focus.

This issue does not occur on Win10 but has been observed on two Win11 systems. Further testing revealed that the initial installation of a base Windows 11 ISO _downloaded_ in March does not reproduce the issue, but the same installation, after full updates, will reproduce the issue.

On Windows 11, SetForegroundWindow fails on the pwsafe password entry modal dialog if the prior pwsafe foreground window—the prior password entry modal dialog—was destroyed while active as the foreground window. Yet, the issue does not seem to occur when only a single click, and not a double-click, are required by the pwsafe system tray to activate the password entry modal dialog. Given these two observations, the following two successful workarounds/fixes were observed.

Two potential changes to workaround the new Windows 11 behavior:

- Change pwsafe's system tray notification for login from WM_LBUTTONDBLCLK to WM_LBUTTONUP. It seems the extra clicking on the Windows 11 system tray is one way to give rise to the issue. This is the recommended fix for two reasons: a) less churn, b) most all system tray icons use single-click to activate app-related windows. Password Safe's behavior here stands out and is an extra click so it takes longer, and is less ergonomically friendly compared to a single click. If going from double to single click is inadvisable for any reason... 
- Change pwsafe's password entry modal dialog box so it is a modeless acting as a modal dialog box, where it is not destroyed when dismissed, but instead hidden until next use when it will be made visible. This seems to work by avoiding destroying the app's then current foreground window upon dismissal which also seems to give rise to the problem. While this is conceptually easier than it sounds (already tested), full integration is more involved from dev/test/review standpoint.

**Comment by ronys** [comment]
Fix tested, documented & merged. Thanks!
