### ISSUE TITLE
entry fields are disabled for the Safe Combination Entry on v1.16 on Fedora 38

### ISSUE THREAD

**Issue by roehnan** [pwsafe/pwsafe#961]
When I open the app on Fedora 38, the entry field for Safe Combination and the checkboxes for "Open as read-only" and "Show Combination" are all disabled.

**Comment by roehnan** [comment]
If I run the app manually from the terminal with `pwsafe -c`, I can select the desired database and enter the master password. Clearly, there is a visibility management issue.

I have tried to edit the pwsafe.desktop launcher file to run with the `-c` command line argument but it doesn't work. Perhaps "closed" should be a configurable option?

**Comment by ronys** [comment]
Hi,

I couldn't reproduce this with passwordsafe-fedora37-1.16.rpm on a Fedora 38 VM.
The "open as read-only" checkbox will be marked and disabled if the user doesn't have write permission to the passwordsafe file.
I don't see how "Show Combination" can be disabled. Odd.

**Comment by roehnan** [comment]
It seems to be working now ¯\_(ツ)_/¯. I'll close the issue.
