### ISSUE TITLE
Linux PS: Enter not working to repeat a string search

### ISSUE THREAD

**Issue by anfokaboom** [pwsafe/pwsafe#963]
I have used PS on Windows extensively in the past, and I have noticed a feature that is not apparent in the Linux version. When I Ctrl+F to search and enter a string, I press enter to search which works. In Windows I could press enter again and it continues to search for the same string. In the Linux version, however, pressing enter again does nothing. Pressing the magnifying glass icon solves this, but it does slow things down.

For consideration.

**Comment by ronys** [comment]
You can also use F3 to the same effect.

**Comment by celane** [comment]
Used PS for many years on Linux, and yes, the behavior on search is changed...looks like the mouse gets displaced from the search box to the "PS tray icon" after you put in a search.

**Comment by anfokaboom** [comment]
> Used PS for many years on Linux, and yes, the behavior on search is changed...looks like the mouse gets displaced from the search box to the "PS tray icon" after you put in a search.

Yes, it seems unusual that the first search works using enter, then I have to change to F3 to continue.
