### ISSUE TITLE
ubuntu 23.04 lunar version please?

### ISSUE THREAD

**Issue by samarium** [pwsafe/pwsafe#964]
Can I get a lunar build please.  The kinetic build is a little flaky on lunar, and I wonder if it just needs to be rebuilt. 

Is there a LXC and/or docker image I can use to do a build, so it is less hassle for the maintainers?

**Comment by ronys** [comment]
Try https://pwsafe.org/tmp/passwordsafe-ubuntu23-1.16.1-amd64.deb (sig file https://pwsafe.org/tmp/passwordsafe-ubuntu23-1.16.1-amd64.deb.sig).

Please re-open this ticket is there's a problem.
