### ISSUE TITLE
Windows 11 Focus and window layering issues when interacting with Password Safe 3.62.0 system tray icon

### ISSUE THREAD

**Issue by keystrike** [pwsafe/pwsafe#965]
**Description**
I am using Password Safe version 3.62.0 on Windows 11, and I have encountered two focus-related issues when interacting with the application via the system tray icon.

**Issue 1:**
When opening the application from the system tray by double-clicking the icon using either a mouse or a physical press on the trackpad, the popup window and "Master Password:" textbox do not receive focus.

**Issue 2:**
When minimizing the application using the escape key and then clicking on the system tray icon to reopen it, the window appears behind the currently active window instead of in the foreground.

**Steps to reproduce:**

**Issue 1:**
1. Minimize Password Safe to the system tray and lock the safe.
2. Double-click the Password Safe icon in the system tray using either a mouse or a physical press on the trackpad.

**Issue 2:**

1. Unlock a safe and minimize Password Safe using the escape key.
2. Click the Password Safe icon in the system tray to reopen the application.

**Expected behavior:**
In both cases, upon opening the application, the popup window should appear in the foreground and automatically receive focus.

**Additional information:**
Interestingly, when using a touchpad and double-tapping (not physically clicking) the Password Safe icon in the system tray, the focus issues do not occur.

**Environment:**
Password Safe version: 3.62.0
Operating System: Windows 11

**Comment by ronys** [comment]
Fixed in commit c4911dcc6c6096b5430854fff0520ba24d2f0d21, will be in next release.
