### ISSUE TITLE
transifex pull requests generate excessive builds.sr.ht usage

### ISSUE THREAD

**Issue by ddevault** [pwsafe/pwsafe#983]
Hi there! I am an administrator with SourceHut. In the past 5 minutes, more than 75 builds have been submitted on builds.sr.ht to run CI jobs for the pull requests generated by transifex. This is an excessive consumption of resources which is not permitted on SourceHut. Please reconfigure your usage of builds.sr.ht accordingly to avoid excessive resource utilization.

**Comment by ronys** [comment]
Sorry - one time event due to a configuration change at transifex. Won't happen again, promise!

**Comment by ddevault** [comment]
Thanks!

**Comment by ddevault** [comment]
This has happened again. I have revoked your hottub OAuth token until you are able to demonstrate that the issue will not recur.

**Comment by ronys** [comment]
Looks like a problem with transifex's GitHub integration. I've unlinked the repo from transifex, as shown below, so I think it's safe to restore the OAuth token now. Thanks!

![image](https://github.com/pwsafe/pwsafe/assets/781072/053524d9-7513-4194-a2a1-a1738a7a9f05)

**Comment by ddevault** [comment]
Thanks! You should be able to log back into hottub and set up the integration again.
