### ISSUE TITLE
Non-windows: unable to edit/create new entry (v1.15 Mac)

### ISSUE THREAD

**Issue by martyzee** [pwsafe/pwsafe#984]
Launching `1.15.0` in MacOS Monterey 12.6.5 (21G531), editing an item or creating an item causes app to stall. Unable to do anything until esc is pressed, and pop-up appears. Cancelling then takes you back to main app.
Also, when clicking 'about password safe', app completely crashes with no escape. Requires a force quit

<img width="250" alt="Screenshot 2023-05-19 at 08 19 26" src="https://github.com/pwsafe/pwsafe/assets/85994286/7aa24130-3d5e-420d-b485-d098b87ee41f">

Attached another screenshot to show how the contrast is off on the launch screen too - not an issue just an fyi
<img width="492" alt="Screenshot 2023-05-19 at 08 25 12" src="https://github.com/pwsafe/pwsafe/assets/85994286/3793ab9d-e2f9-4e0f-b4e7-1e33469abf16">

**Comment by ronys** [comment]
Can you try 1.17.0? https://github.com/pwsafe/pwsafe/releases/download/1.17.0/PasswordSafe-1.17.dmg

**Comment by martyzee** [comment]
> Can you try 1.17.0? https://github.com/pwsafe/pwsafe/releases/download/1.17.0/PasswordSafe-1.17.dmg

Thanks Rony, have downloaded it and will test tomorrow if all goes well.

**Comment by martyzee** [comment]
Works great, thanks again
