### ISSUE TITLE
Version string at MacOS version

### ISSUE THREAD

**Issue by rafaelx** [pwsafe/pwsafe#993]
A patch has been posted on SourceForge to make the macOS application provide version information.
See [support ticket 433](https://sourceforge.net/p/passwordsafe/support-requests/433/) for more details.

Could someone please confirm if the version information is provided by the application and if the changes are still relevant?

**Comment by nobugshere** [comment]
I can confirm that this is still an issue.  I can work on it later this week.

**Comment by rafaelx** [comment]
Resolved by #995
